Return-Path: <klongfield.10162425@dealer.onstation.com>
X-Original-To: cobaltgroup@cp.monitor1.returnpath.net
Delivered-To: assurance@localhost.returnpath.net
Received: from mxa-d1.returnpath.net (unknown [10.8.2.117])
	by cpa-d1.returnpath.net (Postfix) with ESMTP id F41CC19825C
	for <cobaltgroup@cp.monitor1.returnpath.net>; Fri,  1 Apr 2011 10:25:18 -0600 (MDT)
Received: from osadmin02.tuk.cobaltgroup.com (cblt-tuk.cobaltgroup.com [216.231.226.21])
	by mxa-d1.returnpath.net (Postfix) with SMTP id 3BE71AD
	for <cobaltgroup@cp.monitor1.returnpath.net>; Fri,  1 Apr 2011 10:25:18 -0600 (MDT)
Received: (qmail 27934 invoked from network); 1 Apr 2011 16:25:17 -0000
Received: from localhost (HELO osadmin02.tuk.cobaltgroup.com) (127.0.0.1)
  by osadmin02.tuk.cobaltgroup.com with SMTP; 1 Apr 2011 16:25:17 -0000
Date: Fri, 1 Apr 2011 16:25:17 +0000 (UTC)
From: Hometown Motors <klongfield.10162425@dealer.onstation.com>
Reply-To: emailteam@cobalt.com
To: cobaltgroup@cp.monitor1.returnpath.net
Message-ID: <6426946.1413.1301675117949.JavaMail.tomcat@osadmin02>
Subject: [SAMPLE] 04-719314-2011 Chevy April DAP #1
MIME-Version: 1.0
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
X-OSTN-RCP: sample=true;domain=cp.monitor1.returnpath.net;dealer=6065

<html>
<head>
  <style type=3D"text/css">
    body, td, p { font-family: Verdana, Arial, sans-serif; font-size: 12px;=
 color: #000000; }
    .body { font-family: Verdana, Arial, sans-serif; font-size: 12px; color=
: #000000; }
    .shopinfo { font-size: 11px; color: #ffffff; }
    .boxtitle { font-size: 15px; color: #ffffff; font-weight: bold; }
    .promotitle { font-size: 16px; color: #dd0000; font-weight: bold; }
    .promoexp { font-size: 12px; font-weight: bold;}
    .small { font-size: 10px; }
    .smallgrey { font-size: 10px; color: #999999; }
    a.sm {color: #999999;}
 </style>
</head>
<body bgcolor=3D"#ffffff">
<table border=3D"0" cellpadding=3D"2" cellspacing=3D"0" align=3D"center" bg=
color=3D"#cccccc" width=3D"604"><tr><td>
<table width=3D"600" cellpadding=3D"0" cellspacing=3D"0" bgcolor=3D"#ffffff=
"><tr><td>
 <table width=3D"600" cellpadding=3D"1" cellspacing=3D"0" bgcolor=3D"#00000=
0">
 <tr><td><img src=3D"http://dealer.onstation.com/image/6065/shoplogo.gif" a=
lt=3D"Hometown Motors"></td></tr><tr><td><table width=3D"600" cellpadding=
=3D"4" cellspacing=3D"0" bgcolor=3D"#000000"><tr><td class=3D"shopinfo"><fo=
nt color=3D"#ffffff"><b>Hometown Motors</b> 605 Fifth Avenue South Suite 80=
0, Seattle, WA 98104-3889<br>  Sales: 1-800-909-8244 | Service: 1-800-909-8=
244   </font></td></tr></table></td></tr></table>
      <table width=3D"602" border=3D"0" cellpadding=3D"0" cellspacing=3D"0"=
 bgcolor=3D"#DCDCDC">
        <tr>
          <td height=3D"5" colspan=3D"5" />
        </tr>
        <tr>
                  <td height=3D"17" align=3D"center">
            <a href=3D"#navigation-ostn-button1">
              <font size=3D"1" face=3D"Helvetica, Geneva, Arial, SunSans-Re=
gular, sans-serif" color=3D"#000000">Home Page</font>
            </a>
          </td>
                  <td height=3D"17" align=3D"center">
            <a href=3D"#navigation-ostn-button9">
              <font size=3D"1" face=3D"Helvetica, Geneva, Arial, SunSans-Re=
gular, sans-serif" color=3D"#000000">Search New Vehicles</font>
            </a>
          </td>
                  <td height=3D"17" align=3D"center">
            <a href=3D"#navigation-ostn-button23">
              <font size=3D"1" face=3D"Helvetica, Geneva, Arial, SunSans-Re=
gular, sans-serif" color=3D"#000000">Search Used Vehicles</font>
            </a>
          </td>
                  <td height=3D"17" align=3D"center">
            <a href=3D"#navigation-ostn-button20">
              <font size=3D"1" face=3D"Helvetica, Geneva, Arial, SunSans-Re=
gular, sans-serif" color=3D"#000000">Appraise My Trade</font>
            </a>
          </td>
                  <td height=3D"17" align=3D"center">
            <a href=3D"#navigation-ostn-button29">
              <font size=3D"1" face=3D"Helvetica, Geneva, Arial, SunSans-Re=
gular, sans-serif" color=3D"#000000">Schedule Service</font>
            </a>
          </td>
                </tr>
        <tr>
          <td height=3D"7" colspan=3D"5" background=3D"http://oem.onstation=
.com/static/base0/Base0_NavBar_5bar_07.gif"/>
        </tr>
      </table>
    <table width=3D"600" border=3D"0" cellpadding=3D"10" cellspacing=3D"0" =
bgcolor=3D"#ffffff"><tr><td> <p>Dear John Doe,</p>

<p><table width=3D"580" border=3D"0" cellspacing=3D"0" cellpadding=3D"0" id=
=3D"04-719314-2011 Chevy April DAP #1">
  <tr>
    <td align=3D"left" valign=3D"top"><span style=3D"font-family:Arial, Hel=
vetica, sans-serif; font-size:12px; line-height:15px"><strong>It's not just=
 numbers&hellip;it's real world performance.</strong> The worksite doesn't =
care about a truck's spec sheet. What does matter is how those numbers tran=
slate into real-world results. To find out this info, Chevy hired AMCI Test=
ing to put Silverado HD, Ford Super Duty and Ram HD through a series of tes=
ts designed to simulate everyday scenarios. The result? Check out the video=
s and see for yourself how Silverado HD beat out the competition. <br />
      <br />
    </span></td>
  </tr>
</table>
<table width=3D"580" height=3D"291" border=3D"0" cellpadding=3D"0" cellspac=
ing=3D"0" bgcolor=3D"#000000" id=3D"Table_01">
=09<tr>
=09=09<td>
=09=09  <img src=3D"http://oem.onstation.com/static/GM/chevy/04_11dap/top_0=
1.jpg" width=3D"271" height=3D"57" alt=3D"Chevy Silverado" style=3D"display=
: block;" /></td>
=09=09<td width=3D"309" height=3D"57" align=3D"left" valign=3D"bottom" bgco=
lor=3D"#000000"><span style=3D"font-family:Arial, Helvetica, sans-serif; co=
lor:#FFFFFF; font-size:14px"><em>How does Silverado HD measure up?</em></sp=
an></td>
=09</tr>
=09<tr>
=09=09<td>
=09=09  <img src=3D"http://oem.onstation.com/static/GM/chevy/04_11dap/top_0=
3.jpg" width=3D"271" height=3D"101" alt=3D"Chevy Silverado" style=3D"displa=
y: block;" /></td>
=09=09<td>
=09=09  <img src=3D"http://oem.onstation.com/static/GM/chevy/04_11dap/top_0=
4.jpg" width=3D"309" height=3D"101" alt=3D"Check Out The Videos" style=3D"d=
isplay: block;" /></td>
=09</tr>
=09<tr>
=09=09<td colspan=3D"2">
=09=09  <img src=3D"http://oem.onstation.com/static/GM/chevy/04_11dap/top_0=
5.jpg" width=3D"580" height=3D"133" alt=3D"Silverado HD vs. the competition=
: Check out the Videos" style=3D"display: block;" /></td>
=09</tr>
</table>
<table id=3D"Table_01" width=3D"580" height=3D"427" border=3D"0" cellpaddin=
g=3D"0" cellspacing=3D"0">
=09<tr>
=09=09<td colspan=3D"5">
=09=09=09<img src=3D"http://oem.onstation.com/static/GM/chevy/04_11dap/midd=
le_01.gif" width=3D"580" height=3D"88" alt=3D"" style=3D"display: block;" /=
></td>
=09</tr>
=09<tr>
=09=09<td width=3D"20" height=3D"306" bgcolor=3D"#262525">&nbsp;</td>
=09=09<td align=3D"left" valign=3D"middle">
=09=09  <img src=3D"http://oem.onstation.com/static/GM/chevy/04_11dap/middl=
e_03.jpg" width=3D"140" height=3D"306" alt=3D"" style=3D"display: block;" /=
></td>
=09=09<td width=3D"354" height=3D"306" align=3D"left" valign=3D"top"><span =
style=3D"font-family:Arial, Helvetica, sans-serif; font-size:11px; color:#3=
33333; -webkit-text-size-adjust:none"><span style=3D"font-size:14px"><em><b=
r />
=09    Motor Trend's</em><strong> 2011 Truck of the Year</strong></span><br=
 />
<span style=3D"line-height:15px">Silverado HD's stronger frame and more pow=
erful drivetrain permit you to tow more and handle more payload than before=
. This potent combination didn't just beat out direct competitors in AMCI-c=
ertified tests, it beat out all trucks to be named the Motor Trend 2011 Tru=
ck of the Year. </span><br />
<br />
<br />
<br />
<span style=3D"font-size:14px"><strong>Duramax 6.6L Turbo-Diesel</strong></=
span><br />
<span style=3D"line-height:15px">The available Duramax 6.6L Turbo-Diesel de=
livers increased horsepower and torque numbers, as well as highway fuel eco=
nomy that was improved by more than 11%<sup>1</sup> over the previous gener=
ation. </span><br />
<br />
<br />
<br />
<span style=3D"font-size:14px"><strong>Allison<sup>&reg;</sup> Transmission=
</strong></span><br />
<span style=3D"line-height:15px">To handle all the torque and power created=
 by the updated Duramax Diesel, Chevy beefed up the available, legendary he=
avy-duty Allison=AE 6-speed transmission for a stronger torque converter an=
d larger output shaft </span></span><br />
<br /></td>
=09=09<td width=3D"48" height=3D"306">&nbsp;</td>
=09=09<td width=3D"18" height=3D"306" bgcolor=3D"#262525">&nbsp;</td>
=09</tr>
=09<tr>
=09=09<td colspan=3D"5">
=09=09=09<img src=3D"http://oem.onstation.com/static/GM/chevy/04_11dap/midd=
le_07.gif" width=3D"580" height=3D"33" alt=3D""></td>
=09</tr>
</table><table id=3D"Table_01" width=3D"580" height=3D"442" border=3D"0" ce=
llpadding=3D"0" cellspacing=3D"0">
=09<tr>
=09=09<td>
=09=09=09<a href=3D"$INSERTLINK_DEALERINVENTORY" target=3D"_blank"><img src=
=3D"http://oem.onstation.com/static/GM/chevy/04_11dap/bottom_01.jpg" alt=3D=
"View Silverado Inventory" width=3D"283" height=3D"86" border=3D"0" style=
=3D"display: block;" /></a></td>
=09=09<td>
=09=09  <a href=3D"#schedule-ostn-Sales" target=3D"_blank"><img src=3D"http=
://oem.onstation.com/static/GM/chevy/04_11dap/bottom_02.jpg" alt=3D"Schedul=
e Test Drive" width=3D"297" height=3D"86" border=3D"0" style=3D"display: bl=
ock;" /></a></td>
=09</tr>
=09<tr>
=09=09<td colspan=3D"2">
=09=09=09<a href=3D"$INSERTLINK_DEALERINVENTORY" target=3D"_blank"><img src=
=3D"http://oem.onstation.com/static/GM/chevy/04_11dap/bottom_03.jpg" alt=3D=
"Siverado lineup" width=3D"580" height=3D"102" border=3D"0" style=3D"displa=
y: block;" /></a></td>
=09</tr>
=09<tr>
=09=09<td colspan=3D"2">
=09=09=09<a href=3D"$INSERTLINK_DEALERINVENTORY" target=3D"_blank"><img src=
=3D"http://oem.onstation.com/static/GM/chevy/04_11dap/bottom_04.jpg" alt=3D=
"2011 Silverado HD" width=3D"580" height=3D"254" border=3D"0" style=3D"disp=
lay: block;" /></a></td>
=09</tr>
</table>
<table width=3D"580" border=3D"0" cellspacing=3D"0" cellpadding=3D"0">
  <tr>
    <td align=3D"left" valign=3D"top"><font face=3D"Arial, Helvetica, sans-=
serif"; size=3D"1" color=3D"#999999">1. Based on GM testing. <br />
<br />
Photos for illustrative purposes only. Dealer and agency not responsible fo=
r misprints or typographical errors. Manufacturer programs subject to chang=
e without notice.</font></td>
  </tr>
</table></p>
=20
      =20
<table><tr valign=3D"middle"><td><img src=3D"http://dealer.onstation.com/im=
g/email/schedule.gif" width=3D"28" height=3D"28" alt=3D" "></td><td> </td><=
td><a href=3D"#schedule-ostn-Sales">Schedule your appointment online today!=
</a><small> (24 hours a day, 7 days a week.)</small></td></tr></table>  <ta=
ble><tr valign=3D"center"><td><img src=3D"http://dealer.onstation.com/img/e=
mail/print.gif" width=3D"28" height=3D"28" alt=3D" "></td><td> </td><td><b>=
Please print this email and bring it with you on your next visit to redeem.=
</b></td></tr></table>  <p>
If you have any questions, please contact us.=20
We look forward to hearing from you soon!
<table width=3D"100%" border=3D"0" align=3D"center" cellpadding=3D"3">
  <tr>
    <td><div align=3D"center"><b>Sales: </b>1-800-909-8244</div></td>
    <td><div align=3D"center"><b>Service: </b>1-800-909-8244</div></td>    =
<td><p align=3D"center"><a href=3D"mailto:emailteam@cobalt.com">emailteam@c=
obalt.com</a></p></td>
  </tr>
</table>
</p>   <a href=3D"#schedule-ostn-Refer-A-Friend"><img src=3D"http://oem.ons=
tation.com/static/raf/send_savings1_raf_1a.gif" border=3D"0" align=3D"right=
"></a>
 <p>Sincerely,<br>
Your Friends at Hometown Motors</p>
 <p>To ensure continued delivery of these emails, please add us to your "sa=
fe list" or address book in your email program.</p>
 <hr size=3D"1">
<p style=3D"font-size: 12px; color: #333333;" align=3D"center">You are rece=
iving this promotional email as a customer of<BR><b>Hometown Motors</b>.<br=
><br>
To <a href=3D"#unsubscribe" style=3D"color: #0000FF;">unsubscribe</a> from =
future emails, please <a href=3D"#unsubscribe" style=3D"color: #0000FF;">cl=
ick here</a>.<br>
<a href=3D"#ostn-link-privacy" style=3D"color: #0000FF;">Privacy Informatio=
n</a>
<img src=3D"http://dealer.onstation.com/img/pclear.gif" width=3D"10" height=
=3D"10" alt=3D" ">
<BR>
<a href=3D"#ostn-link-home"><img src=3D"http://dealer.onstation.com/img/ema=
il/poweredby.gif" vspace=3D"10" border=3D"0" alt=3D" "></a></p>
</td></tr></table>
</td></tr></table>
</td></tr></table>
</body>
</html>
