Return-Path: <Amway@MagazineLine.com>
X-Original-To: americancollegiatemarketing@cp.monitor1.returnpath.net
Delivered-To: assurance@localhost.returnpath.net
Received: from mxa-d1.returnpath.net (unknown [10.8.2.117])
	by cpa-d1.returnpath.net (Postfix) with ESMTP id 66940198274
	for <americancollegiatemarketing@cp.monitor1.returnpath.net>; Fri,  1 Apr 2011 08:38:41 -0600 (MDT)
Received: from smtp3.magazineline.com (smtp3.magazineline.com [70.34.187.204])
	by mxa-d1.returnpath.net (Postfix) with ESMTP id 04CF6576
	for <americancollegiatemarketing@cp.monitor1.returnpath.net>; Fri,  1 Apr 2011 08:38:40 -0600 (MDT)
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed;
  s=s1024;d=magazineline.com;
  h=from:to:subject:date:message-id:mime-version:content-type;
  bh=vcYMKY0GBnmZ9vTGjlmJaQNW980=;
  b=SxdD/MdDbRh57tHyU9umSe9z4I9YMOEeLXvzFpP99ymPzOCuAGM4CDn89Zq9rixOkTxkdM2x
    hZKhXvHaQ8ysQBnRf/479I62g6LM/6FbJrdlrTHEa0KDFzr6atAnVvn1yl3G6J+s8B2lVds4
    MkZitG2uYZ+pd6bpv5q+8g+AGbI=
DomainKey-Signature: a=rsa-sha1; q=dns; c=nofws;
  s=s1024;d=magazineline.com;
  h=from:to:subject:date:message-id:mime-version:content-type;
  b=DeYgKh7LYDCoG81PrpRR/FY42JINdtoZOKo6Uc/+gO0QHaWdYry1wm6auS4puTw04GAgs6ab
    pAD+rCktPbxrE6q/aLR/fORJUKte6ZWi5Nx5F3iv0c3YzB/6MVjSvUl5jppLYo6pzSTjw2mS
    6vgJNmk9bczwTMnrlfEpAz4sXHM=
Received: from mail pickup service by smtp3.magazineline.com with Microsoft SMTPSVC;
	 Fri, 1 Apr 2011 10:38:39 -0400
thread-index: Acvwem/aq3cCRTUITXS83q+dsAqHPg==
Thread-Topic: April 2011 TPM Amway No Subs Spring Savings from MagazineLine
From: <Amway@MagazineLine.com>
To: <americancollegiatemarketing@cp.monitor1.returnpath.net>
Subject: April 2011 TPM Amway No Subs Spring Savings from MagazineLine
Date: Fri, 1 Apr 2011 10:38:16 -0400
Message-ID: <EF9C090C1310457C97AD9E1279F0BF68@acm.local>
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="----=_NextPart_000_0032_01CBF058.E8C87270"
X-Mailer: Microsoft CDO for Exchange 2000
Content-Class: urn:content-classes:message
Importance: normal
Priority: normal
X-MimeOLE: Produced By Microsoft MimeOLE V6.00.3790.4721
X-OriginalArrivalTime: 01 Apr 2011 14:38:39.0312 (UTC) FILETIME=[7D8ADD00:01CBF07A]

This is a multi-part message in MIME format.

------=_NextPart_000_0032_01CBF058.E8C87270
Content-Type: text/plain;
	charset="iso-8859-1"
Content-Transfer-Encoding: 7bit

If you have trouble viewing this email, please click here
<http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount
/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=homepage%2Ehtm&SiteID
=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&
utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y>  to see this
week's featured offers.

 
<http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount
/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=homepage%2Ehtm&SiteID
=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&
utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y>  
 <http://www.magazineline.com/images/email/20071105_drop_leftcap.gif>
<http://www.magazineline.com/images/email/20071105_drop_space.gif>
<http://www.magazineline.com/images/email/20071105_drop_div.gif> See All
Women's Magazines
<http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount
/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=%2E%2E%2FHaupt%2FCate
gory%2FCategory%5FWI%5F11%5F1%5F25%2Ehtml&SiteID=25&AffiliateID=LRC-0M35
7&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&ut
m_campaign=Amway&loadAllSubs=Y>
<http://www.magazineline.com/images/email/20071105_drop_div.gif> See All
Men's Magazines
<http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount
/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=%2E%2E%2FHaupt%2FCate
gory%2FCategory%5FMI%5F11%5F1%5F25%2Ehtml&SiteID=25&AffiliateID=LRC-0M35
7&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&ut
m_campaign=Amway&loadAllSubs=Y>
<http://www.magazineline.com/images/email/20071105_drop_div.gif> See All
Children's Magazines
<http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount
/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=%2E%2E%2FHaupt%2FCate
gory%2FCategory%5FCD%5F11%5F1%5F25%2Ehtml&SiteID=25&AffiliateID=LRC-0M35
7&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&ut
m_campaign=Amway&loadAllSubs=Y>
<http://www.magazineline.com/images/email/20071105_drop_div.gif> See All
Cooking and Food Magazines
<http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount
/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=%2E%2E%2FHaupt%2FCate
gory%2FCategory%5FFD%5F11%5F1%5F25%2Ehtml&SiteID=25&AffiliateID=LRC-0M35
7&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&ut
m_campaign=Amway&loadAllSubs=Y>
<http://www.magazineline.com/images/email/20071105_drop_div.gif> See All
Entertainment Magazines
<http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount
/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=%2E%2E%2FHaupt%2FCate
gory%2FCategory%5FAE%5F11%5F1%5F25%2Ehtml&SiteID=25&AffiliateID=LRC-0M35
7&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&ut
m_campaign=Amway&loadAllSubs=Y>
<http://www.magazineline.com/images/email/20071105_drop_div.gif> See All
News Magazines
<http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount
/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=%2E%2E%2FHaupt%2FCate
gory%2FCategory%5FNP%5F11%5F1%5F25%2Ehtml&SiteID=25&AffiliateID=LRC-0M35
7&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&ut
m_campaign=Amway&loadAllSubs=Y>
<http://www.magazineline.com/images/email/20071105_drop_div.gif> See All
Magazine Categories
<http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount
/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=category%2Ehtm&SiteID
=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&
utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y>
<http://www.magazineline.com/images/email/20071105_drop_div.gif>
<http://www.magazineline.com/images/email/20071105_drop_space.gif>
<http://www.magazineline.com/images/email/20071105_drop_rightcap.gif> 	
Dear Terri,

Save up to 85% on these Amway Member Favorites! Choose from
Entrepreneur, Good Housekeeping, Men's Health, or more than 900 other
great magazines. Click here
<http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount
/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=homepage%2Ehtm&SiteID
=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&
utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y>  to search for
your favorite now!

We hope Jessica Witte is enjoying their gift subscription to Life &
Style Weekly
<http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount
/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=Life%26StyleWeekly%2E
htm&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_s
ource=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y> .
Renew your gift below, and lock in your Amway Member price of just
$77.48. Then, check out our special recommendations for you below. And
remember - IBOs get 20.83%/50% PV/BV on every purchase!
 <http://www.magazineline.com/images/clear.gif> 
 
<http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount
/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=homepage%2Ehtm&SiteID
=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&
utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y> 

Extend your gift subscription to Life & Style Weekly!

 
<http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount
/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=Life%26StyleWeekly%2E
htm&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_s
ource=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y>
Life & Style Weekly
<http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount
/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=Life%26StyleWeekly%2E
htm&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_s
ource=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y> 
1 Year, 52 Issues
Regular Price: $155.48
Your Price: $77.48
You Save 50%
 
<http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount
/EasyRenewalPage.aspx&SiteID=25&AffiliateID=LRC-0M357&Action=Order&EID=1
03761460&Cust=72310624325&SendTo=C&SubID=13473265&utm_source=TPM&utm_med
ium=April+2011&utm_campaign=Amway&loadAllSubs=Y> 

A Gift For:
Jessica Witte
This month's recommendations for you
MagazineLine has great deals on over 900 magazines. Here are a few of
our recommendations for you. 

Save $153.50 on OK!!

Save $78.00 on In Touch Weekly!

Save $95.08 on National Enquirer!


 
<http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount
/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=OK%21%2Ehtm&SiteID=25
&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&utm
_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y>  
OK!
<http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount
/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=OK%21%2Ehtm&SiteID=25
&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&utm
_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y> 
1 Year, 51 Issues
Cover Price: $203.49
Your Price: $49.99
 
<http://www.magazineline.com/search.asp?SiteID=25&AffiliateID=LRC-0M357&
EID=103761460&Cust=72310624325&WCI=LandingPage&WCE=NetMyAccount/EasyRene
walPage.aspx&Action=NewOrder&TitleCode=MJA&OfferingCode=K7&utm_source=TP
M&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y>
<http://www.magazineline.com/search.asp?SiteID=25&AffiliateID=LRC-0M357&
EID=103761460&Cust=72310624325&WCI=LandingPage&WCE=NetMyAccount/EasyRene
walPage.aspx&Action=NewOrder&TitleCode=MJA&OfferingCode=K7&AutoRenew=yes
&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y> 
More Info
<http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount
/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=OK%21%2Ehtm&SiteID=25
&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&utm
_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y>  	
 
<http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount
/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=InTouchWeekly%2Ehtm&S
iteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source
=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y>  
In Touch Weekly
<http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount
/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=InTouchWeekly%2Ehtm&S
iteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source
=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y> 
1 Year, 52 Issues
Cover Price: $155.48
Your Price: $77.48
 
<http://www.magazineline.com/search.asp?SiteID=25&AffiliateID=LRC-0M357&
EID=103761460&Cust=72310624325&WCI=LandingPage&WCE=NetMyAccount/EasyRene
walPage.aspx&Action=NewOrder&TitleCode=QNN&OfferingCode=YE&utm_source=TP
M&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y>
<http://www.magazineline.com/search.asp?SiteID=25&AffiliateID=LRC-0M357&
EID=103761460&Cust=72310624325&WCI=LandingPage&WCE=NetMyAccount/EasyRene
walPage.aspx&Action=NewOrder&TitleCode=QNN&OfferingCode=YE&AutoRenew=yes
&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y> 
More Info
<http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount
/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=InTouchWeekly%2Ehtm&S
iteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source
=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y>  	
 
<http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount
/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=NationalEnquirer%2Eht
m&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_sou
rce=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y>  
National Enquirer
<http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount
/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=NationalEnquirer%2Eht
m&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_sou
rce=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y> 
1 Year, 52 Issues
Cover Price: $197.08
Your Price: $102.00
 
<http://www.magazineline.com/search.asp?SiteID=25&AffiliateID=LRC-0M357&
EID=103761460&Cust=72310624325&WCI=LandingPage&WCE=NetMyAccount/EasyRene
walPage.aspx&Action=NewOrder&TitleCode=EMY&OfferingCode=T3&utm_source=TP
M&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y>
<http://www.magazineline.com/search.asp?SiteID=25&AffiliateID=LRC-0M357&
EID=103761460&Cust=72310624325&WCI=LandingPage&WCE=NetMyAccount/EasyRene
walPage.aspx&Action=NewOrder&TitleCode=EMY&OfferingCode=T3&AutoRenew=yes
&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y> 
More Info
<http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount
/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=NationalEnquirer%2Eht
m&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_sou
rce=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y>  	

Find the perfect magazine now, click here
<http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount
/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=homepage%2Ehtm&SiteID
=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&
utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y>  to start your
search. 

Sincerely,
 <http://www.magazineline.com/images/email/20060714_KathySig.gif> 
Kathy Ross
Customer Service Manager
MagazineLine

P.S. Need a gift for a Teenage girl who's into fashion? Or a man who is
interested in fitness? What do you buy for an 8-year-old boy? Now you
can use our Gift Finder
<http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount
/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=%2E%2E%2FHaupt%2FCate
gory%2FGiftFinder%2Easpx&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&C
ust=72310624325&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&
loadAllSubs=Y>  to find the perfect magazine gift for anyone. And with
your Amway Member discount, magazine gifts are affordable as well as
easy to shop for.

You have received this email because you are a MagazineLine customer. If
you do not wish to receive future emails from us with information about
your subscriptions, new services or special savings opportunities,
please click here
<http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount
/EasyRenewalPage.aspx&SiteID=25&AffiliateID=LRC-0M357&Action=Prefs&EID=1
03761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&utm_campa
ign=Amway&loadAllSubs=Y>  to update your preferences.

MagazineLine is located at:
     4440 Hagadorn
     Okemos, MI 48864-2414

You can call toll-free 8 AM to midnight EDT to order, to make a payment,
or to change your address:
    1-800-828-8390.

Your Customer # is 723-10-6243-25
Your Savings Code is LRC-0M357 

			

------=_NextPart_000_0032_01CBF058.E8C87270
Content-Type: text/html
Content-Transfer-Encoding: 7bit

<!DOCTYPE HTML PUBLIC -//W3C//DTD HTML 4.01 Transitional//EN>
<html>
<head>
<title>Untitled Document</title>
<meta http-equiv=Content-Type content=text/html; charset=iso-8859-1>
<link rel=stylesheet href=http://www.magazineline.com/magazineline/googleteststyles.css type=text/css>
</head>
<body>
<p><center><small>If you have trouble viewing this email, please <a href="http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=homepage%2Ehtm&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y">click here</a> to see this week's featured offers.</small></center></p>
<table width=587 border=0 align=center cellpadding=0 cellspacing=0 bgcolor=#FFCC33>
<tr align=left>
<td height=70 colspan=2 valign=top><div align=left>
<a href="http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=homepage%2Ehtm&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y"><img src=http://www.magazineline.com/images/email/20090209_quixtar_hotline.gif height=70 border=0></a>
</div>
<div>
	<table align="center">
		<tr align="left">			<td height="26" align="center" valign="top"><img src="http://www.magazineline.com/images/email/20071105_drop_leftcap.gif" width="17" height="26"><img src="http://www.magazineline.com/images/email/20071105_drop_space.gif" width="13" height="26"><img src="http://www.magazineline.com/images/email/20071105_drop_div.gif" width="1" height="26"><a href="http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=%2E%2E%2FHaupt%2FCategory%2FCategory%5FWI%5F11%5F1%5F25%2Ehtml&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y"><img src="http://www.magazineline.com/images/email/20071105_drop_womens.gif" alt="See All Women's Magazines" name="womens" width="76" height="26" border="0"></a><img src="http://www.magazineline.com/images/email/20071105_drop_div.gif" width="1" height="26"><a href="http://www.magazineline.com/search
 .asp?wci=LandingPage&wce=NetMyAccount/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=%2E%2E%2FHaupt%2FCategory%2FCategory%5FMI%5F11%5F1%5F25%2Ehtml&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y"><img src="http://www.magazineline.com/images/email/20071105_drop_mens.gif" alt="See All Men's Magazines" name="mens" width="56" height="26" border="0"></a><img src="http://www.magazineline.com/images/email/20071105_drop_div.gif" width="1" height="26"><a href="http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=%2E%2E%2FHaupt%2FCategory%2FCategory%5FCD%5F11%5F1%5F25%2Ehtml&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y"><img src="http://www.magazineline.com/images/email/20071105_drop_childrens.gif" alt="See All Children's Magazines" name="chil
 drens" width="84" height="26" border="0"></a><img src="http://www.magazineline.com/images/email/20071105_drop_div.gif" width="1" height="26"><a href="http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=%2E%2E%2FHaupt%2FCategory%2FCategory%5FFD%5F11%5F1%5F25%2Ehtml&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y"><img src="http://www.magazineline.com/images/email/20080114_drop_food.gif" alt="See All Cooking and Food Magazines" name="food" width="52" height="26" border="0"></a><img src="http://www.magazineline.com/images/email/20071105_drop_div.gif" width="1" height="26"><a href="http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=%2E%2E%2FHaupt%2FCategory%2FCategory%5FAE%5F11%5F1%5F25%2Ehtml&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&u
 tm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y"><img src="http://www.magazineline.com/images/email/20071105_drop_ent.gif" alt="See All Entertainment Magazines" name="Entertainment" width="108" height="26" border="0"></a><img src="http://www.magazineline.com/images/email/20071105_drop_div.gif" width="1" height="26"><a href="http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=%2E%2E%2FHaupt%2FCategory%2FCategory%5FNP%5F11%5F1%5F25%2Ehtml&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y"><img src="http://www.magazineline.com/images/email/20080211_drop_news.gif" alt="See All News Magazines" name="News" width="55" height="26" border="0"></a><img src="http://www.magazineline.com/images/email/20071105_drop_div.gif" width="1" height="26"><a href="http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMy
 Account/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=category%2Ehtm&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y"><img src="http://www.magazineline.com/images/email/20071105_drop_allcats.gif" alt="See All Magazine Categories" name="allcats" width="111" height="26" border="0"></a><img src="http://www.magazineline.com/images/email/20071105_drop_div.gif" width="1" height="26"><img src="http://www.magazineline.com/images/email/20071105_drop_space.gif" width="13" height="26"><img src="http://www.magazineline.com/images/email/20071105_drop_rightcap.gif" width="18" height="26"></td>		</tr>	</table>
</div>
</td></tr>
<tr>
<td colspan=2 valign=top>
<table width=583 cellpadding=5 cellspacing=6 border=0 align=center bgcolor=#FFCC33>
<tr bgcolor=#FFFFFF>
<td height=105 colspan=2 valign=top>
<span class=bodyMED><b>
Dear Terri,</b></span></p>
<p class=bodyMED><span class=bodyMED><b>Save up to 85% on these Amway Member Favorites!</b> Choose from <i>Entrepreneur</i>, <i>Good Housekeeping</i>, <i>Men's Health</i>, or more than 900 other great magazines. <a href="http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=homepage%2Ehtm&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y">Click here</a> to search for your favorite now!<br><br></span><span class="BodyMED">We hope Jessica Witte is enjoying their gift subscription to <a href="http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=Life%26StyleWeekly%2Ehtm&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y">Life & Style Weekly</a>.   Renew your gift below, and lock in y
 our Amway Member price of just $77.48.  Then, check out our special recommendations for you below.  And remember - IBOs get 20.83%/50% PV/BV on every purchase!<br><img src=http://www.magazineline.com/images/clear.gif width=600 height=1>
</td></tr>
<tr>
<td width=50% height=186 valign=top bgcolor=#FFFFFF align="center"><p align=center><a href="http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=homepage%2Ehtm&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y"><img src=http://www.magazineline.com/images/email/spring_Amway.jpg border=0 ></a></p>
</td>
<td width="50%" valign="top" bgcolor="#FFFFFF">
<p align="left" class="redHead">Extend your gift subscription to Life & Style Weekly!</p>
<table><tr valign="top"><td><p align=left class=BodyMED><a href="http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=Life%26StyleWeekly%2Ehtm&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y"><img src=http://www.magazineline.com/images/covers/EMAmedium.jpg align=left border=0></a></td><td><span class=bodyMED><a href="http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=Life%26StyleWeekly%2Ehtm&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y">Life & Style Weekly</a></span><br><span class=bodySM>1 Year, 52 Issues<br>Regular Price: $155.48</span><br><span class="bodySM"><b>Your Price: $77.48</b></span><br><span class="bodySM" style="color: red">You Save 50%</span><br><a href="
 http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount/EasyRenewalPage.aspx&SiteID=25&AffiliateID=LRC-0M357&Action=Order&EID=103761460&Cust=72310624325&SendTo=C&SubID=13473265&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y"><img src=http://www.magazineline.com/images/email/20070219_ordernow.gif border=0></a></span></p><div style="display: block; border-style: solid; border-width: 3px; border-color: black; text-align: center; background-color: #ffffcc; color: red; padding: 3px;" class="bodyMED">A Gift For:<br><b>Jessica Witte</b></div></td></tr></table></td>
</tr>
<tr>
<td colspan=2 valign=top bgcolor=#FFFFFF>
<p align=left>
<span class="bluehead">This month's recommendations for you</span><br>
<span class="bodyMED">MagazineLine has great deals on over 900 magazines. Here are a few of our recommendations for you. </span>
</p>
<div align=center>
<table width=100% border=0 cellspacing=5 cellpadding=0>
<tr>
<td width="33%" align="center" valign="top"><p align="center" class="redPrice">Save $153.50 on OK!!</p></td>
<td width="33%" align="center" valign="top"><p align="center" class="redPrice">Save $78.00 on In Touch Weekly!</p></td>
<td width="33%" align="center" valign="top"><p align="center" class="redPrice">Save $95.08 on National Enquirer!</p></td>
</tr>
<tr>
<td align=center valign=top><br>
<a href="http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=OK%21%2Ehtm&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y"><img src=http://www.magazineline.com/images/covers/MJAmedium.jpg width=100 height=132  border=0></a>
<br>
<span class=bodyMED><a href="http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=OK%21%2Ehtm&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y">OK!</a></span><br>
<span class=bodySM>1 Year, 51 Issues<br>
Cover Price: $203.49<br>
<b>Your Price: $49.99</b></span><br>
<a href="http://www.magazineline.com/search.asp?SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&WCI=LandingPage&WCE=NetMyAccount/EasyRenewalPage.aspx&Action=NewOrder&TitleCode=MJA&OfferingCode=K7&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y"><img src=http://www.magazineline.com/images/email/buybuttonsm1.gif border=0></a>
<a href="http://www.magazineline.com/search.asp?SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&WCI=LandingPage&WCE=NetMyAccount/EasyRenewalPage.aspx&Action=NewOrder&TitleCode=MJA&OfferingCode=K7&AutoRenew=yes&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y"><img src=http://www.magazineline.com/images/email/buygiftbtnsmw.gif border=0></a><br>
<font face=verdana size=1><a href="http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=OK%21%2Ehtm&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y">More Info</a></font>
</span>
</td>
<td align=center valign=top><br>
<a href="http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=InTouchWeekly%2Ehtm&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y"><img src=http://www.magazineline.com/images/covers/QNNmedium.jpg width=100 height=132  border=0></a>
<br>
<span class=bodyMED><a href="http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=InTouchWeekly%2Ehtm&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y">In Touch Weekly</a></span><br>
<span class=bodySM>1 Year, 52 Issues<br>
Cover Price: $155.48<br>
<b>Your Price: $77.48</b></span><br>
<a href="http://www.magazineline.com/search.asp?SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&WCI=LandingPage&WCE=NetMyAccount/EasyRenewalPage.aspx&Action=NewOrder&TitleCode=QNN&OfferingCode=YE&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y"><img src=http://www.magazineline.com/images/email/buybuttonsm1.gif border=0></a>
<a href="http://www.magazineline.com/search.asp?SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&WCI=LandingPage&WCE=NetMyAccount/EasyRenewalPage.aspx&Action=NewOrder&TitleCode=QNN&OfferingCode=YE&AutoRenew=yes&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y"><img src=http://www.magazineline.com/images/email/buygiftbtnsmw.gif border=0></a><br>
<font face=verdana size=1><a href="http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=InTouchWeekly%2Ehtm&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y">More Info</a></font>
</span>
</td>
<td align=center valign=top><br>
<a href="http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=NationalEnquirer%2Ehtm&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y"><img src=http://www.magazineline.com/images/covers/EMYmedium.jpg width=100 height=132  border=0></a>
<br>
<span class=bodyMED><a href="http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=NationalEnquirer%2Ehtm&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y">National Enquirer</a></span><br>
<span class=bodySM>1 Year, 52 Issues<br>
Cover Price: $197.08<br>
<b>Your Price: $102.00</b></span><br>
<a href="http://www.magazineline.com/search.asp?SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&WCI=LandingPage&WCE=NetMyAccount/EasyRenewalPage.aspx&Action=NewOrder&TitleCode=EMY&OfferingCode=T3&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y"><img src=http://www.magazineline.com/images/email/buybuttonsm1.gif border=0></a>
<a href="http://www.magazineline.com/search.asp?SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&WCI=LandingPage&WCE=NetMyAccount/EasyRenewalPage.aspx&Action=NewOrder&TitleCode=EMY&OfferingCode=T3&AutoRenew=yes&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y"><img src=http://www.magazineline.com/images/email/buygiftbtnsmw.gif border=0></a><br>
<font face=verdana size=1><a href="http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=NationalEnquirer%2Ehtm&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y">More Info</a></font>
</span>
</td>
</tr>
</table>
</div>
<p class=bodyMED>Find the perfect magazine now, <a href="http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=homepage%2Ehtm&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y">click here</a> to start your search.
<p>
<p align=left><span class=bodyMED> Sincerely,<br>
<img src=http://www.magazineline.com/images/email/20060714_KathySig.gif><br>
Kathy Ross<br>Customer Service Manager<br>
MagazineLine</span></p>
<p align=left><span class=bodyMED>P.S. Need a gift for a Teenage girl who's into fashion? Or a man who is interested in fitness? What do you buy for an 8-year-old boy?  Now you can use our <a href="http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount/EasyRenewalpage.aspx&Action=StaticPage&StaticPage=%2E%2E%2FHaupt%2FCategory%2FGiftFinder%2Easpx&SiteID=25&AffiliateID=LRC-0M357&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y">Gift Finder</a> to find the perfect magazine gift for anyone. And with your Amway Member discount, magazine gifts are affordable as well as easy to shop for.</span></p>
</td>
</tr>
<tr>
<td height=180 colspan=4 valign=top><p align=left><font face=Arial, Helvetica, sans-serif size=1>
You have received this email because you are a MagazineLine customer. If you do not wish to receive future emails from us with information about your subscriptions, new services or special savings opportunities, please <a href="http://www.magazineline.com/search.asp?wci=LandingPage&wce=NetMyAccount/EasyRenewalPage.aspx&SiteID=25&AffiliateID=LRC-0M357&Action=Prefs&EID=103761460&Cust=72310624325&utm_source=TPM&utm_medium=April+2011&utm_campaign=Amway&loadAllSubs=Y">click here</a> to update your preferences.</font></p><p align=left><font face=Arial, Helvetica, sans-serif size=1>
MagazineLine is located at:<br></font><font face=Arial, Helvetica, sans-serif size=1>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4440 Hagadorn<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Okemos, MI 48864-2414</font></p>
<p align=left><font face=Arial, Helvetica, sans-serif size=1>
You can call toll-free 8 AM to midnight EDT to order, to make a payment, or to change your address:<br></font>
<font face=Arial, Helvetica, sans-serif size=1>&nbsp;&nbsp;&nbsp;&nbsp;1-800-828-8390.</font></p>
<p align=left><font face=Arial, Helvetica, sans-serif size=1><b>
<b>Your Customer # is 723-10-6243-25</b><br>
<b>Your Savings Code is LRC-0M357</b>
</b></font></p></td>
</tr>
</table></td>
</tr>
<tr>
<td height=1></td>
<td width=767></td>
<td></td>
</tr>
</table>
</body>
</html>

------=_NextPart_000_0032_01CBF058.E8C87270--
