Return-Path: <bounce-17011457_HTML-295436918-26481642-10016540-37@bounce.sls.enewsaxs.com>
X-Original-To: aeg@cp.delivery.ncrcustomerpower.com
Delivered-To: assurance@localhost.returnpath.net
Received: from mxa-d1.returnpath.net (unknown [10.8.2.117])
	by cpa-d1.returnpath.net (Postfix) with ESMTP id 72714198272
	for <aeg@cp.delivery.ncrcustomerpower.com>; Fri,  1 Apr 2011 12:06:36 -0600 (MDT)
Received: from mta.sls.enewsaxs.com (mta.sls.enewsaxs.com [64.132.89.25])
	by mxa-d1.returnpath.net (Postfix) with ESMTP id 014F1F99
	for <aeg@cp.delivery.ncrcustomerpower.com>; Fri,  1 Apr 2011 12:06:36 -0600 (MDT)
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; s=200608; d=events.lagalaxy.com;
 h=From:To:Subject:Date:List-Unsubscribe:MIME-Version:Reply-To:Message-ID:Content-Type:Content-Transfer-Encoding; i=enews@events.lagalaxy.com;
 bh=FKdYuRbX4MLx8jwGZMeClvG4XuI=;
 b=J3KDT/5dKurpogHe/xXkDrR8tJpjNaStAd3EaVJnnuc49A0NZG9M+meFSJpqwCV/J4blSrHV8Wzq
   E4PrAxOKXHxx0vqIo1OxUY4Z+3Adb5r3BYU78pC+8pwKGIW7IQVxkRRjMlccuTWDe04pxPKLTc/w
   nHYhWZZBrNPezfpBZEI=
DomainKey-Signature: a=rsa-sha1; c=nofws; q=dns; s=200608; d=events.lagalaxy.com;
 b=tzuRFzrkMXsBp9VRhxb23h2oRZLmnk6ITXnm7F3UxGRWy82WWojdhJ+VkL/b9p8S+voO/tjX7dNK
   J5y+5Nvx8onr6x5IaHy5TtSoWXtJQpD/BGOZbmFXlcJ/ovIWj6bYjF/Fv6ZDOCxUwJ5e1446r6jB
   MmzPff1ga34Kb11AOvQ=;
Received: by mta.sls.enewsaxs.com (PowerMTA(TM) v3.5r15) id hioa2o0ie1sa for <aeg@cp.delivery.ncrcustomerpower.com>; Fri, 1 Apr 2011 12:06:25 -0600 (envelope-from <bounce-17011457_HTML-295436918-26481642-10016540-37@bounce.sls.enewsaxs.com>)
From: "LA Galaxy" <enews@events.lagalaxy.com>
To: <aeg@cp.delivery.ncrcustomerpower.com>
Subject: April Fool's Day Offer, Save up to 40% with no fees
Date: Fri, 01 Apr 2011 12:06:22 -0600
List-Unsubscribe: <mailto:leave-fc5115777565057970131f2d205921-fe2016797060077b7c1578-fe5e1676716c057b7116-fe6e1570756502787114-ff951777@leave.sls.enewsaxs.com>
MIME-Version: 1.0
Reply-To: "LA Galaxy" <reply-fe5e1676716c057b7116-17011457_HTML-295436918-10016540-37@events.lagalaxy.com>
x-job: 10016540_26481642
Message-ID: <3709e1a3-663f-464c-a38f-584ae8c9fe24@xtinmta105.xt.local>
Content-Type: text/html;
	charset="us-ascii"
Content-Transfer-Encoding: 7bit

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<!-- RegionStart[ socialslot:"The Gold Standard", title:"LA Galaxy:", description:"See the Galaxy take on the brightest stars of MLS"] --><head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<title>LA Galaxy: The Gold Standard</title>
</head>
 
<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" bgcolor="#CCCCCC">
 
<table align="center" width="100%" height="100%" cellspacing="0" cellpadding="0" border="0" bgcolor="#CCCCCC"> 
<tr>
<td><table width="580" bgcolor="#FFFFFF" border="0" cellpadding="0" cellspacing="0" align="center">
<tr> 
  <td align="center" valign="top"><img src="http://www.aeginteractive.com/galaxy/images/newsletter/nofees2.jpg" alt="" width="580" height="520" border="0" usemap="#Map" /></td>
</tr>
<tr>
  <td align="center" valign="top" bgcolor="#CCCCCC">&nbsp;</td>
</tr>
</table></td>
</tr>
</table>
<br />

<map name="NavigationMap" id="NavigationMap">
<area shape="rect" coords="3,-1,60,27" href="http://click.sls.enewsaxs.com/?qs=403635d4baaee603030906ef7d225c11cd4f1331f3983b9e8fd93b0135729179dc99f0d99e374969" target="_blank" />
<area shape="rect" coords="59,-2,132,27" href="http://click.sls.enewsaxs.com/?qs=403635d4baaee603085d74d98e586e9fe9471632180988b684c202e99d16bf0a8841dd7a79240ce2" target="_blank" />
<area shape="rect" coords="131,-1,186,26" href="http://click.sls.enewsaxs.com/?qs=403635d4baaee603e225d617792487da814d36832d3f10110a84dc36c71e3a7244f846ac6c713c53" target="_blank" />
<area shape="rect" coords="186,-1,234,33" href="http://click.sls.enewsaxs.com/?qs=403635d4baaee603fc190ab3cd872fb41cd7410070efc3d3fae2a4d52718083c7775f8079252d94f" target="_blank" />
<area shape="rect" coords="233,-2,292,26" href="http://click.sls.enewsaxs.com/?qs=403635d4baaee603dfcf5f3e1cfb4b16eb6ac9cea166d4493b388e40162df96f8ad773097aedbf38" target="_blank" />
<area shape="rect" coords="291,-2,351,28" href="http://click.sls.enewsaxs.com/?qs=403635d4baaee60326875f555e08271d610cd5aa5b9ddd2975c9b3b19f7abb229bcde6e99085a265" target="_blank" />
<area shape="rect" coords="351,-2,393,26" href="http://click.sls.enewsaxs.com/?qs=403635d4baaee603d21fbe6c2c1dae6662811ccbcba78686a0ce2698f5fc0ae9e757e6749e839c8e" target="_blank" />
<area shape="rect" coords="397,-2,479,26" href="http://click.sls.enewsaxs.com/?qs=403635d4baaee603551a8be6a0c39f12c8b82ef6d0d124c60a827d95d29277b97acfb515ef8acbee" target="_blank" />
<area shape="rect" coords="480,-2,577,28" href="http://click.sls.enewsaxs.com/?qs=403635d4baaee603b9b94e569744851d0f759efcf064cabc353100965ae4e9fbc985d2b9d3665811" target="_blank" />
</map>

<map name="SocialMap" id="SocialMap">
<area shape="rect" coords="1,1,61,26" href="http://click.sls.enewsaxs.com/?qs=403635d4baaee60313fb65f0aedd496973f47a60e890ad2beb2c09636f6656e9e484da3caacad04e" target="_blank" />
<area shape="rect" coords="123,1,214,26" href="http://click.sls.enewsaxs.com/?qs=403635d4baaee6032d59749a43ec37db68952e0415bb8f8fa6e6a0a0ce6dc92b55af02d20f6fda95" />
<area shape="rect" coords="215,1,259,26" href="http://click.sls.enewsaxs.com/?qs=403635d4baaee603b11e6e99d05df5d73107ce5034b4ede507e16ae8dcc46d1947df1b34da82180d" target="_blank" />
<area shape="rect" coords="260,1,346,26" href="http://click.sls.enewsaxs.com/?qs=403635d4baaee6037287f8e076b5697e73403ffa83253a914f0317089c5719d9e102ca49281a9bfd" target="_blank" />
<area shape="rect" coords="347,1,433,26" href="http://click.sls.enewsaxs.com/?qs=403635d4baaee603ade345be2f89f94e2460736f26fc3b25ab4daeb43a6fd175f284676d8a889825" target="_blank" />
<area shape="rect" coords="434,1,517,26" href="http://click.sls.enewsaxs.com/?qs=403635d4baaee60384974b8a0f479ac3d6abf04539613f5c7e9087a6488ffe6f1762310b66f87463" target="_blank" />
<area shape="rect" coords="518,1,580,26" href="http://click.sls.enewsaxs.com/?qs=403635d4baaee603b3fdebc4505e731b08936eeae08dff71040c1d5c353b450abedea0350703fff9" target="_blank" />
</map>

<img src="http://click.sls.enewsaxs.com/open.aspx?ffcb10-fe5e1676716c057b7116-fdd41571746402787513717767-fe6e1570756502787114-fe651577756505797013-fe2016797060077b7c1578-ff951777" width="1" height="1">
<map name="Map" id="Map">
  <area shape="rect" coords="9,636,10,638" href="#" />
  <area shape="rect" coords="3,159,312,342" href="http://click.sls.enewsaxs.com/?qs=403635d4baaee603e6829927f0610a8652c1328963a46df03adf4232452444843ccdb3ec4887c104" />
  <area shape="rect" coords="7,346,317,519" href="http://click.sls.enewsaxs.com/?qs=403635d4baaee60339ddf1285b2a8eb69842f1a00df4693bda47c09af5b35b652d082a00d49c580c" />
</map>
</body>
<!-- RegionEnd[ socialslot:"The Gold Standard"] -->
<!-- http://click.sls.enewsaxs.com/profile_center.aspx?s=fe2016797060077b7c1578&mid=fe6e1570756502787114&j=fe5e1676716c057b7116&l=fe651577756505797013&jb=ff951777&ju= --></html>  
 


