Return-Path: <out-582632-B2C71BD37AF148CE9D728B61264F854D@mail.beliefnet.com>
X-Original-To: beliefnet@cp.monitor1.returnpath.net
Delivered-To: assurance@localhost.returnpath.net
Received: from mxa-d1.returnpath.net (unknown [10.8.2.117])
	by cpa-d1.returnpath.net (Postfix) with ESMTP id 4F39C19825C
	for <beliefnet@cp.monitor1.returnpath.net>; Fri,  1 Apr 2011 08:12:01 -0600 (MDT)
Received: from mail1101.mail.beliefnet.com (mail1101.mail.beliefnet.com [64.27.69.101])
	by mxa-d1.returnpath.net (Postfix) with ESMTP id 6275D992
	for <beliefnet@cp.monitor1.returnpath.net>; Fri,  1 Apr 2011 08:12:00 -0600 (MDT)
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; s=default; d=mail.beliefnet.com;
 h=From:Reply-To:To:Message-ID:Subject:MIME-Version:Content-Type:Content-Transfer-Encoding; i=specialoffers@mail.beliefnet.com;
 bh=kwfm9qePWfYmPSIHlEjFYVCYzlg=;
 b=SNIGrGXvBRXp4hSf72CttBCV3dmQd3F1UphY00hAKhNFiOhPCUtwTknlclAzlkYJ2OBGBXpoNxlA
   EIF4Uu4o5Q==
DomainKey-Signature: a=rsa-sha1; c=nofws; q=dns; s=default; d=mail.beliefnet.com;
 b=RvVmJOpSKiPqhWQl7saVvXjcbR7D4c9cUR6T0wQs7AlVzuobcxddkQ0GiFKIYdQNQHUOsh5bBZ/C
   0IuUBJPPxg==;
Received: by mail1101.mail.beliefnet.com (PowerMTA(TM) v3.5r13) id hinej00sgh8s for <beliefnet@cp.monitor1.returnpath.net>; Fri, 1 Apr 2011 10:11:27 -0400 (envelope-from <out-582632-B2C71BD37AF148CE9D728B61264F854D@mail.beliefnet.com>)
From: Announce - Beliefnet Sponsor <specialoffers@mail.beliefnet.com>
Reply-To: Announce - Beliefnet Sponsor <r-ethtsdsrhbqfybrtqfjswzrjlyzvkrtpwcqlzspjhrshtkpbtl@mail.beliefnet.com>
To:  <beliefnet@cp.monitor1.returnpath.net>
Message-ID: <527817310.344.1301667087687.JavaMail.root@mail.beliefnet.com>
Subject: [SP] Grant Funding May Be Available for Top Online Colleges. Get
 Free Info Today.
MIME-Version: 1.0
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
X-ID: slvvmprjvrkvtbrbtbjvbckljmk wrhsbwfvszdbclhgpfsrlwkbrkcdlmcftcrjrbkmptvmbcp bvpjksbvbp
X-RPTags: Seed
X-NLCID: 35149
Date: Fri,  1 Apr 2011 08:12:00 -0600 (MDT)

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.=
w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Diso-8859-=
1">
<meta http-equiv=3D"Content-Type" content=3D"text/x-aol; charset=3Diso-8859=
-1">
<title>...</title>
</head>
<body bgcolor=3D"#ffffff">
<div align=3D"center" style=3D"font-size:8pt; font-family:arial,helvetica,s=
ans-serif; color:#666666;">
=09<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"598">
=09=09=09<tr>
=09=09=09=09<td width=3D"139" bgcolor=3D"#dce8f7" align=3D"left"><img src=
=3D"http://bnimg1.beliefnet.com/ads/beliefnet/beliefnetlogo-1.gif" alt=3D"B=
eliefnet" width=3D"139" height=3D"31" border=3D"0"></td>
=09=09=09=09<td  width=3D"459" bgcolor=3D"#dce8f7" align=3D"center" valign=
=3D"bottom" style=3D"background-image:url(http://bnimg1.beliefnet.com/ads/b=
eliefnet/head-1.gif);background-repeat:repeat-x;"><font size=3D"2" color=3D=
"#012d54" style=3D"font-size:9px;line-height:12px;font-family:arial,helveti=
ca,sans-serif;">A&nbsp;&nbsp;&nbsp;&nbsp;S p o n s o r e d&nbsp;&nbsp;&nbsp=
;&nbsp;M e s s a g e&nbsp;&nbsp;&nbsp;&nbsp;f r o m&nbsp;&nbsp;&nbsp;&nbsp;=
B e l i e f n e t</font></td>
=09=09=09</tr>
=09=09=09<tr>
=09=09=09=09<td width=3D"139" bgcolor=3D"#e1efff" align=3D"left"><img src=
=3D"http://www.beliefnet.com/media/spacer.gif" alt=3D"" width=3D"139" heigh=
t=3D"21" border=3D"0"></td>
=09=09=09=09<td width=3D"459" bgcolor=3D"#e1efff" align=3D"center" valign=
=3D"top" style=3D"background-image:url(http://bnimg1.beliefnet.com/ads/beli=
efnet/head-2.gif);background-repeat:repeat-x;"><font color=3D"#012d54" styl=
e=3D"font-size:8pt; font-family:arial,helvetica,sans-serif;">Unsubscribe in=
structions are at the bottom of this email.</font><br><font size=3D"1" styl=
e=3D"font-size:9px;line-height:12px;">P A I D &nbsp;&nbsp; A D V E R T I S =
E M E N T</font>
=09=09=09=09</td>
=09=09=09</tr>
=09=09=09<tr>
=09=09=09=09<td width=3D"139" style=3D"background-image:url(http://bnimg1.b=
eliefnet.com/ads/beliefnet/shadow-1.gif);background-repeat:repeat-x;"><img =
src=3D"http://bnimg1.beliefnet.com/ads/beliefnet/shadow-1.gif" alt=3D"" wid=
th=3D"139" height=3D"7" border=3D"0"></td>
=09=09=09=09<td width=3D"459" style=3D"background-image:url(http://bnimg1.b=
eliefnet.com/ads/beliefnet/shadow-2.gif);background-repeat:repeat-x;"><img =
src=3D"http://bnimg1.beliefnet.com/ads/beliefnet/shadow-2.gif" alt=3D"" wid=
th=3D"459" height=3D"7" border=3D"0"></td>
=09=09=09</tr>
=09=09</table>

<br>
</div>
<div align=3D"center" style=3D"padding:10px;">
<a href=3D"http://click1.mail.beliefnet.com/rktyrbtcyfnpthqcpkwbsplftrpwyvc=
rvkqwgkfttgwcv_qgmvwnwmfgd.html"><img src=3D"http://bnimg1.beliefnet.com/cl=
t/pc/anncmdia/201104/1/topdegrees_sc.jpg" width=3D"700" height=3D"600" bord=
er=3D"0" /></a>
<p align=3D"center"><font face=3D"Arial, Helvetica, sans-serif" size=3D"2" =
style=3D"font-size:12px;"><a href=3D"http://click1.mail.beliefnet.com/cgqvd=
zjtvrpfjkntfgqzsfmrjdfqvltdlgnqcgrjjcqtj_qgmvwnwmfgd.html"><font color=3D"#=
990000">Unsubscribe</font></a><br /><br />
800 High School Way, #20<br />
Mountain View, CA 94041</font></p>
<img src=3D"http://click1.mail.beliefnet.com/vkgdvzjfdbpnjqtfnkmzcnybjvnmdg=
fvgktmhkbjjhmfh_qgmvwnwmfgd.gif" width=3D"0" height=3D"0">
=09=09</div>
=09=09<table width=3D"565" border=3D"0" cellspacing=3D"0" cellpadding=3D"0"=
 align=3D"center">
=09=09=09<tr>
=09=09=09=09<td valign=3D"top" align=3D"left">
=09=09=09=09=09<hr width=3D"565" size=3D"1">
=09=09=09=09=09<table width=3D"565" border=3D"0" cellspacing=3D"0" cellpadd=
ing=3D"10" bgcolor=3D"#F5F9FC">
=09=09=09=09=09=09<tr>
=09=09=09=09=09=09=09<td valign=3D"top" align=3D"left">
=09=09=09=09=09=09=09=09<font face=3D"verdana,arial,sans-serif" size=3D"1" =
color=3D"#666666">
=09=09=09=09=09=09=09=09To view this email as a web page <a href=3D"http://=
click1.mail.beliefnet.com/ViewMessage.do?a=3Dview&m=3Dbglfgpjz&r=3Dqgmvwnwm=
fgd&s=3Dylkyltbsyrqbpzsfctwvrblcygslgfzckfr">follow this link</a>.
=09=09=09=09=09=09=09=09<br><br>
=09=09=09=09=09=09=09=09This email was requested by: &#123;beliefnet@cp.mon=
itor1.returnpath.net&#125;<br><br>
=09=09=09=09=09=09=09=09<strong>Unsubscribe from advertisements, but keep y=
our newsletters:</strong> <a href=3D"http://www.beliefnet.com/newsletter/un=
subscriberequest.aspx?recipientid=3D42021659&externalid=3D31a21254104102c47=
31bc338dc3e7628&listid=3D147&tracking=3Dunsub" target=3D"_blank"><font colo=
r=3D"#0000FF">unsubscribe me</font></a><br><br>
=09=09=09=09=09=09=09=09<strong>Manage your Beliefnet subscriptions includi=
ng newsletters and advertisements:</strong> <a href=3D"http://www.beliefnet=
.com/Newsletter/Manage.aspx?tracking=3Dunsub" target=3D"_blank"><font color=
=3D"#0000FF">unsubscribe me</font></a><br><br>
=09=09=09=09=09=09=09=09<strong>Unsubscribe by mail:</strong> Beliefnet, P.=
O. Box 3882, Norfolk, VA 23514-3882<br><br>
=09=09=09=09=09=09=09=09<strong>Change your email address:</strong>
=09=09=09=09=09=09=09=09<a href=3D"http://www.beliefnet.com/user/nl_updemai=
l.asp" target=3D"_blank">
=09=09=09=09=09=09=09=09<font color=3D"#0000FF">http://www.beliefnet.com/us=
er/nl_updemail.asp</font></a><br><br>
=09=09=09=09=09=09=09=09<strong>Privacy statement:</strong>
=09=09=09=09=09=09=09=09<a href=3D"http://www.beliefnet.com/about/privacy.a=
sp"><font color=3D"#0000FF">http://www.beliefnet.com/about/privacy.asp</fon=
t></a> </font>
=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09</tr>
=09=09=09=09=09</table>
=09=09=09=09</td>
=09=09=09</tr>
=09=09</table>
=09
=09</body>
</html>
