Return-Path: <customer.service@citicorp.com>
X-Original-To: citibanksingaporelimited@cp.monitor1.returnpath.net
Delivered-To: assurance@localhost.returnpath.net
Received: from mxa-d1.returnpath.net (unknown [10.8.2.117])
	by cpa-d1.returnpath.net (Postfix) with ESMTP id 84C61198272
	for <citibanksingaporelimited@cp.monitor1.returnpath.net>; Thu, 31 Mar 2011 20:57:26 -0600 (MDT)
Received: from mail109.messagelabs.com (mail109.messagelabs.com [216.82.250.67])
	by mxa-d1.returnpath.net (Postfix) with ESMTP id B2DF4226
	for <citibanksingaporelimited@cp.monitor1.returnpath.net>; Thu, 31 Mar 2011 20:57:25 -0600 (MDT)
X-VirusChecked: Checked
X-Env-Sender: customer.service@citicorp.com
X-Msg-Ref: server-5.tower-109.messagelabs.com!1301626644!14681666!1
X-StarScan-Version: 6.2.9; banners=-,-,-
X-Originating-IP: [199.67.137.142]
Received: (qmail 10805 invoked from network); 1 Apr 2011 02:57:25 -0000
Received: from unknown (HELO mail.citigroup.com) (199.67.137.142)
  by server-5.tower-109.messagelabs.com with AES256-SHA encrypted SMTP; 1 Apr 2011 02:57:25 -0000
Received: from imbhub-gt06.nam.nsroot.net (imbhub-gt06.nam.nsroot.net [169.171.119.176])
	by smtpinbound.citigroup.com (Switch-3.4.1/Switch-3.4.1) with ESMTP id p312vOvf005088
	for <citibanksingaporelimited@cp.monitor1.returnpath.net>; Fri, 1 Apr 2011 02:57:24 GMT
Received: from imbhub-mw13.nam.nsroot.net (imbhub-mw13.nam.nsroot.net [165.203.230.125])
	by imbhub-gt06.nam.nsroot.net (Switch-3.4.1/Switch-3.4.1) with ESMTP id p312vNMe013343
	for <citibanksingaporelimited@cp.monitor1.returnpath.net>; Fri, 1 Apr 2011 02:57:24 GMT
Received: from saixp36 (saixp36.aspac.citicorp.com [169.175.190.36])
	by imbhub-mw13.nam.nsroot.net (Switch-3.4.1/Switch-3.4.1) with ESMTP id p312vLp4026903
	for <citibanksingaporelimited@cp.monitor1.returnpath.net>; Fri, 1 Apr 2011 02:57:22 GMT
Date: Fri, 1 Apr 2011 02:57:21 GMT
Message-ID: <1479419471.1301626641534.JavaMail.pjfpbg1@saixp36>
From: customer.service@citicorp.com
To: citibanksingaporelimited@cp.monitor1.returnpath.net
Subject: Citi Alerts
Mime-Version: 1.0
Content-Type: multipart/alternative; 
	boundary="----=_Part_26607_1527703119.1301626641533"
urn:schemas:mailheader:content-type: multipart/mixed

------=_Part_26607_1527703119.1301626641533
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: binary

Dear Customer,

We would like to update you on your account balance:

Date: 31/03/11
Account no.: XXXXXX8007  
Account balance: USD 0.00 

Thank you for using Citi Alerts.

Citibank Online
Citibank Singapore Limited
Co. Reg. No. 200309485K

Please do not reply to this email. To view or amend your Citi Alerts Profile, simply log into www.citibank.com.sg with your card number and ATM/Credit Card PIN. Alternatively, you may call our 24-Hour CitiPhone Banking at 6225 5225 for assistance or any other enquiries.
------=_Part_26607_1527703119.1301626641533--

