Return-Path: <news@email1-corel.com>
X-Original-To: corel@cp.monitor1.returnpath.net
Delivered-To: assurance@localhost.returnpath.net
Received: from mxa-d1.returnpath.net (unknown [10.8.2.117])
	by cpa-d1.returnpath.net (Postfix) with ESMTP id D355F19825C
	for <corel@cp.monitor1.returnpath.net>; Fri,  1 Apr 2011 06:52:55 -0600 (MDT)
Received: from outbound4.email1-corel.com (outbound4.email1-corel.com [97.107.23.84])
	by mxa-d1.returnpath.net (Postfix) with ESMTP id 7E1B3A5E
	for <corel@cp.monitor1.returnpath.net>; Fri,  1 Apr 2011 06:52:55 -0600 (MDT)
DKIM-Signature: v=1; a=rsa-sha1; d=email1-corel.com; s=yesmail1; c=relaxed/simple;
	q=dns/txt; i=@email1-corel.com; t=1301662375;
	h=From:Subject:Date:To:MIME-Version:Content-Type;
	bh=vNfDMZXTVpBy4afccNCwiyJcV4M=;
	b=NdmKKvrQLeX1kxhycBp721v/flZhFvjrLoAZZ0LgRnJMNivfKn9CYlQz4F4dVTP3
	IjBwsYvH/frbObiqJJOZFD8n/PMDZjnorC5UZAwDi/BGkXgSwbnDez0IQcOyLieq;
DomainKey-Signature: q=dns; a=rsa-sha1; c=nofws;
	s=yesmail1; d=email1-corel.com;
	h=Date:From:Subject:To:Message-ID:X-Vitals:List-Unsubscribe:X-Header-Versions:Reply-To:X-Header-CompanyDBUserName:X-Header-MasterId:MIME-Version:Content-Type;
	b=fePAfeTxhn94yeLLB+iiJfQcy0NrZPqswqQgjArmX0PK17V+ynfajn9c78S133pt
	vmYvBhFs+WSYY+uVg0/egtdjabDcvNMAhF5XRKBSInVI8hPa+TDAkHTCXBsd7NO+
Date: Fri, 01 Apr 2011 05:52:55 PDT
From: Corel <news@email1-corel.com>
Subject: PREVIEW:   Save $170 and get special gift with CorelDraw Premium Suite X5
To: corel@cp.monitor1.returnpath.net
Message-ID: <Corel.6k3yh-636g-.fv4t@email1-corel.com>
X-Vitals: 1.115503.1.1326598.11.63c7
List-Unsubscribe: <mailto:corel6k3yh-636g-.6fv4t@email1-corel.com?subject=unsubscribe>
X-Header-Versions: Corel.6k3yh-636g-.fv4t@email1-corel.com
Reply-To: Corel.6k3yh-636g-.fv4t@email1-corel.com
X-Header-CompanyDBUserName: corel
X-Header-MasterId: 1326598
MIME-Version: 1.0
Content-Type: text/html; charset=us-ascii


<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
    <head>
        <title></title>
    </head>
    <body bgcolor="#cfcfcf" background="http://images.postdirect.com/master/11/1326598/siteBackground.jpg" spellcheck="false">
        <img src="http://links.email1-corel.com/1x1.dyn?0A48MWlh4MFBRpJU1kg2=0" width=1 height=1  width="1" height="1" border="0">          
        <div align="center"><a name="top"></a> 	  	   <table width="600" cellpadding="0" cellspacing="1" border="0" align="center">
<tr>
<td align="center">
<font face="Verdana, Arial, Helvetica, sans-serif" size="1" color="#666666">
<a href="http://links.email1-corel.com/t.d?O4GnCNWw3_yonv=/@HTML_2PREVIEW_2LINK_0a=ninRp-v-RNKmrQtaiXz"><font color="#666666">View this email as a webpage</font></a> if you don't see any images being displayed.<br>Reminder&#58; add news@email1-corel.com to your Known Senders/Contact list.<br></font></td>
</tr>
</table>    <!-- banner -->
        <div align="center">
        <table width="565" cellspacing="0" cellpadding="0" border="0">
            <tbody>
                <tr>
                    <td><img height="59" width="4" border="0" src="http://images.postdirect.com/master/11/1326598/topLeft.gif" alt="" style="display: block;" /></td>
                    <td><img height="59" width="557" border="0" src="http://images.postdirect.com/master/11/1326598/header.jpg" alt="" style="display: block;" /></td>
                    <td><img height="59" width="4" border="0" src="http://images.postdirect.com/master/11/1326598/topRight.gif" alt="" style="display: block;" /></td>
                </tr>
            </tbody>
        </table>
        </div>
        <!-- /banner -->     <!-- content -->
        <div align="center">
        <table width="565" cellspacing="0" cellpadding="0" border="0">
            <tbody>
                <tr>
                    <td colspan="3"><a href="http://links.email1-corel.com/u.d?UYGnCNWw3_yonv8MWlh=1&s=1326598&ym_2rid="><img height="234" width="565" border="0" src="http://images.postdirect.com/master/11/1326598/main_banner_learn_more.jpg" alt="" style="display: block;" /></a></td>
                </tr>
                <tr>
                    <td rowspan="4"><a href="http://links.email1-corel.com/u.d?W4GnCNWw3_yonv8MWlk=11&s=1326598&ym_2rid="><img height="262" width="383" border="0" src="http://images.postdirect.com/master/11/1326598/btm_lft.jpg" alt="" style="display: block;" /></a></td>
                    <td><a href="http://links.email1-corel.com/u.d?YYGnCNWw3_yonv8MWlr=21&s=1326598&ym_2rid="><img height="96" width="182" border="0" src="http://images.postdirect.com/master/11/1326598/btm_rt_prce.jpg" alt="" style="display: block;" /></a></td>
                </tr>
                <tr>
                    <td><a href="http://links.email1-corel.com/u.d?f4GnCNWw3_yonv8MWlu=31&s=1326598&ym_2rid="><img height="48" width="182" border="0" src="http://images.postdirect.com/master/11/1326598/by_now_usd.jpg" alt="" style="display: block;" /></a></td>
                </tr>
                <tr>
                    <td><a href="http://links.email1-corel.com/u.d?HYGnCNWw3_yonv8MWlxs=41&s=1326598&ym_2rid="><img height="48" width="182" border="0" src="http://images.postdirect.com/master/11/1326598/by_now_cad.jpg" alt="" style="display: block;" /></a></td>
                </tr>
                <tr>
                    <td><a href="http://links.email1-corel.com/u.d?NYGnCNWw3_yonv8MWlxh=51&s=1326598&ym_2rid="><img height="70" width="182" border="0" src="http://images.postdirect.com/master/11/1326598/btm_rt_phone.jpg" alt="" style="display: block;" /></a></td>
                </tr>
            </tbody>
        </table>
        </div>
        <!-- /content -->      <!-- footer -->
        <div align="center">
        <table width="565" cellspacing="0" cellpadding="0" border="0">
            <tbody>
                <tr>
                    <td><img height="28" width="565" border="0" src="http://images.postdirect.com/master/11/1326598/footer.gif" alt="" style="display: block;" /></td>
                </tr>
            </tbody>
        </table>
        </div>
        <!-- /footer -->      <br />
        <table width="600" cellpadding="3" cellspacing="0" border="0" align="center">
<tbody>
<tr>
	<td valign="top">
	<font face="Arial, Verdana, Helvetica, sans-serif" size="1" color="#666666">
	Copyright&copy; 2010 Corel Corporation. All Rights Reserved.
	<br>
	<br>
	You are receiving this email because you requested to receive information regarding Corel products and special offers or you subscribe to a Corel e-newsletter. If you wish to unsubscribe from this email or otherwise change your Corel email communications settings, please <a href="http://pages.email1-corel.com/unsubscribe.jsp?s=YfoY&i=1461760628900"> <font face="Arial, Verdana, Helvetica, sans-serif" size="1" color="#666666">click here</font></a>.
	<br>
	<br>
	At Corel, we respect your privacy. For more information, please view our <a href="http://links.email1-corel.com/u.d?D4GnCNWw3_yonvns=3"><font face="Arial, Verdana, Helvetica, sans-serif" size="1" color="#666666">Privacy Policy</font></a>, or contact us at: Customer Service, Corel Corporation, 1600 Carling Avenue, Ottawa, Ontario, Canada, K1Z 8R7, Attention: Privacy.
	</font>
  	</td>
</tr>
</tbody>
</table></div>
    </body>
</html>

