Return-Path: <suncoast@boydgaming.net>
X-Original-To: boydgamingcorporation@cp.assurance.returnpath.net
Delivered-To: assurance@localhost.returnpath.net
Received: from mxa-d1.returnpath.net (unknown [10.8.2.117])
	by cpa-d1.returnpath.net (Postfix) with ESMTP id 0937F198271
	for <boydgamingcorporation@cp.assurance.returnpath.net>; Fri,  1 Apr 2011 11:36:27 -0600 (MDT)
Received: from smtp2.boydgaming.net (smtp2.boydgaming.net [64.79.129.191])
	by mxa-d1.returnpath.net (Postfix) with ESMTP id C120D126
	for <boydgamingcorporation@cp.assurance.returnpath.net>; Fri,  1 Apr 2011 11:36:26 -0600 (MDT)
Received: from [10.251.20.13] (unknown [10.251.20.13])
	by smtp2.boydgaming.net (Postfix) with ESMTP id 3093227844F
	for <boydgamingcorporation@cp.assurance.returnpath.net>; Fri,  1 Apr 2011 10:36:26 -0700 (PDT)
X-DKIM: Sendmail DKIM Filter v2.8.3 smtp2.boydgaming.net 3093227844F
DKIM-Signature: v=1; a=rsa-sha1; c=simple/simple; d=boydgaming.net; s=smtp;
	t=1301679386; bh=DyM8CohSbjCN3K1AByz8K3FHMsA=;
	h=To:From:Reply-To:Subject:Date:MIME-Version:Content-Type:
	 Content-Transfer-Encoding:List-Unsubscribe:Message-ID;
	b=XtHwSYl7M0uQt3U8XI/0f18VYVe/ta7nARZB1GN4TWbczqD8jIOf7cLIp93IX/Q27
	 flggpcloqkcxlrCmJ4qWYstPrVGhpHfCdVJdTQMf9CmnTjjWfqsJ1mPL6QLOdcKxRB
	 XmkjNNLtheRsBRLE1/e6wGHNutpri6zNCZzx7xgA=
To: Lisa Marshall <boydgamingcorporation@cp.assurance.returnpath.net>
From: Suncoast Hotel & Casino - Las Vegas <suncoast@boydgaming.net>
Reply-To: Suncoast Hotel & Casino - Las Vegas <suncoast@boydgaming.net>
Subject: See What's Happening with our Table Games!
Date: Fri, 01 Apr 2011 10:36:26 -0700
X-LibVersion: 3.3.2
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="_=_swift-13596511954d960d1a312b33.37345773_=_"
Content-Transfer-Encoding: 7bit
X-Ninja-Mailer-ID: 6752
List-Unsubscribe: <http://www.boydgaming.com/unsubscribe?6752XXLUX0X0XTEST>
Message-ID: <20110401173626.15575.2089030531.swift@webadmin.boydgaming.net>

This is a message in multipart MIME format.  Your mail client should not
be displaying this. Consider upgrading your mail client to view this
message correctly.
--_=_swift-13596511954d960d1a312b33.37345773_=_
Content-Type: text/plain; charset=iso-8859-1
Content-Transfer-Encoding: 8bit

View Full Version:
https://webadmin.boydgaming.net/m.php?6752XXTX0X0XTEST
- Suncoast Hotel & Casino - Las Vegas -


 See What's Happening with our Table Games!


Click for More Information:
https://webadmin.boydgaming.net/ml.php?6752X17XTX0X0XTEST

----------------------------------------
Must be 21 years old to participate. Management reserves all rights.
----------------------------------------

Suncoast Hotel & Casino - Las Vegas
9090 Alta Drive
Las Vegas, NV 89145 702-636-7111


Visit Official Website:
https://webadmin.boydgaming.net/ml.php?6752X1XTX0X0XTEST

----------------------------------------

To ensure future delivery of E-mail from Suncoast Hotel & Casino - Las Vegas please add suncoast@boydgaming.net to your safe sender list or address book.


To unsubscribe from future E-mail communications, click the link below:
Unsubscribe:
http://www.boydgaming.com/unsubscribe?6752XXTX0X0XTEST


Copyright &copy; 2011 Boyd Gaming. All rights reserved. 

Privacy Policy:
https://webadmin.boydgaming.net/ml.php?6752X3XTX0X0XTEST
&nbsp;|&nbsp;
Responsible Gaming:
https://webadmin.boydgaming.net/ml.php?6752X4XTX0X0XTEST


Don't let the game get out of hand. For Assistance call 800-522-4700.
--_=_swift-13596511954d960d1a312b33.37345773_=_
Content-Type: text/html; charset=iso-8859-1
Content-Transfer-Encoding: 8bit

<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head>

<body bgcolor="#000000" link="#FFFFFF" vlink="#FFFFFF" alink="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0"><img 
src="http://static.boydgaming.net/mailers/media/spacer.gif" alt="View Mobile / Text Version - Click Here: https://webadmin.boydgaming.net/m.php?6752XXMX0X0XTEST" 
height="1" width="1" border="0">



<table width="100%" height="90%" align="center" bgcolor="#000000"><tr><td>


  
<!------------------TOP MESSAGE---------------------->  
<center><table border="0"  width="600" align="center" cellpadding="0" cellspacing="0"><tr><td><a href="https://webadmin.boydgaming.net/ml.php?6752X17XHX0X0XTEST" target="_blank"><font face="Arial, Helvetica, sans-serif" size="1" color="#FFFFFF">See What's Happening with our Table Games!</font></a></td><td align="right"><a href="https://webadmin.boydgaming.net/m.php?6752XXHX0X0XTEST" target="_blank"><font face="Arial, Helvetica, sans-serif" size="1" color="#FFFFFF"> View with Images</font></a><font face="Arial, Helvetica, sans-serif" size="1" color="#FFFFFF"> <strong>|</strong> </font><a href="https://webadmin.boydgaming.net/m.php?6752XXMX0X0XTEST" target="_blank"><font face="Arial, Helvetica, sans-serif" color="#FFFFFF" size="1">View Mobile/Text Version</font></a><br></td></tr><tr><td colspan="2" align="right"><font face="Arial, Helvetica, sans-serif" size="1" color="#FFFFFF">This E-mail is intended for: <strong>Lisa Marshall</strong> <strong>|</strong> Player Card Number:
<strong>99void999</strong></font></td></tr></table>


</center>
<!------------------END TOP MESSAGE---------------------->  



<!------------------CONTENT---------------------->
<center>
<br><img 
src="http://static.boydgaming.net/mailers/media/suncoast_header_.jpg" usemap="#header_new" border="0"><br><img 
src="http://static.boydgaming.net/mailers/6752/poker_01.jpg" border="0"><br><a href="https://webadmin.boydgaming.net/ml.php?6752X17XHX0X0XTEST" target="_blank"><img 
src="http://static.boydgaming.net/mailers/6752/poker_02.jpg" border="0"></a><br><img 
src="http://static.boydgaming.net/mailers/6752/poker_03.jpg" border="0"><br><img 
src="http://static.boydgaming.net/mailers/media/suncoast_footer_.jpg" usemap="#footer_bco_new" border="0">
</center>
<!------------------END CONTENT---------------------->



<!------------------BANNER AD---------------------->

<center><br><a href="https://webadmin.boydgaming.net/ml.php?6752X18XHX0X0XTEST" target="_blank"><img src="http://static.boydgaming.net/mailers/media/bcm_banner.jpg" border="0"></a><br><br>
</center>

<!------------------END BANNER AD---------------------->



<!-----------------DISCLAIMER-------------------->
<br><table width="600" border="0" align="center" cellpadding="0" cellspacing="0"><tr><td align="justify"><font face="Arial, Helvetica, sans-serif" size="1" color="#FFFFFF">
<center><strong>Must be 21 years old to participate. Management reserves all rights.</strong></center></font></td></tr></table>
<!-----------------END DISCLAIMER-------------------->

<br>

<!-----------------OPT-IN/UNSUBSCRIBE-------------------->
<table align="center" width="600"><tr><td align="center"><font face="Arial, Helvetica, sans-serif" size="1" color="#FFFFFF">
You have been sent this E-mail because you opted-in to receive promotions and offers from Suncoast Hotel & Casino - Las Vegas. To ensure future delivery, please add </font><a href="mailto:suncoast@boydgaming.net"><font face="Arial, Helvetica, sans-serif" size="1" color="#FFFFFF">suncoast@boydgaming.net</font></a><font face="Arial, Helvetica, sans-serif" size="1" color="#FFFFFF"> to your safe sender list or address book.</font><br><br><font face="Arial, Helvetica, sans-serif" size="1" color="#FFFFFF">To unsubscribe from future E-mail communications,</font><a href="http://www.boydgaming.com/unsubscribe?6752XXHX0X0XTEST" target="_blank"><font face="Arial, Helvetica, sans-serif" size="1" color="#FFFFFF">click here.</font></a>
<!-----------------OPT-IN/UNSUBSCRIBE-------------------->



<!-----------------FORWARD TO A FRIEND-------------------->
<!--N/A-->
<!-----------------END FORWARD TO A FRIEND-------------------->



<!-----------------SOCIAL MEDIA-------------------->
<br>
<br>
<img src="http://static.boydgaming.net/mailers/media/socialmedia_icons_000000.jpg" border="0" usemap="#social2">
<br>
<!-----------------END SOCIAL MEDIA-------------------->


<!-----------------PROPERTY INFO-------------------->
<font size="2" face="Arial, Helvetica, sans-serif" color="#FFFFFF"><strong>Suncoast Hotel & Casino - Las Vegas</strong><br>
9090 Alta Drive, Las Vegas NV 89145<br>702-636-7111</font><br><br>
<!-----------------END PROPERTY INFO-------------------->



<!-----------------COPYRIGHT-------------------->
<font size="1" face="Arial, Helvetica, sans-serif" color="#FFFFFF">Copyright &copy; 2011 Boyd Gaming. All rights reserved. </font>
<a href="https://webadmin.boydgaming.net/ml.php?6752X3XHX0X0XTEST" target="_blank"><font face="Arial, Helvetica, sans-serif" size="1" color="#FFFFFF">Privacy Policy</font></a><font face="Arial, Helvetica, sans-serif" size="1" color="#FFFFFF">&nbsp;|&nbsp;</font>
<a href="https://webadmin.boydgaming.net/ml.php?6752X4XHX0X0XTEST" target="_blank"><font face="Arial, Helvetica, sans-serif" size="1" color="#FFFFFF">Responsible Gaming</font></a><br>
<!-----------------END COPYRIGHT-------------------->



<!-----------------RESPONSIBLE GAMING-------------------->
<font size="1" face="Arial, Helvetica, sans-serif" color="#FFFFFF">Don't let the game get out of hand. For Assistance call 800-522-4700.</font><br><br><br>
<!-----------------END RESPONSIBLE GAMING-------------------->



<a href="https://webadmin.boydgaming.net/ml.php?6752X2XHX0X0XTEST" target="_blank"><img src="http://static.boydgaming.net/mailers/media/boydfooter_000000.gif" width="592" height="25" border="0"></a><br><br>

</td></tr></table>

</td></tr></table>

<!----------------------NEW-------------------------->
<map name="header_new">
  <area shape="rect" coords="11,10,146,71" href="https://webadmin.boydgaming.net/ml.php?6752X1XHX0X0XTEST" target="_blank" alt="Visit Website">
  <area shape="rect" coords="151,19,226,45" href="https://webadmin.boydgaming.net/ml.php?6752X5XHX0X0XTEST" target="_blank" alt="Reservations">
  <area shape="rect" coords="226,19,307,45" href="https://webadmin.boydgaming.net/ml.php?6752X12XHX0X0XTEST" target="_blank" alt="Entertainment">
  <area shape="rect" coords="307,19,379,45" href="https://webadmin.boydgaming.net/ml.php?6752X13XHX0X0XTEST" target="_blank" alt="What's New">
  <area shape="rect" coords="379,19,494,45" href="https://webadmin.boydgaming.net/ml.php?6752X7XHX0X0XTEST" target="_blank" alt="B Connected Online">
  <area shape="rect" coords="494,19,597,45" href="https://webadmin.boydgaming.net/ml.php?6752X14XHX0X0XTEST" target="_blank" alt="Destinations">
</map>
<map name="footer_bco_new">
  <area shape="rect" coords="4,13,232,63" href="https://webadmin.boydgaming.net/ml.php?6752X7XHX0X0XTEST" target="_blank" alt="B Connected Online">
  <area shape="rect" coords="371,43,589,65" href="https://webadmin.boydgaming.net/ml.php?6752X2XHX0X0XTEST" target="_blank" alt="Boyd Gaming">
</map>
<map name="social">
  <area shape="rect" coords="4,5,34,27" href="https://webadmin.boydgaming.net/ml.php?6752X7XHX0X0XTEST" target="_blank" alt="B Connected Online">
  <area shape="rect" coords="48,5,74,27" href="https://webadmin.boydgaming.net/ml.php?6752X8XHX0X0XTEST" target="_blank" alt="Facebook">
  <area shape="rect" coords="90,5,115,27" href="https://webadmin.boydgaming.net/ml.php?6752X9XHX0X0XTEST" target="_blank" alt="Twitter">
  <area shape="rect" coords="131,5,157,27" href="https://webadmin.boydgaming.net/ml.php?6752X10XHX0X0XTEST" target="_blank" alt="You Tube">
</map>

<map name="social2">
  <area shape="rect" coords="166,17,258,38" href="https://webadmin.boydgaming.net/ml.php?6752X7XHX0X0XTEST" target="_blank" alt="B Connected Online">
  <area shape="rect" coords="296,17,357,38" href="https://webadmin.boydgaming.net/ml.php?6752X8XHX0X0XTEST" target="_blank" alt="Facebook">
  <area shape="rect" coords="399,17,461,38" href="https://webadmin.boydgaming.net/ml.php?6752X9XHX0X0XTEST" target="_blank" alt="Twitter">
  <area shape="rect" coords="499,17,561,38" href="https://webadmin.boydgaming.net/ml.php?6752X10XHX0X0XTEST" target="_blank" alt="You Tube">
</map>
<img src="http://pixel.monitor1.returnpath.net/pixel.gif?r=d6677f8a9ed9c2844f53de3d751cad8d0d25129b">
<img src="https://webadmin.boydgaming.net/ninjaphp/modules/massmailers/mailbug.php?6752XXHX0X0XTEST">
</body>
</html>
--_=_swift-13596511954d960d1a312b33.37345773_=_--

