Return-Path: <A107_223993796_-1@carmamail.com>
X-Original-To: compostmarketingab@cp.monitor1.returnpath.net
Delivered-To: assurance@localhost.returnpath.net
Received: from mxa-d1.returnpath.net (unknown [10.8.2.117])
	by cpa-d1.returnpath.net (Postfix) with ESMTP id 314F019825C
	for <compostmarketingab@cp.monitor1.returnpath.net>; Fri,  1 Apr 2011 05:02:20 -0600 (MDT)
Received: from secos-m101-i51.carmamail.com (secos-m101-i51.carmamail.com [81.201.223.51])
	by mxa-d1.returnpath.net (Postfix) with ESMTP id 6F5AFCC2
	for <compostmarketingab@cp.monitor1.returnpath.net>; Fri,  1 Apr 2011 05:02:16 -0600 (MDT)
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; s=k4; d=carmamail.com;
 h=Message-ID:From:Reply-To:To:Subject:MIME-Version:Content-Type:Date; i=dkim@carmamail.com;
 bh=YYkvtrz3M6P0mBTLTl585OiqCbg=;
 b=KyP+A1oweu86VGdCTfsjD8asQxR3bOoHKENO+ESjD6Hw2aBfrFabOBhUHVpNhtPnTcGwtSI8+BCw
   MMsO8Xkh4A==
Received: by secos-m101-i51.carmamail.com (PowerMTA(TM) v3.5r13) id himobg10u8op for <compostmarketingab@cp.monitor1.returnpath.net>; Fri, 1 Apr 2011 13:02:13 +0200 (envelope-from <A107_223993796_-1@carmamail.com>)
Message-ID: <58795828.1301655732499.JavaMail.compostadmin@secos-a107>
From: {CARMA TEST} Test <from@test.carmamail.com>
Reply-To: Test <test@compost.se>
To: compostmarketingab@cp.monitor1.returnpath.net
Subject: ComHem Senaste Nyheterna
MIME-Version: 1.0
Content-Type: multipart/alternative; 
	boundary="----=_Part_329666_58751540.1301655732499"
Precedence: list
X-Mailer: Compost Carma
X-Carma-Version: 4.5.0
X-Carma-MessageID: 223993796
X-campaignid: carma203208
X-serverid: A107
x-vmta: 55_noauth
Date: Fri, 1 Apr 2011 13:02:13 +0200

------=_Part_329666_58751540.1301655732499
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable


* Ser brevet konstigt ut? kkkKlicka h=E4r: http://www.carmamail.com/mail/OB=
S?muid=3D13azAb223993796

-----



-----


---=20
* comhem.se
* Digital-tv: http://www.comhem.se/comhem/vara-tjanster/digitaltv/-/5620/56=
20/-/index.html
* Bredband: http://www.comhem.se/comhem/vara-tjanster/bredband/-/5622/5622/=
-/index.html
* Telefoni: http://www.comhem.se/comhem/vara-tjanster/telefoni/-/5624/5624/=
-/index.html
* Kundservice: http://www.comhem.se/comhem/kundservice/-/3550/3550/-/index.=
html
* Erbjudanden: http://www.comhem.se/comhem/vara-tjanster/combo/-/5626/5626/=
-/index.html
---
=09

-----



-----


* Caption Wide Article
* Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel lacus a =
eros faucibus accumsan. Morbi facilisis gravida est lacinia placerat. Etiam=
 vel nibh ac tellus facilisis ultricies eu nec purus. In mattis libero eget=
 lorem interdum ac dictum neque commodo. Ut nunc magna, vehicula ac pellent=
esque facilisis, facilisis sit amet dui. Ut ipsum lorem, consectetur quis c=
onsectetur vitae, molestie ut ipsum. Sed mollis sollicitudin laoreet.
* Lorem ipsum: http://www.comhem.se

-----


-----

* Caption Wide Article
* Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel lacus a =
eros faucibus accumsan. Morbi facilisis gravida est lacinia placerat. Etiam=
 vel nibh ac tellus facilisis ultricies eu nec purus. In mattis libero eget=
 lorem interdum ac dictum neque commodo.
* Lorem ipsum: http://www.comhem.se

-----


-----

* Caption Narrow Article
* Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel lacus a =
eros faucibus accumsan. Morbi facilisis gravida.
* Lorem ipsum: http://www.comhem.se

-----



-----



-----


* Com Hem p=E5 Twitter
* Lorem ipsum dolor sit amet, consectetur adipiscing elit.
* Link w/ Arrow: http://www.comhem.se

-----



-----


* Kundservice tipsar
* Lorem ipsum dolor sit amet, consectetur adipiscing elit.
* Link w/ Arrow: http://www.comhem.se

-----



-----


* Com Hem tipsar
* Lorem ipsum dolor sit amet, consectetur adipiscing elit.
* Link w/ Arrow: http://www.comhem.se

-----



-----


* M=E5nadens fr=E5ga
* Lorem ipsum dolor sit amet, consectetur adipiscing elit.
* Link w/ Arrow: http://www.comhem.se

-----



-----


* Downloads

-----


-----

* Title Row 1
=09=09=09=09=09=09=09=09=09=09Title Row 2
* Spel / Genre
* 000:-
* L=E4s mer: http://downloads.comhem.se/games/
* K=F6p: http://downloads.comhem.se/games/

-----


-----

* Title Row 1
=09=09=09=09=09=09=09=09=09=09Title Row 2
* Ljudbok / Genre
* 000:-
* L=E4s mer: http://downloads.comhem.se/audiobooks/
* K=F6p: http://downloads.comhem.se/audiobooks/

-----


-----

* Title Row 1
=09=09=09=09=09=09=09=09=09=09Title Row 2
* Utbildning / Genre
* 000:-
* L=E4s mer: http://downloads.comhem.se/education/
* K=F6p: http://downloads.comhem.se/education/

-----



-----


-----

* Title Row 1
=09=09=09=09=09=09=09=09=09=09Title Row 2
* Spel / Genre
* 000:-
* L=E4s mer: http://downloads.comhem.se/games/
* K=F6p: http://downloads.comhem.se/games/

-----


-----

* Title Row 1
=09=09=09=09=09=09=09=09=09=09Title Row 2
* Ljudbok / Genre
* 000:-
* L=E4s mer: http://downloads.comhem.se/audiobooks/
* K=F6p: http://downloads.comhem.se/audiobooks/

-----


-----

* Title Row 1
=09=09=09=09=09=09=09=09=09=09Title Row 2
* Utbildning / Genre
* 000:-
* L=E4s mer: http://downloads.comhem.se/education/
* K=F6p: http://downloads.comhem.se/education/

-----



-----


-----

* P=E5 tv i veckan

-----


-----

* Title
=09=09=09=09=09=09=09=09=09=09
=09=09=09=09=09=09=09=09=09=09Day hh:mm
=09=09=09=09=09=09=09=09=09=09
* Channel

-----


-----

* Title
=09=09=09=09=09=09=09=09=09=09
=09=09=09=09=09=09=09=09=09=09Day hh:mm
=09=09=09=09=09=09=09=09=09=09
* Channel

-----


-----

* Title
=09=09=09=09=09=09=09=09=09=09
=09=09=09=09=09=09=09=09=09=09Day hh:mm
=09=09=09=09=09=09=09=09=09=09
* Channel

-----



-----



-----


* Avsluta prenumeration: http://www.carmamail.com/Forms/Default.aspx?form=
=3D145_6367318c&amp;muid=3D13azAb223993796

-----


------=_Part_329666_58751540.1301655732499
Content-Type: text/html;charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable


<html xmlns:msxsl=3D"urn:schemas-microsoft-com:xslt" xmlns:xsd=3D"http://ww=
w.w3.org/2001/XMLSchema" xmlns:xsi=3D"http://www.w3.org/2001/XMLSchema-inst=
ance" xmlns:dc=3D"http://purl.org/dc/elements/1.1/" xmlns:ms=3D"urn:schemas=
-microsoft-com:xslt"><head><META http-equiv=3D"Content-Type" content=3D"tex=
t/html; charset=3Diso-8859-1"><meta name=3D"generator" content=3D"Carma Ema=
il Application - www.compost.se"><title>Newsletter</title><link rel=3D"styl=
esheet" type=3D"text/css" href=3D"http://www.carmamail.com/styles/supertemp=
late.css"></head><body leftmargin=3D"0" topmargin=3D"0" marginwidth=3D"0" m=
arginheight=3D"0" bgcolor=3D"#f2f2f2">
<img border=3D"0" width=3D"1" height=3D"1" src=3D"http://www.carmamail.com/=
mail/MOS?uid=3D14000059&mid=3D223993796" /><br />
<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr>=
<td bgcolor=3D"#f2f2f2"><table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0" align=3D"center" width=3D"600"><tr><td>

<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr>=
<td width=3D"100%"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" =
width=3D"100%"><tr><td valign=3D"top" width=3D"100%"><table cellpadding=3D"=
0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http:/=
/www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"25" border=3D"0" a=
lt=3D""></td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cellpadd=
ing=3D"0" cellspacing=3D"0" border=3D"0"><tr><td align=3D"left"><font face=
=3D"Arial, sans-serif" size=3D"2" color=3D"#999999" style=3D"font-weight: n=
ormal;font-style: normal;text-decoration: none;font-size: 11px;">Ser brevet=
 konstigt ut? kkk</font><font size=3D"2" style=3D"font-size: 11px;"><a targ=
et=3D"_blank" href=3D"http://www.carmamail.com/mail/OBS?muid=3D13azAb223993=
796" style=3D"text-decoration: underline;"><font face=3D"Arial, sans-serif"=
 color=3D"#999999" style=3D"font-weight: normal;font-style: normal;text-dec=
oration: underline;">Klicka h&auml;r</font></a></font></td></tr></table></t=
d></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" widt=
h=3D"100%"><tr><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" wid=
th=3D"1" height=3D"10" border=3D"0" alt=3D""></td></tr></table></td></tr></=
table></td></tr></table>

<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr>=
<td width=3D"100%"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" =
width=3D"100%"><tr><td valign=3D"top"><table cellpadding=3D"0" cellspacing=
=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left"><t=
able cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"1"><tr><td><=
a><img src=3D"http://www.carmamail.com/comhem/img2/logo-600x73.jpg" alt=3D"=
" border=3D"0" width=3D"600" height=3D"73"></a></td></tr></table></td></tr>=
</table></td><td valign=3D"top" width=3D"100%"></td></tr></table></td></tr>=
</table>

</td></tr><tr><td><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" w=
idth=3D"100%"><tr><td><table cellpadding=3D"0" cellspacing=3D"0" border=3D"=
0" width=3D"100%"><tr><td align=3D"left" valign=3D"top" bgcolor=3D"#e5e5e5"=
><img src=3D"http://www.carmamail.com/images/pixel.gif" width=3D"1" height=
=3D"1" alt=3D"" border=3D"0"></td><td bgcolor=3D"#e5e5e5"><img src=3D"http:=
//www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"1" border=3D"0" a=
lt=3D""></td><td align=3D"right" valign=3D"top" bgcolor=3D"#e5e5e5"><img sr=
c=3D"http://www.carmamail.com/images/pixel.gif" width=3D"1" height=3D"1" al=
t=3D"" border=3D"0"></td></tr><tr><td bgcolor=3D"#e5e5e5"><img src=3D"http:=
//www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"1" border=3D"0" a=
lt=3D""></td><td width=3D"100%" bgcolor=3D"#ffffff">

<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr>=
<td width=3D"100%"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" =
width=3D"100%"><tr><td valign=3D"top" width=3D"100%"><table cellpadding=3D"=
0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http:/=
/www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"10" border=3D"0" a=
lt=3D""></td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0" width=3D"100%"><tr><td><img src=3D"http://www.carmamail.com/img/pixe=
l2.gif" width=3D"15" height=3D"1" border=3D"0" alt=3D""></td><td width=3D"1=
00%"><table border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"100%"=
 align=3D"left"><tr><td valign=3D"top" align=3D"left" width=3D"125"><table =
cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td wid=
th=3D"100%" align=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" borde=
r=3D"0"><tr><td align=3D"left"><font face=3D"Helvetica, sans-serif" size=3D=
"2" color=3D"#000000" style=3D"font-weight: bold;font-style: normal;text-de=
coration: none;font-size: 11px;">comhem.se</font></td></tr></table></td></t=
r></table></td><td valign=3D"top" align=3D"left" width=3D"125"><table cellp=
adding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=
=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"15" height=3D"1" bord=
er=3D"0" alt=3D""></td><td width=3D"100%" align=3D"left"><table cellpadding=
=3D"0" cellspacing=3D"0" border=3D"0"><tr><td><img src=3D"http://www.carmam=
ail.com/comhem/img2/bullet-blue-6x11.gif" alt=3D"" border=3D"0" width=3D"6"=
 height=3D"11"></td><td><img src=3D"http://www.carmamail.com/img/pixel2.gif=
" width=3D"5" height=3D"1"></td><td align=3D"left"><font size=3D"2" style=
=3D"font-size: 11px;"><a target=3D"_blank" style=3D"text-decoration: none;"=
 href=3D"http://www.carmamail.com/mail/RLS?mid=3D223993796&guid=3D13azAb&li=
d=3D695231" clinkID=3D"695231"><font face=3D"Arial, sans-serif" color=3D"#0=
068a2" style=3D"font-weight: bold;font-style: normal;text-decoration: none;=
">Digital-tv</font></a></font></td></tr></table></td></tr></table></td><td =
valign=3D"top" align=3D"left" width=3D"125"><table cellpadding=3D"0" cellsp=
acing=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://www.carm=
amail.com/img/pixel2.gif" width=3D"15" height=3D"1" border=3D"0" alt=3D""><=
/td><td width=3D"100%" align=3D"left"><table cellpadding=3D"0" cellspacing=
=3D"0" border=3D"0"><tr><td><img src=3D"http://www.carmamail.com/comhem/img=
2/bullet-blue-6x11.gif" alt=3D"" border=3D"0" width=3D"6" height=3D"11"></t=
d><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"5" heig=
ht=3D"1"></td><td align=3D"left"><font size=3D"2" style=3D"font-size: 11px;=
"><a target=3D"_blank" style=3D"text-decoration: none;" href=3D"http://www.=
carmamail.com/mail/RLS?mid=3D223993796&guid=3D13azAb&lid=3D695232" clinkID=
=3D"695232"><font face=3D"Arial, sans-serif" color=3D"#0068a2" style=3D"fon=
t-weight: bold;font-style: normal;text-decoration: none;">Bredband</font></=
a></font></td></tr></table></td></tr></table></td><td valign=3D"top" align=
=3D"left" width=3D"125"><table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0" width=3D"100%"><tr><td><img src=3D"http://www.carmamail.com/img/pixe=
l2.gif" width=3D"15" height=3D"1" border=3D"0" alt=3D""></td><td width=3D"1=
00%" align=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0"=
><tr><td><img src=3D"http://www.carmamail.com/comhem/img2/bullet-blue-6x11.=
gif" alt=3D"" border=3D"0" width=3D"6" height=3D"11"></td><td><img src=3D"h=
ttp://www.carmamail.com/img/pixel2.gif" width=3D"5" height=3D"1"></td><td a=
lign=3D"left"><font size=3D"2" style=3D"font-size: 11px;"><a target=3D"_bla=
nk" style=3D"text-decoration: none;" href=3D"http://www.carmamail.com/mail/=
RLS?mid=3D223993796&guid=3D13azAb&lid=3D695233" clinkID=3D"695233"><font fa=
ce=3D"Arial, sans-serif" color=3D"#0068a2" style=3D"font-weight: bold;font-=
style: normal;text-decoration: none;">Telefoni</font></a></font></td></tr><=
/table></td></tr></table></td><td valign=3D"top" align=3D"left" width=3D"12=
5"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><=
tr><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"15" he=
ight=3D"1" border=3D"0" alt=3D""></td><td width=3D"100%" align=3D"left"><ta=
ble cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr><td><img src=3D"ht=
tp://www.carmamail.com/comhem/img2/bullet-blue-6x11.gif" alt=3D"" border=3D=
"0" width=3D"6" height=3D"11"></td><td><img src=3D"http://www.carmamail.com=
/img/pixel2.gif" width=3D"5" height=3D"1"></td><td align=3D"left"><font siz=
e=3D"2" style=3D"font-size: 11px;"><a target=3D"_blank" style=3D"text-decor=
ation: none;" href=3D"http://www.carmamail.com/mail/RLS?mid=3D223993796&gui=
d=3D13azAb&lid=3D695234" clinkID=3D"695234"><font face=3D"Arial, sans-serif=
" color=3D"#0068a2" style=3D"font-weight: bold;font-style: normal;text-deco=
ration: none;">Kundservice</font></a></font></td></tr></table></td></tr></t=
able></td><td valign=3D"top" align=3D"left"><table cellpadding=3D"0" cellsp=
acing=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://www.carm=
amail.com/img/pixel2.gif" width=3D"15" height=3D"1" border=3D"0" alt=3D""><=
/td><td width=3D"100%" align=3D"left"><table cellpadding=3D"0" cellspacing=
=3D"0" border=3D"0"><tr><td><img src=3D"http://www.carmamail.com/comhem/img=
2/bullet-blue-6x11.gif" alt=3D"" border=3D"0" width=3D"6" height=3D"11"></t=
d><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"5" heig=
ht=3D"1"></td><td align=3D"left"><font size=3D"2" style=3D"font-size: 11px;=
"><a target=3D"_blank" style=3D"text-decoration: none;" href=3D"http://www.=
carmamail.com/mail/RLS?mid=3D223993796&guid=3D13azAb&lid=3D695235" clinkID=
=3D"695235"><font face=3D"Arial, sans-serif" color=3D"#0068a2" style=3D"fon=
t-weight: bold;font-style: normal;text-decoration: none;">Erbjudanden</font=
></a></font></td></tr></table></td></tr></table></td></tr></table></td><td>=
<img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"15" height=3D=
"1" border=3D"0" alt=3D""></td></tr></table><table cellpadding=3D"0" cellsp=
acing=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://www.carm=
amail.com/img/pixel2.gif" width=3D"1" height=3D"10" border=3D"0" alt=3D""><=
/td></tr></table></td></tr></table></td></tr></table>

<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr>=
<td width=3D"100%"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" =
width=3D"100%"><tr><td valign=3D"top" width=3D"100%"><table cellpadding=3D"=
0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%" ali=
gn=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=
=3D"1"><tr><td><a><img src=3D"http://www.carmamail.com/comhem/img2/big-imag=
e-598x200.gif" alt=3D"" border=3D"0" width=3D"598" height=3D"200"></a></td>=
</tr></table></td></tr></table></td></tr></table></td></tr></table>

<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr>=
<td><img src=3D"http://www.carmamail.com/images/pixel.gif" width=3D"1" heig=
ht=3D"1" alt=3D"" border=3D"0"></td><td><img src=3D"http://www.carmamail.co=
m/img/pixel2.gif" width=3D"1" height=3D"15" border=3D"0" alt=3D""></td><td>=
<img src=3D"http://www.carmamail.com/images/pixel.gif" width=3D"1" height=
=3D"1" alt=3D"" border=3D"0"></td></tr><tr><td><img src=3D"http://www.carma=
mail.com/img/pixel2.gif" width=3D"10" height=3D"1" border=3D"0" alt=3D""></=
td><td width=3D"100%"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"=
0" width=3D"100%"><tr><td valign=3D"top" width=3D"100%"><table cellpadding=
=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%"=
 align=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr=
><td align=3D"left"><font face=3D"Arial, sans-serif" size=3D"4" color=3D"#3=
33333" style=3D"font-weight: bold;font-style: normal;text-decoration: none;=
font-size: 24px;">Caption Wide Article</font></td></tr></table></td></tr></=
table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%=
"><tr><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"1" =
height=3D"8" border=3D"0" alt=3D""></td></tr></table><table cellpadding=3D"=
0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%" ali=
gn=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr><td=
 align=3D"left"><font face=3D"Arial, sans-serif" size=3D"2" color=3D"#33333=
3" style=3D"font-weight: normal;font-style: normal;text-decoration: none;fo=
nt-size: 11px;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Se=
d vel lacus a eros faucibus accumsan. Morbi facilisis gravida est lacinia p=
lacerat. Etiam vel nibh ac tellus facilisis ultricies eu nec purus. In matt=
is libero eget lorem interdum ac dictum neque commodo. Ut nunc magna, vehic=
ula ac pellentesque facilisis, facilisis sit amet dui. Ut ipsum lorem, cons=
ectetur quis consectetur vitae, molestie ut ipsum. Sed mollis sollicitudin =
laoreet.</font></td></tr></table></td></tr></table><table cellpadding=3D"0"=
 cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://w=
ww.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"8" border=3D"0" alt=
=3D""></td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cellpadd=
ing=3D"0" cellspacing=3D"0" border=3D"0"><tr><td><img src=3D"http://www.car=
mamail.com/comhem/img2/bullet-blue-6x11.gif" alt=3D"" border=3D"0" width=3D=
"6" height=3D"11"></td><td><img src=3D"http://www.carmamail.com/img/pixel2.=
gif" width=3D"5" height=3D"1"></td><td align=3D"left"><font size=3D"2" styl=
e=3D"font-size: 11px;"><a target=3D"_blank" style=3D"text-decoration: none;=
" href=3D"http://www.carmamail.com/mail/RLS?mid=3D223993796&guid=3D13azAb&l=
id=3D695236" clinkID=3D"695236"><font face=3D"Arial, sans-serif" color=3D"#=
0068a2" style=3D"font-weight: bold;font-style: normal;text-decoration: none=
;">Lorem ipsum</font></a></font></td></tr></table></td></tr></table><table =
cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td><im=
g src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"15"=
 border=3D"0" alt=3D""></td></tr></table></td></tr></table></td><td><img sr=
c=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"20" height=3D"1" bor=
der=3D"0" alt=3D""></td></tr></table><table cellpadding=3D"0" cellspacing=
=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"10"><img src=3D"http://=
www.carmamail.com/img/pixel2.gif" width=3D"10" height=3D"1" border=3D"0" al=
t=3D""></td><td bgcolor=3D"#ebebeb" height=3D"1"><img src=3D"http://www.car=
mamail.com/img/pixel2.gif" width=3D"1" height=3D"1"></td><td width=3D"10"><=
img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"10" height=3D"=
1" border=3D"0" alt=3D""></td></tr><tr><td><img src=3D"http://www.carmamail=
.com/images/pixel.gif" width=3D"1" height=3D"1" alt=3D"" border=3D"0"></td>=
<td height=3D"15"><img src=3D"http://www.carmamail.com/img/pixel2.gif" widt=
h=3D"1" height=3D"15" border=3D"0" alt=3D""></td><td><img src=3D"http://www=
.carmamail.com/images/pixel.gif" width=3D"1" height=3D"1" alt=3D"" border=
=3D"0"></td></tr></table>

<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr>=
<td width=3D"100%"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" =
width=3D"100%"><tr><td valign=3D"top" width=3D"100%"><table cellpadding=3D"=
0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td valign=3D"top"><ta=
ble cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td=
><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"10" height=
=3D"1" border=3D"0" alt=3D""></td><td width=3D"100%"><table cellpadding=3D"=
0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td valign=3D"top" wid=
th=3D"100%"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=
=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cellpadding=3D"0" ce=
llspacing=3D"0" border=3D"0" width=3D"1"><tr><td><a><img src=3D"http://www.=
carmamail.com/comhem/img2/wide-image-l-375x126.gif" alt=3D"" border=3D"0" w=
idth=3D"375" height=3D"126"></a></td></tr></table></td></tr></table><table =
cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td><im=
g src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"10"=
 border=3D"0" alt=3D""></td></tr></table><table cellpadding=3D"0" cellspaci=
ng=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left">=
<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr><td align=3D"le=
ft"><font face=3D"Arial, sans-serif" size=3D"3" color=3D"#333333" style=3D"=
font-weight: bold;font-style: normal;text-decoration: none;font-size: 14px;=
">Caption Wide Article</font></td></tr></table></td></tr></table><table cel=
lpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td><img s=
rc=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"8" bor=
der=3D"0" alt=3D""></td></tr></table><table cellpadding=3D"0" cellspacing=
=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left"><t=
able cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr><td align=3D"left=
"><font face=3D"Arial, sans-serif" size=3D"2" color=3D"#333333" style=3D"fo=
nt-weight: normal;font-style: normal;text-decoration: none;font-size: 11px;=
">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel lacus a =
eros faucibus accumsan. Morbi facilisis gravida est lacinia placerat. Etiam=
 vel nibh ac tellus facilisis ultricies eu nec purus. In mattis libero eget=
 lorem interdum ac dictum neque commodo.</font></td></tr></table></td><td><=
img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"10" height=3D"=
1" border=3D"0" alt=3D""></td></tr></table><table cellpadding=3D"0" cellspa=
cing=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://www.carma=
mail.com/img/pixel2.gif" width=3D"1" height=3D"8" border=3D"0" alt=3D""></t=
d></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" widt=
h=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cellpadding=3D"0" c=
ellspacing=3D"0" border=3D"0"><tr><td><img src=3D"http://www.carmamail.com/=
comhem/img2/bullet-blue-6x11.gif" alt=3D"" border=3D"0" width=3D"6" height=
=3D"11"></td><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=
=3D"5" height=3D"1"></td><td align=3D"left"><font size=3D"2" style=3D"font-=
size: 11px;"><a target=3D"_blank" style=3D"text-decoration: none;" href=3D"=
http://www.carmamail.com/mail/RLS?mid=3D223993796&guid=3D13azAb&lid=3D69523=
7" clinkID=3D"695237"><font face=3D"Arial, sans-serif" color=3D"#0068a2" st=
yle=3D"font-weight: bold;font-style: normal;text-decoration: none;">Lorem i=
psum</font></a></font></td></tr></table></td></tr></table><table cellpaddin=
g=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"h=
ttp://www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"15" border=3D=
"0" alt=3D""></td></tr></table></td></tr></table></td><td><img src=3D"http:=
//www.carmamail.com/img/pixel2.gif" width=3D"10" height=3D"1" border=3D"0" =
alt=3D""></td></tr></table></td><td valign=3D"top"><table cellpadding=3D"0"=
 cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://w=
ww.carmamail.com/img/pixel2.gif" width=3D"10" height=3D"1" border=3D"0" alt=
=3D""></td><td width=3D"100%"><table cellpadding=3D"0" cellspacing=3D"0" bo=
rder=3D"0" width=3D"100%"><tr><td valign=3D"top" width=3D"100%"><table cell=
padding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td width=
=3D"100%" align=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0" width=3D"1"><tr><td><a><img src=3D"http://www.carmamail.com/comhem/i=
mg2/small-image-l-181x126.gif" alt=3D"" border=3D"0" width=3D"181" height=
=3D"126"></a></td></tr></table></td></tr></table><table cellpadding=3D"0" c=
ellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://www=
.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"10" border=3D"0" alt=
=3D""></td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cellpadd=
ing=3D"0" cellspacing=3D"0" border=3D"0"><tr><td align=3D"left"><font face=
=3D"Arial, sans-serif" size=3D"3" color=3D"#333333" style=3D"font-weight: b=
old;font-style: normal;text-decoration: none;font-size: 14px;">Caption Narr=
ow Article</font></td></tr></table></td></tr></table><table cellpadding=3D"=
0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http:/=
/www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"8" border=3D"0" al=
t=3D""></td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cellpadd=
ing=3D"0" cellspacing=3D"0" border=3D"0"><tr><td align=3D"left"><font face=
=3D"Arial, sans-serif" size=3D"2" color=3D"#333333" style=3D"font-weight: n=
ormal;font-style: normal;text-decoration: none;font-size: 11px;">Lorem ipsu=
m dolor sit amet, consectetur adipiscing elit. Sed vel lacus a eros faucibu=
s accumsan. Morbi facilisis gravida.</font></td></tr></table></td><td><img =
src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"10" height=3D"1" b=
order=3D"0" alt=3D""></td></tr></table><table cellpadding=3D"0" cellspacing=
=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://www.carmamail=
.com/img/pixel2.gif" width=3D"1" height=3D"8" border=3D"0" alt=3D""></td></=
tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D=
"100%"><tr><td width=3D"100%" align=3D"left"><table cellpadding=3D"0" cells=
pacing=3D"0" border=3D"0"><tr><td><img src=3D"http://www.carmamail.com/comh=
em/img2/bullet-blue-6x11.gif" alt=3D"" border=3D"0" width=3D"6" height=3D"1=
1"></td><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"5=
" height=3D"1"></td><td align=3D"left"><font size=3D"2" style=3D"font-size:=
 11px;"><a target=3D"_blank" style=3D"text-decoration: none;" href=3D"http:=
//www.carmamail.com/mail/RLS?mid=3D223993796&guid=3D13azAb&lid=3D695238" cl=
inkID=3D"695238"><font face=3D"Arial, sans-serif" color=3D"#0068a2" style=
=3D"font-weight: bold;font-style: normal;text-decoration: none;">Lorem ipsu=
m</font></a></font></td></tr></table></td></tr></table><table cellpadding=
=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"ht=
tp://www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"15" border=3D"=
0" alt=3D""></td></tr></table></td></tr></table></td><td><img src=3D"http:/=
/www.carmamail.com/img/pixel2.gif" width=3D"10" height=3D"1" border=3D"0" a=
lt=3D""></td></tr></table></td></tr></table></td></tr></table></td></tr></t=
able>

</td><td bgcolor=3D"#e5e5e5"><img src=3D"http://www.carmamail.com/img/pixel=
2.gif" width=3D"1" height=3D"1" border=3D"0" alt=3D""></td></tr></table></t=
d></tr><tr><td><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" bord=
ercolor=3D"red" width=3D"100%"><tr><td bgcolor=3D"#e5e5e5" width=3D"1"><img=
 src=3D"http://www.carmamail.com/images/pixel.gif" width=3D"1" height=3D"1"=
 alt=3D"" border=3D"0"></td><td valign=3D"top" width=3D"100%" bgcolor=3D"#f=
fffff">

<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr>=
<td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"10" heigh=
t=3D"1" border=3D"0" alt=3D""></td><td width=3D"100%"><table cellpadding=3D=
"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td valign=3D"top"><t=
able cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><t=
d width=3D"100%" align=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" =
border=3D"0" width=3D"1"><tr><td><a href=3D"http://www.carmamail.com/mail/R=
LS?mid=3D223993796&guid=3D13azAb&lid=3D695239" clinkID=3D"695239"><img src=
=3D"http://static.addtoany.com/buttons/share_save_171_16.png" alt=3D"" bord=
er=3D"0" width=3D"171" height=3D"16"></a></td></tr></table></td><td><img sr=
c=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"10" height=3D"1" bor=
der=3D"0" alt=3D""></td></tr></table><table cellpadding=3D"0" cellspacing=
=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://www.carmamail=
.com/img/pixel2.gif" width=3D"1" height=3D"10" border=3D"0" alt=3D""></td><=
/tr></table></td><td valign=3D"top"><table cellpadding=3D"0" cellspacing=3D=
"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left"><tabl=
e cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"1"><tr><td><a h=
ref=3D"http://www.carmamail.com/mail/RLS?mid=3D223993796&guid=3D13azAb&lid=
=3D695240" clinkID=3D"695240"><img src=3D"http://s7.addthis.com/static/btn/=
v2/lg-share-en.gif" alt=3D"" border=3D"0" width=3D"125" height=3D"16"></a><=
/td></tr></table></td><td><img src=3D"http://www.carmamail.com/img/pixel2.g=
if" width=3D"10" height=3D"1" border=3D"0" alt=3D""></td></tr></table><tabl=
e cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td><=
img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"1=
0" border=3D"0" alt=3D""></td></tr></table></td><td valign=3D"top"><table c=
ellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td widt=
h=3D"100%" align=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0" width=3D"1"><tr><td><a href=3D"http://www.carmamail.com/mail/RLS?mid=
=3D223993796&guid=3D13azAb&lid=3D695241" clinkID=3D"695241"><img src=3D"htt=
p://s7.addthis.com/static/btn/sm-share-en.gif" alt=3D"" border=3D"0" width=
=3D"83" height=3D"16"></a></td></tr></table></td><td><img src=3D"http://www=
.carmamail.com/img/pixel2.gif" width=3D"10" height=3D"1" border=3D"0" alt=
=3D""></td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0" width=3D"100%"><tr><td><img src=3D"http://www.carmamail.com/img/pixe=
l2.gif" width=3D"1" height=3D"10" border=3D"0" alt=3D""></td></tr></table><=
/td><td valign=3D"top" width=3D"100%"></td></tr></table></td><td><img src=
=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"10" height=3D"1" bord=
er=3D"0" alt=3D""></td></tr></table>

</td><td valign=3D"top" bgcolor=3D"#ffffff"><table cellspacing=3D"0" cellpa=
dding=3D"0" border=3D"0" bordercolor=3D"#ff0000" width=3D"1"><tr><td></td><=
td valign=3D"top" width=3D"1"><img src=3D"http://www.carmamail.com/comhem/i=
mg2/profile-box-top-179x13.gif" width=3D"179" height=3D"13"></td><td></td><=
/tr><tr><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"1=
0" height=3D"1"></td><td valign=3D"top" bgcolor=3D"#282828">

<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr>=
<td><img src=3D"http://www.carmamail.com/images/pixel.gif" width=3D"1" heig=
ht=3D"1" alt=3D"" border=3D"0"></td><td><img src=3D"http://www.carmamail.co=
m/img/pixel2.gif" width=3D"1" height=3D"8" border=3D"0" alt=3D""></td><td><=
img src=3D"http://www.carmamail.com/images/pixel.gif" width=3D"1" height=3D=
"1" alt=3D"" border=3D"0"></td></tr><tr><td><img src=3D"http://www.carmamai=
l.com/img/pixel2.gif" width=3D"15" height=3D"1" border=3D"0" alt=3D""></td>=
<td width=3D"100%"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" =
width=3D"100%"><tr><td valign=3D"top" width=3D"100%"><table cellpadding=3D"=
0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%" ali=
gn=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr><td=
 align=3D"left"><font face=3D"Arial, sans-serif" size=3D"3" color=3D"#fffff=
f" style=3D"font-weight: bold;font-style: normal;text-decoration: none;font=
-size: 14px;">!!First_Name_Short!! !!Last_Name_Short!!</font></td></tr></ta=
ble></td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"=
0" width=3D"100%"><tr><td><img src=3D"http://www.carmamail.com/img/pixel2.g=
if" width=3D"1" height=3D"10" border=3D"0" alt=3D""></td></tr></table><tabl=
e cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td w=
idth=3D"100%" align=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" bor=
der=3D"0"><tr><td align=3D"left"><font face=3D"Arial, sans-serif" size=3D"2=
" color=3D"#ffffff" style=3D"font-weight: normal;font-style: normal;text-de=
coration: none;font-size: 11px;">!!Email_Address_Short!!<br>          Faktu=
ratyp: !!TextFakturaStatus!!</font></td></tr></table></td></tr></table><tab=
le cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td>=
<img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"=
10" border=3D"0" alt=3D""></td></tr></table><table cellpadding=3D"0" cellsp=
acing=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"lef=
t"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr><td><img src=
=3D"http://www.carmamail.com/comhem/img2/bullet-white-6x11.gif" alt=3D"" bo=
rder=3D"0" width=3D"6" height=3D"11"></td><td><img src=3D"http://www.carmam=
ail.com/img/pixel2.gif" width=3D"5" height=3D"1"></td><td align=3D"left"><f=
ont size=3D"2" style=3D"font-size: 11px;"><a target=3D"_blank" style=3D"tex=
t-decoration: none;" href=3D"http://www.carmamail.com/mail/RLS?mid=3D223993=
796&guid=3D13azAb&lid=3D695242" clinkID=3D"695242"><font face=3D"Arial, san=
s-serif" color=3D"#ffffff" style=3D"font-weight: bold;font-style: normal;te=
xt-decoration: none;">&Auml;ndra uppgifter</font></a></font></td></tr></tab=
le></td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0=
" width=3D"100%"><tr><td><img src=3D"http://www.carmamail.com/img/pixel2.gi=
f" width=3D"1" height=3D"10" border=3D"0" alt=3D""></td></tr></table><table=
 cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td wi=
dth=3D"100%" align=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" bord=
er=3D"0"><tr><td><img src=3D"http://www.carmamail.com/comhem/img2/bullet-wh=
ite-6x11.gif" alt=3D"" border=3D"0" width=3D"6" height=3D"11"></td><td><img=
 src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"5" height=3D"1"><=
/td><td align=3D"left"><font size=3D"2" style=3D"font-size: 11px;"><a targe=
t=3D"_blank" style=3D"text-decoration: none;" href=3D"http://www.carmamail.=
com/mail/RLS?mid=3D223993796&guid=3D13azAb&lid=3D695243" clinkID=3D"695243"=
><font face=3D"Arial, sans-serif" color=3D"#ffffff" style=3D"font-weight: b=
old;font-style: normal;text-decoration: none;">Logga in p&aring; Mina sidor=
</font></a></font></td></tr></table></td></tr></table><table cellpadding=3D=
"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http:=
//www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"10" border=3D"0" =
alt=3D""></td></tr></table></td></tr></table></td><td><img src=3D"http://ww=
w.carmamail.com/img/pixel2.gif" width=3D"10" height=3D"1" border=3D"0" alt=
=3D""></td></tr></table>

<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr>=
<td><img src=3D"http://www.carmamail.com/images/pixel.gif" width=3D"1" heig=
ht=3D"1" alt=3D"" border=3D"0"></td><td><img src=3D"http://www.carmamail.co=
m/img/pixel2.gif" width=3D"1" height=3D"8" border=3D"0" alt=3D""></td><td><=
img src=3D"http://www.carmamail.com/images/pixel.gif" width=3D"1" height=3D=
"1" alt=3D"" border=3D"0"></td></tr><tr><td><img src=3D"http://www.carmamai=
l.com/img/pixel2.gif" width=3D"15" height=3D"1" border=3D"0" alt=3D""></td>=
<td width=3D"100%"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" =
width=3D"100%"><tr><td valign=3D"top" width=3D"100%"><table cellpadding=3D"=
0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%" ali=
gn=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr><td=
 align=3D"left"><font face=3D"Arial, sans-serif" size=3D"3" color=3D"#fffff=
f" style=3D"font-weight: bold;font-style: normal;text-decoration: none;font=
-size: 12px;">Mina Grundabonnemang</font></td></tr></table></td></tr></tabl=
e><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><t=
r><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"1" heig=
ht=3D"10" border=3D"0" alt=3D""></td></tr></table><table cellpadding=3D"0" =
cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%" align=
=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"=
1"><tr><td><a><img src=3D"http://www.carmamail.com/comhem/img2/separator-da=
rk-small-149x3.gif" alt=3D"" border=3D"0" width=3D"149" height=3D"3"></a></=
td></tr></table></td></tr></table><table cellpadding=3D"0" cellspacing=3D"0=
" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://www.carmamail.com/=
img/pixel2.gif" width=3D"1" height=3D"15" border=3D"0" alt=3D""></td></tr><=
/table></td></tr></table></td><td><img src=3D"http://www.carmamail.com/img/=
pixel2.gif" width=3D"10" height=3D"1" border=3D"0" alt=3D""></td></tr></tab=
le>

</td><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"10" =
height=3D"1"></td></tr><tr><td></td><td valign=3D"top" width=3D"1"><img src=
=3D"http://www.carmamail.com/comhem/img2/profile-box-bottom-179x13.gif" wid=
th=3D"179" height=3D"13"></td><td></td></tr><tr><td></td><td><img src=3D"ht=
tp://www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"15"></td><td><=
/td></tr></table>

<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr>=
<td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"12" heigh=
t=3D"1" border=3D"0" alt=3D""></td><td bgcolor=3D"#e5e5e5"><img src=3D"http=
://www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"1" border=3D"0" =
alt=3D""></td><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" widt=
h=3D"12" height=3D"1" border=3D"0" alt=3D""></td><td width=3D"100%"><table =
cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td val=
ign=3D"top" width=3D"100%"><table cellpadding=3D"0" cellspacing=3D"0" borde=
r=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cellpad=
ding=3D"0" cellspacing=3D"0" border=3D"0"><tr><td align=3D"left"><font face=
=3D"Arial, sans-serif" size=3D"2" color=3D"#000000" style=3D"font-weight: b=
old;font-style: normal;text-decoration: none;font-size: 11px;">Com Hem p&ar=
ing; Twitter</font></td><td><img src=3D"http://www.carmamail.com/img/pixel2=
.gif" width=3D"5" height=3D"1"></td><td><img src=3D"http://www.carmamail.co=
m/comhem/img2/icon-twitter-28x23.gif" alt=3D"" border=3D"0" width=3D"28" he=
ight=3D"23"></td></tr></table></td></tr></table><table cellpadding=3D"0" ce=
llspacing=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://www.=
carmamail.com/img/pixel2.gif" width=3D"1" height=3D"6" border=3D"0" alt=3D"=
"></td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0"=
 width=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cellpadding=3D=
"0" cellspacing=3D"0" border=3D"0"><tr><td align=3D"left"><font face=3D"Ari=
al, sans-serif" size=3D"2" color=3D"#333333" style=3D"font-weight: normal;f=
ont-style: normal;text-decoration: none;font-size: 11px;">Lorem ipsum dolor=
 sit amet, consectetur adipiscing elit.</font></td></tr></table></td></tr><=
/table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100=
%"><tr><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"1"=
 height=3D"8" border=3D"0" alt=3D""></td></tr></table><table cellpadding=3D=
"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%" al=
ign=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr><t=
d><img src=3D"http://www.carmamail.com/comhem/img2/bullet-blue-6x11.gif" al=
t=3D"" border=3D"0" width=3D"6" height=3D"11"></td><td><img src=3D"http://w=
ww.carmamail.com/img/pixel2.gif" width=3D"5" height=3D"1"></td><td align=3D=
"left"><font size=3D"2" style=3D"font-size: 11px;"><a target=3D"_blank" sty=
le=3D"text-decoration: none;" href=3D"http://www.carmamail.com/mail/RLS?mid=
=3D223993796&guid=3D13azAb&lid=3D695244" clinkID=3D"695244"><font face=3D"A=
rial, sans-serif" color=3D"#0068a2" style=3D"font-weight: bold;font-style: =
normal;text-decoration: none;">Link w/ Arrow</font></a></font></td></tr></t=
able></td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=3D=
"0" width=3D"100%"><tr><td><img src=3D"http://www.carmamail.com/img/pixel2.=
gif" width=3D"1" height=3D"10" border=3D"0" alt=3D""></td></tr></table></td=
></tr></table></td><td><img src=3D"http://www.carmamail.com/img/pixel2.gif"=
 width=3D"10" height=3D"1" border=3D"0" alt=3D""></td></tr></table>

<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr>=
<td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"12" heigh=
t=3D"1" border=3D"0" alt=3D""></td><td bgcolor=3D"#e5e5e5"><img src=3D"http=
://www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"1" border=3D"0" =
alt=3D""></td><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" widt=
h=3D"12" height=3D"1" border=3D"0" alt=3D""></td><td width=3D"100%"><table =
cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td val=
ign=3D"top" width=3D"100%"><table cellpadding=3D"0" cellspacing=3D"0" borde=
r=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cellpad=
ding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"1"><tr><td><a><img src=
=3D"http://www.carmamail.com/comhem/img2/separator-white-small-164x3.gif" a=
lt=3D"" border=3D"0" width=3D"164" height=3D"3"></a></td></tr></table></td>=
</tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=
=3D"100%"><tr><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" widt=
h=3D"1" height=3D"15" border=3D"0" alt=3D""></td></tr></table></td></tr></t=
able></td></tr></table>

<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr>=
<td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"12" heigh=
t=3D"1" border=3D"0" alt=3D""></td><td bgcolor=3D"#e5e5e5"><img src=3D"http=
://www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"1" border=3D"0" =
alt=3D""></td><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" widt=
h=3D"12" height=3D"1" border=3D"0" alt=3D""></td><td width=3D"100%"><table =
cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td val=
ign=3D"top" width=3D"100%"><table cellpadding=3D"0" cellspacing=3D"0" borde=
r=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cellpad=
ding=3D"0" cellspacing=3D"0" border=3D"0"><tr><td align=3D"left"><font face=
=3D"Arial, sans-serif" size=3D"2" color=3D"#000000" style=3D"font-weight: b=
old;font-style: normal;text-decoration: none;font-size: 11px;">Kundservice =
tipsar</font></td><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" =
width=3D"5" height=3D"1"></td><td><img src=3D"http://www.carmamail.com/comh=
em/img2/icon-bulb-28x23.gif" alt=3D"" border=3D"0" width=3D"28" height=3D"2=
3"></td></tr></table></td></tr></table><table cellpadding=3D"0" cellspacing=
=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://www.carmamail=
.com/img/pixel2.gif" width=3D"1" height=3D"6" border=3D"0" alt=3D""></td></=
tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D=
"100%"><tr><td width=3D"100%" align=3D"left"><table cellpadding=3D"0" cells=
pacing=3D"0" border=3D"0"><tr><td align=3D"left"><font face=3D"Arial, sans-=
serif" size=3D"2" color=3D"#333333" style=3D"font-weight: normal;font-style=
: normal;text-decoration: none;font-size: 11px;">Lorem ipsum dolor sit amet=
, consectetur adipiscing elit.</font></td></tr></table></td></tr></table><t=
able cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><t=
d><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"1" height=
=3D"8" border=3D"0" alt=3D""></td></tr></table><table cellpadding=3D"0" cel=
lspacing=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"=
left"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr><td><img =
src=3D"http://www.carmamail.com/comhem/img2/bullet-blue-6x11.gif" alt=3D"" =
border=3D"0" width=3D"6" height=3D"11"></td><td><img src=3D"http://www.carm=
amail.com/img/pixel2.gif" width=3D"5" height=3D"1"></td><td align=3D"left">=
<font size=3D"2" style=3D"font-size: 11px;"><a target=3D"_blank" style=3D"t=
ext-decoration: none;" href=3D"http://www.carmamail.com/mail/RLS?mid=3D2239=
93796&guid=3D13azAb&lid=3D695245" clinkID=3D"695245"><font face=3D"Arial, s=
ans-serif" color=3D"#0068a2" style=3D"font-weight: bold;font-style: normal;=
text-decoration: none;">Link w/ Arrow</font></a></font></td></tr></table></=
td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" wid=
th=3D"100%"><tr><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" wi=
dth=3D"1" height=3D"10" border=3D"0" alt=3D""></td></tr></table></td></tr><=
/table></td><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=
=3D"10" height=3D"1" border=3D"0" alt=3D""></td></tr></table>

<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr>=
<td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"12" heigh=
t=3D"1" border=3D"0" alt=3D""></td><td bgcolor=3D"#e5e5e5"><img src=3D"http=
://www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"1" border=3D"0" =
alt=3D""></td><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" widt=
h=3D"12" height=3D"1" border=3D"0" alt=3D""></td><td width=3D"100%"><table =
cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td val=
ign=3D"top" width=3D"100%"><table cellpadding=3D"0" cellspacing=3D"0" borde=
r=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cellpad=
ding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"1"><tr><td><a><img src=
=3D"http://www.carmamail.com/comhem/img2/separator-white-small-164x3.gif" a=
lt=3D"" border=3D"0" width=3D"164" height=3D"3"></a></td></tr></table></td>=
</tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=
=3D"100%"><tr><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" widt=
h=3D"1" height=3D"15" border=3D"0" alt=3D""></td></tr></table></td></tr></t=
able></td></tr></table>

<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr>=
<td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"12" heigh=
t=3D"1" border=3D"0" alt=3D""></td><td bgcolor=3D"#e5e5e5"><img src=3D"http=
://www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"1" border=3D"0" =
alt=3D""></td><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" widt=
h=3D"12" height=3D"1" border=3D"0" alt=3D""></td><td width=3D"100%"><table =
cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td val=
ign=3D"top" width=3D"100%"><table cellpadding=3D"0" cellspacing=3D"0" borde=
r=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cellpad=
ding=3D"0" cellspacing=3D"0" border=3D"0"><tr><td align=3D"left"><font face=
=3D"Arial, sans-serif" size=3D"2" color=3D"#000000" style=3D"font-weight: b=
old;font-style: normal;text-decoration: none;font-size: 11px;">Com Hem tips=
ar</font></td><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" widt=
h=3D"5" height=3D"1"></td><td><img src=3D"http://www.carmamail.com/comhem/i=
mg2/icon-bulb-28x23.gif" alt=3D"" border=3D"0" width=3D"28" height=3D"23"><=
/td></tr></table></td></tr></table><table cellpadding=3D"0" cellspacing=3D"=
0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://www.carmamail.com=
/img/pixel2.gif" width=3D"1" height=3D"6" border=3D"0" alt=3D""></td></tr><=
/table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100=
%"><tr><td width=3D"100%" align=3D"left"><table cellpadding=3D"0" cellspaci=
ng=3D"0" border=3D"0"><tr><td align=3D"left"><font face=3D"Arial, sans-seri=
f" size=3D"2" color=3D"#333333" style=3D"font-weight: normal;font-style: no=
rmal;text-decoration: none;font-size: 11px;">Lorem ipsum dolor sit amet, co=
nsectetur adipiscing elit.</font></td></tr></table></td></tr></table><table=
 cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td><i=
mg src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"8"=
 border=3D"0" alt=3D""></td></tr></table><table cellpadding=3D"0" cellspaci=
ng=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left">=
<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr><td><img src=3D=
"http://www.carmamail.com/comhem/img2/bullet-blue-6x11.gif" alt=3D"" border=
=3D"0" width=3D"6" height=3D"11"></td><td><img src=3D"http://www.carmamail.=
com/img/pixel2.gif" width=3D"5" height=3D"1"></td><td align=3D"left"><font =
size=3D"2" style=3D"font-size: 11px;"><a target=3D"_blank" style=3D"text-de=
coration: none;" href=3D"http://www.carmamail.com/mail/RLS?mid=3D223993796&=
guid=3D13azAb&lid=3D695246" clinkID=3D"695246"><font face=3D"Arial, sans-se=
rif" color=3D"#0068a2" style=3D"font-weight: bold;font-style: normal;text-d=
ecoration: none;">Link w/ Arrow</font></a></font></td></tr></table></td></t=
r></table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"=
100%"><tr><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D=
"1" height=3D"10" border=3D"0" alt=3D""></td></tr></table></td></tr></table=
></td><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"10"=
 height=3D"1" border=3D"0" alt=3D""></td></tr></table>

<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr>=
<td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"12" heigh=
t=3D"1" border=3D"0" alt=3D""></td><td bgcolor=3D"#e5e5e5"><img src=3D"http=
://www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"1" border=3D"0" =
alt=3D""></td><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" widt=
h=3D"12" height=3D"1" border=3D"0" alt=3D""></td><td width=3D"100%"><table =
cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td val=
ign=3D"top" width=3D"100%"><table cellpadding=3D"0" cellspacing=3D"0" borde=
r=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cellpad=
ding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"1"><tr><td><a><img src=
=3D"http://www.carmamail.com/comhem/img2/separator-white-small-164x3.gif" a=
lt=3D"" border=3D"0" width=3D"164" height=3D"3"></a></td></tr></table></td>=
</tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=
=3D"100%"><tr><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" widt=
h=3D"1" height=3D"15" border=3D"0" alt=3D""></td></tr></table></td></tr></t=
able></td></tr></table>

<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr>=
<td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"12" heigh=
t=3D"1" border=3D"0" alt=3D""></td><td bgcolor=3D"#e5e5e5"><img src=3D"http=
://www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"1" border=3D"0" =
alt=3D""></td><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" widt=
h=3D"12" height=3D"1" border=3D"0" alt=3D""></td><td width=3D"100%"><table =
cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td val=
ign=3D"top" width=3D"100%"><table cellpadding=3D"0" cellspacing=3D"0" borde=
r=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cellpad=
ding=3D"0" cellspacing=3D"0" border=3D"0"><tr><td align=3D"left"><font face=
=3D"Arial, sans-serif" size=3D"2" color=3D"#000000" style=3D"font-weight: b=
old;font-style: normal;text-decoration: none;font-size: 11px;">M&aring;nade=
ns fr&aring;ga</font></td><td><img src=3D"http://www.carmamail.com/img/pixe=
l2.gif" width=3D"5" height=3D"1"></td><td><img src=3D"http://www.carmamail.=
com/comhem/img2/icon-question-28x23.gif" alt=3D"" border=3D"0" width=3D"28"=
 height=3D"23"></td></tr></table></td></tr></table><table cellpadding=3D"0"=
 cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://w=
ww.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"6" border=3D"0" alt=
=3D""></td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cellpadd=
ing=3D"0" cellspacing=3D"0" border=3D"0"><tr><td align=3D"left"><font face=
=3D"Arial, sans-serif" size=3D"2" color=3D"#333333" style=3D"font-weight: n=
ormal;font-style: normal;text-decoration: none;font-size: 11px;">Lorem ipsu=
m dolor sit amet, consectetur adipiscing elit.</font></td></tr></table></td=
></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=
=3D"100%"><tr><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" widt=
h=3D"1" height=3D"8" border=3D"0" alt=3D""></td></tr></table><table cellpad=
ding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"1=
00%" align=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0"=
><tr><td><img src=3D"http://www.carmamail.com/comhem/img2/bullet-blue-6x11.=
gif" alt=3D"" border=3D"0" width=3D"6" height=3D"11"></td><td><img src=3D"h=
ttp://www.carmamail.com/img/pixel2.gif" width=3D"5" height=3D"1"></td><td a=
lign=3D"left"><font size=3D"2" style=3D"font-size: 11px;"><a target=3D"_bla=
nk" style=3D"text-decoration: none;" href=3D"http://www.carmamail.com/mail/=
RLS?mid=3D223993796&guid=3D13azAb&lid=3D695247" clinkID=3D"695247"><font fa=
ce=3D"Arial, sans-serif" color=3D"#0068a2" style=3D"font-weight: bold;font-=
style: normal;text-decoration: none;">Link w/ Arrow</font></a></font></td><=
/tr></table></td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" bo=
rder=3D"0" width=3D"100%"><tr><td><img src=3D"http://www.carmamail.com/img/=
pixel2.gif" width=3D"1" height=3D"10" border=3D"0" alt=3D""></td></tr></tab=
le></td></tr></table></td><td><img src=3D"http://www.carmamail.com/img/pixe=
l2.gif" width=3D"10" height=3D"1" border=3D"0" alt=3D""></td></tr></table>

</td><td width=3D"1" bgcolor=3D"#e5e5e5"><img src=3D"http://www.carmamail.c=
om/images/pixel.gif" width=3D"1" height=3D"1" alt=3D"" border=3D"0"></td></=
tr></table></td></tr><tr><td><table cellpadding=3D"0" cellspacing=3D"0" bor=
der=3D"0" width=3D"100%"><tr><td bgcolor=3D"#e5e5e5"><img src=3D"http://www=
.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"1" border=3D"0" alt=3D=
""></td><td width=3D"100%" bgcolor=3D"#ffffff">

<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr>=
<td><img src=3D"http://www.carmamail.com/images/pixel.gif" width=3D"1" heig=
ht=3D"1" alt=3D"" border=3D"0"></td><td height=3D"10"><img src=3D"http://ww=
w.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"10" border=3D"0" alt=
=3D""></td><td><img src=3D"http://www.carmamail.com/images/pixel.gif" width=
=3D"1" height=3D"1" alt=3D"" border=3D"0"></td></tr><tr><td width=3D"10"><i=
mg src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"10" height=3D"1=
" border=3D"0" alt=3D""></td><td bgcolor=3D"#ebebeb" height=3D"1"><img src=
=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"1"></td>=
<td width=3D"10"><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=
=3D"10" height=3D"1" border=3D"0" alt=3D""></td></tr><tr><td><img src=3D"ht=
tp://www.carmamail.com/images/pixel.gif" width=3D"1" height=3D"1" alt=3D"" =
border=3D"0"></td><td height=3D"15"><img src=3D"http://www.carmamail.com/im=
g/pixel2.gif" width=3D"1" height=3D"15" border=3D"0" alt=3D""></td><td><img=
 src=3D"http://www.carmamail.com/images/pixel.gif" width=3D"1" height=3D"1"=
 alt=3D"" border=3D"0"></td></tr></table><table cellpadding=3D"0" cellspaci=
ng=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%"><table cellpadd=
ing=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td valign=3D"t=
op" width=3D"100%"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" =
width=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cellpadding=3D"=
0" cellspacing=3D"0" border=3D"0" width=3D"1"><tr><td><a><img src=3D"http:/=
/www.carmamail.com/comhem/img2/big-image-598x200.gif" alt=3D"" border=3D"0"=
 width=3D"598" height=3D"200"></a></td></tr></table></td></tr></table></td>=
</tr></table></td></tr></table>

<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr>=
<td><img src=3D"http://www.carmamail.com/images/pixel.gif" width=3D"1" heig=
ht=3D"1" alt=3D"" border=3D"0"></td><td height=3D"10"><img src=3D"http://ww=
w.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"10" border=3D"0" alt=
=3D""></td><td><img src=3D"http://www.carmamail.com/images/pixel.gif" width=
=3D"1" height=3D"1" alt=3D"" border=3D"0"></td></tr><tr><td width=3D"10"><i=
mg src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"10" height=3D"1=
" border=3D"0" alt=3D""></td><td bgcolor=3D"#ebebeb" height=3D"1"><img src=
=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"1"></td>=
<td width=3D"10"><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=
=3D"10" height=3D"1" border=3D"0" alt=3D""></td></tr><tr><td><img src=3D"ht=
tp://www.carmamail.com/images/pixel.gif" width=3D"1" height=3D"1" alt=3D"" =
border=3D"0"></td><td height=3D"15"><img src=3D"http://www.carmamail.com/im=
g/pixel2.gif" width=3D"1" height=3D"15" border=3D"0" alt=3D""></td><td><img=
 src=3D"http://www.carmamail.com/images/pixel.gif" width=3D"1" height=3D"1"=
 alt=3D"" border=3D"0"></td></tr></table><table cellpadding=3D"0" cellspaci=
ng=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://www.carmama=
il.com/img/pixel2.gif" width=3D"10" height=3D"1" border=3D"0" alt=3D""></td=
><td width=3D"100%"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0"=
 width=3D"100%"><tr><td valign=3D"top" width=3D"100%"><table cellpadding=3D=
"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%" al=
ign=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr><t=
d align=3D"left"><font face=3D"Arial, sans-serif" size=3D"2" color=3D"#0000=
00" style=3D"font-weight: bold;font-style: normal;text-decoration: none;fon=
t-size: 14px;">Downloads</font></td><td><img src=3D"http://www.carmamail.co=
m/img/pixel2.gif" width=3D"5" height=3D"1"></td><td><img src=3D"http://www.=
carmamail.com/comhem/img2/icon-download-30x17.gif" alt=3D"" border=3D"0" wi=
dth=3D"30" height=3D"17"></td></tr></table></td></tr></table></td></tr></ta=
ble></td><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"=
10" height=3D"1" border=3D"0" alt=3D""></td></tr><tr><td><img src=3D"http:/=
/www.carmamail.com/images/pixel.gif" width=3D"1" height=3D"1" alt=3D"" bord=
er=3D"0"></td><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" widt=
h=3D"1" height=3D"15" border=3D"0" alt=3D""></td><td><img src=3D"http://www=
.carmamail.com/images/pixel.gif" width=3D"1" height=3D"1" alt=3D"" border=
=3D"0"></td></tr></table>

<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr>=
<td width=3D"100%"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" =
width=3D"100%"><tr><td valign=3D"top" width=3D"100%"><table cellpadding=3D"=
0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td valign=3D"top"><ta=
ble cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td=
 width=3D"195"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" widt=
h=3D"100%"><tr><td valign=3D"top"><table cellpadding=3D"0" cellspacing=3D"0=
" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://www.carmamail.com/=
img/pixel2.gif" width=3D"10" height=3D"1" border=3D"0" alt=3D""></td><td wi=
dth=3D"100%" align=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" bord=
er=3D"0" width=3D"1"><tr><td><a><img src=3D"http://www.carmamail.com/comhem=
/img2/cover-80x110.gif" alt=3D"" border=3D"0" width=3D"80" height=3D"110"><=
/a></td></tr></table></td><td><img src=3D"http://www.carmamail.com/img/pixe=
l2.gif" width=3D"10" height=3D"1" border=3D"0" alt=3D""></td></tr></table><=
/td><td valign=3D"top" width=3D"100%"><table cellpadding=3D"0" cellspacing=
=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left"><t=
able cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr><td align=3D"left=
"><font face=3D"Arial, sans-serif" size=3D"2" color=3D"#333333" style=3D"fo=
nt-weight: bold;font-style: normal;text-decoration: none;font-size: 11px;">=
Title Row 1<br>=09=09=09=09=09=09=09=09=09=09Title Row 2</font></td></tr></=
table></td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0" width=3D"100%"><tr><td><img src=3D"http://www.carmamail.com/img/pixe=
l2.gif" width=3D"1" height=3D"8" border=3D"0" alt=3D""></td></tr></table><t=
able cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><t=
d width=3D"100%" align=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" =
border=3D"0"><tr><td align=3D"left"><font face=3D"Arial, sans-serif" size=
=3D"2" color=3D"#666666" style=3D"font-weight: normal;font-style: normal;te=
xt-decoration: none;font-size: 11px;">Spel / Genre</font></td></tr></table>=
</td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" w=
idth=3D"100%"><tr><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" =
width=3D"1" height=3D"8" border=3D"0" alt=3D""></td></tr></table><table cel=
lpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td width=
=3D"100%" align=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0"><tr><td align=3D"left"><font face=3D"Arial, sans-serif" size=3D"3" c=
olor=3D"#0068a2" style=3D"font-weight: bold;font-style: normal;text-decorat=
ion: none;font-size: 18px;">000:-</font></td></tr></table></td></tr></table=
><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr=
><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"1" heigh=
t=3D"4" border=3D"0" alt=3D""></td></tr></table><table cellpadding=3D"0" ce=
llspacing=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D=
"left"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr><td><img=
 src=3D"http://www.carmamail.com/comhem/img2/bullet-blue-6x11.gif" alt=3D""=
 border=3D"0" width=3D"6" height=3D"11"></td><td><img src=3D"http://www.car=
mamail.com/img/pixel2.gif" width=3D"5" height=3D"1"></td><td align=3D"left"=
><font size=3D"2" style=3D"font-size: 11px;"><a target=3D"_blank" style=3D"=
text-decoration: none;" href=3D"http://www.carmamail.com/mail/RLS?mid=3D223=
993796&guid=3D13azAb&lid=3D695248" clinkID=3D"695248"><font face=3D"Arial, =
sans-serif" color=3D"#0068a2" style=3D"font-weight: bold;font-style: normal=
;text-decoration: none;">L&auml;s mer</font></a></font></td></tr></table></=
td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" wid=
th=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cellpadding=3D"0" =
cellspacing=3D"0" border=3D"0"><tr><td><img src=3D"http://www.carmamail.com=
/comhem/img2/bullet-purple-6x11.gif" alt=3D"" border=3D"0" width=3D"6" heig=
ht=3D"11"></td><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" wid=
th=3D"5" height=3D"1"></td><td align=3D"left"><font size=3D"2" style=3D"fon=
t-size: 11px;"><a target=3D"_blank" style=3D"text-decoration: none;" href=
=3D"http://www.carmamail.com/mail/RLS?mid=3D223993796&guid=3D13azAb&lid=3D6=
95249" clinkID=3D"695249"><font face=3D"Arial, sans-serif" color=3D"#d10080=
" style=3D"font-weight: bold;font-style: normal;text-decoration: none;">K&o=
uml;p</font></a></font></td></tr></table></td></tr></table></td></tr></tabl=
e></td></tr></table></td><td bgcolor=3D"#e5e5e5" width=3D"1"><img src=3D"ht=
tp://www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"1"></td><td va=
lign=3D"top"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=
=3D"100%"><tr><td width=3D"195"><table cellpadding=3D"0" cellspacing=3D"0" =
border=3D"0" width=3D"100%"><tr><td valign=3D"top"><table cellpadding=3D"0"=
 cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://w=
ww.carmamail.com/img/pixel2.gif" width=3D"10" height=3D"1" border=3D"0" alt=
=3D""></td><td width=3D"100%" align=3D"left"><table cellpadding=3D"0" cells=
pacing=3D"0" border=3D"0" width=3D"1"><tr><td><a><img src=3D"http://www.car=
mamail.com/comhem/img2/cover-80x110.gif" alt=3D"" border=3D"0" width=3D"80"=
 height=3D"110"></a></td></tr></table></td><td><img src=3D"http://www.carma=
mail.com/img/pixel2.gif" width=3D"10" height=3D"1" border=3D"0" alt=3D""></=
td></tr></table></td><td valign=3D"top" width=3D"100%"><table cellpadding=
=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%"=
 align=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr=
><td align=3D"left"><font face=3D"Arial, sans-serif" size=3D"2" color=3D"#3=
33333" style=3D"font-weight: bold;font-style: normal;text-decoration: none;=
font-size: 11px;">Title Row 1<br>=09=09=09=09=09=09=09=09=09=09Title Row 2<=
/font></td></tr></table></td></tr></table><table cellpadding=3D"0" cellspac=
ing=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://www.carmam=
ail.com/img/pixel2.gif" width=3D"1" height=3D"8" border=3D"0" alt=3D""></td=
></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=
=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cellpadding=3D"0" ce=
llspacing=3D"0" border=3D"0"><tr><td align=3D"left"><font face=3D"Arial, sa=
ns-serif" size=3D"2" color=3D"#666666" style=3D"font-weight: normal;font-st=
yle: normal;text-decoration: none;font-size: 11px;">Ljudbok / Genre</font><=
/td></tr></table></td></tr></table><table cellpadding=3D"0" cellspacing=3D"=
0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://www.carmamail.com=
/img/pixel2.gif" width=3D"1" height=3D"8" border=3D"0" alt=3D""></td></tr><=
/table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100=
%"><tr><td width=3D"100%" align=3D"left"><table cellpadding=3D"0" cellspaci=
ng=3D"0" border=3D"0"><tr><td align=3D"left"><font face=3D"Arial, sans-seri=
f" size=3D"3" color=3D"#0068a2" style=3D"font-weight: bold;font-style: norm=
al;text-decoration: none;font-size: 18px;">000:-</font></td></tr></table></=
td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" wid=
th=3D"100%"><tr><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" wi=
dth=3D"1" height=3D"4" border=3D"0" alt=3D""></td></tr></table><table cellp=
adding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D=
"100%" align=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"=
0"><tr><td><img src=3D"http://www.carmamail.com/comhem/img2/bullet-blue-6x1=
1.gif" alt=3D"" border=3D"0" width=3D"6" height=3D"11"></td><td><img src=3D=
"http://www.carmamail.com/img/pixel2.gif" width=3D"5" height=3D"1"></td><td=
 align=3D"left"><font size=3D"2" style=3D"font-size: 11px;"><a target=3D"_b=
lank" style=3D"text-decoration: none;" href=3D"http://www.carmamail.com/mai=
l/RLS?mid=3D223993796&guid=3D13azAb&lid=3D695250" clinkID=3D"695250"><font =
face=3D"Arial, sans-serif" color=3D"#0068a2" style=3D"font-weight: bold;fon=
t-style: normal;text-decoration: none;">L&auml;s mer</font></a></font></td>=
</tr></table></td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" b=
order=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cel=
lpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr><td><img src=3D"http://ww=
w.carmamail.com/comhem/img2/bullet-purple-6x11.gif" alt=3D"" border=3D"0" w=
idth=3D"6" height=3D"11"></td><td><img src=3D"http://www.carmamail.com/img/=
pixel2.gif" width=3D"5" height=3D"1"></td><td align=3D"left"><font size=3D"=
2" style=3D"font-size: 11px;"><a target=3D"_blank" style=3D"text-decoration=
: none;" href=3D"http://www.carmamail.com/mail/RLS?mid=3D223993796&guid=3D1=
3azAb&lid=3D695251" clinkID=3D"695251"><font face=3D"Arial, sans-serif" col=
or=3D"#d10080" style=3D"font-weight: bold;font-style: normal;text-decoratio=
n: none;">K&ouml;p</font></a></font></td></tr></table></td></tr></table></t=
d></tr></table></td></tr></table></td><td bgcolor=3D"#e5e5e5" width=3D"1"><=
img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"1=
"></td><td valign=3D"top"><table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0" width=3D"100%"><tr><td width=3D"195"><table cellpadding=3D"0" cellsp=
acing=3D"0" border=3D"0" width=3D"100%"><tr><td valign=3D"top"><table cellp=
adding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=
=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"10" height=3D"1" bord=
er=3D"0" alt=3D""></td><td width=3D"100%" align=3D"left"><table cellpadding=
=3D"0" cellspacing=3D"0" border=3D"0" width=3D"1"><tr><td><a><img src=3D"ht=
tp://www.carmamail.com/comhem/img2/cover-80x110.gif" alt=3D"" border=3D"0" =
width=3D"80" height=3D"110"></a></td></tr></table></td><td><img src=3D"http=
://www.carmamail.com/img/pixel2.gif" width=3D"10" height=3D"1" border=3D"0"=
 alt=3D""></td></tr></table></td><td valign=3D"top" width=3D"100%"><table c=
ellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td widt=
h=3D"100%" align=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0"><tr><td align=3D"left"><font face=3D"Arial, sans-serif" size=3D"2" c=
olor=3D"#333333" style=3D"font-weight: bold;font-style: normal;text-decorat=
ion: none;font-size: 11px;">Title Row 1<br>=09=09=09=09=09=09=09=09=09=09Ti=
tle Row 2</font></td></tr></table></td></tr></table><table cellpadding=3D"0=
" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://=
www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"8" border=3D"0" alt=
=3D""></td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cellpadd=
ing=3D"0" cellspacing=3D"0" border=3D"0"><tr><td align=3D"left"><font face=
=3D"Arial, sans-serif" size=3D"2" color=3D"#666666" style=3D"font-weight: n=
ormal;font-style: normal;text-decoration: none;font-size: 11px;">Utbildning=
 / Genre</font></td></tr></table></td></tr></table><table cellpadding=3D"0"=
 cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://w=
ww.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"8" border=3D"0" alt=
=3D""></td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cellpadd=
ing=3D"0" cellspacing=3D"0" border=3D"0"><tr><td align=3D"left"><font face=
=3D"Arial, sans-serif" size=3D"3" color=3D"#0068a2" style=3D"font-weight: b=
old;font-style: normal;text-decoration: none;font-size: 18px;">000:-</font>=
</td></tr></table></td></tr></table><table cellpadding=3D"0" cellspacing=3D=
"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://www.carmamail.co=
m/img/pixel2.gif" width=3D"1" height=3D"4" border=3D"0" alt=3D""></td></tr>=
</table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"10=
0%"><tr><td width=3D"100%" align=3D"left"><table cellpadding=3D"0" cellspac=
ing=3D"0" border=3D"0"><tr><td><img src=3D"http://www.carmamail.com/comhem/=
img2/bullet-blue-6x11.gif" alt=3D"" border=3D"0" width=3D"6" height=3D"11">=
</td><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"5" h=
eight=3D"1"></td><td align=3D"left"><font size=3D"2" style=3D"font-size: 11=
px;"><a target=3D"_blank" style=3D"text-decoration: none;" href=3D"http://w=
ww.carmamail.com/mail/RLS?mid=3D223993796&guid=3D13azAb&lid=3D695252" clink=
ID=3D"695252"><font face=3D"Arial, sans-serif" color=3D"#0068a2" style=3D"f=
ont-weight: bold;font-style: normal;text-decoration: none;">L&auml;s mer</f=
ont></a></font></td></tr></table></td></tr></table><table cellpadding=3D"0"=
 cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%" align=
=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr><td><=
img src=3D"http://www.carmamail.com/comhem/img2/bullet-purple-6x11.gif" alt=
=3D"" border=3D"0" width=3D"6" height=3D"11"></td><td><img src=3D"http://ww=
w.carmamail.com/img/pixel2.gif" width=3D"5" height=3D"1"></td><td align=3D"=
left"><font size=3D"2" style=3D"font-size: 11px;"><a target=3D"_blank" styl=
e=3D"text-decoration: none;" href=3D"http://www.carmamail.com/mail/RLS?mid=
=3D223993796&guid=3D13azAb&lid=3D695253" clinkID=3D"695253"><font face=3D"A=
rial, sans-serif" color=3D"#d10080" style=3D"font-weight: bold;font-style: =
normal;text-decoration: none;">K&ouml;p</font></a></font></td></tr></table>=
</td></tr></table></td></tr></table></td></tr></table></td></tr></table></t=
d></tr></table></td></tr><tr><td><img src=3D"http://www.carmamail.com/img/p=
ixel2.gif" width=3D"1" height=3D"15" border=3D"0" alt=3D""></td></tr></tabl=
e><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><t=
r><td width=3D"10"><img src=3D"http://www.carmamail.com/img/pixel2.gif" wid=
th=3D"10" height=3D"1" border=3D"0" alt=3D""></td><td bgcolor=3D"#ebebeb" h=
eight=3D"1"><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"1=
" height=3D"1"></td><td width=3D"10"><img src=3D"http://www.carmamail.com/i=
mg/pixel2.gif" width=3D"10" height=3D"1" border=3D"0" alt=3D""></td></tr><t=
r><td><img src=3D"http://www.carmamail.com/images/pixel.gif" width=3D"1" he=
ight=3D"1" alt=3D"" border=3D"0"></td><td height=3D"15"><img src=3D"http://=
www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"15" border=3D"0" al=
t=3D""></td><td><img src=3D"http://www.carmamail.com/images/pixel.gif" widt=
h=3D"1" height=3D"1" alt=3D"" border=3D"0"></td></tr></table>

<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr>=
<td width=3D"100%"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" =
width=3D"100%"><tr><td valign=3D"top" width=3D"100%"><table cellpadding=3D"=
0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td valign=3D"top"><ta=
ble cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td=
 width=3D"195"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" widt=
h=3D"100%"><tr><td valign=3D"top"><table cellpadding=3D"0" cellspacing=3D"0=
" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://www.carmamail.com/=
img/pixel2.gif" width=3D"10" height=3D"1" border=3D"0" alt=3D""></td><td wi=
dth=3D"100%" align=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" bord=
er=3D"0" width=3D"1"><tr><td><a><img src=3D"http://www.carmamail.com/comhem=
/img2/cover-80x110.gif" alt=3D"" border=3D"0" width=3D"80" height=3D"110"><=
/a></td></tr></table></td><td><img src=3D"http://www.carmamail.com/img/pixe=
l2.gif" width=3D"10" height=3D"1" border=3D"0" alt=3D""></td></tr></table><=
/td><td valign=3D"top" width=3D"100%"><table cellpadding=3D"0" cellspacing=
=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left"><t=
able cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr><td align=3D"left=
"><font face=3D"Arial, sans-serif" size=3D"2" color=3D"#333333" style=3D"fo=
nt-weight: bold;font-style: normal;text-decoration: none;font-size: 11px;">=
Title Row 1<br>=09=09=09=09=09=09=09=09=09=09Title Row 2</font></td></tr></=
table></td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0" width=3D"100%"><tr><td><img src=3D"http://www.carmamail.com/img/pixe=
l2.gif" width=3D"1" height=3D"8" border=3D"0" alt=3D""></td></tr></table><t=
able cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><t=
d width=3D"100%" align=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" =
border=3D"0"><tr><td align=3D"left"><font face=3D"Arial, sans-serif" size=
=3D"2" color=3D"#666666" style=3D"font-weight: normal;font-style: normal;te=
xt-decoration: none;font-size: 11px;">Spel / Genre</font></td></tr></table>=
</td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" w=
idth=3D"100%"><tr><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" =
width=3D"1" height=3D"8" border=3D"0" alt=3D""></td></tr></table><table cel=
lpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td width=
=3D"100%" align=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0"><tr><td align=3D"left"><font face=3D"Arial, sans-serif" size=3D"3" c=
olor=3D"#0068a2" style=3D"font-weight: bold;font-style: normal;text-decorat=
ion: none;font-size: 18px;">000:-</font></td></tr></table></td></tr></table=
><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr=
><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"1" heigh=
t=3D"4" border=3D"0" alt=3D""></td></tr></table><table cellpadding=3D"0" ce=
llspacing=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D=
"left"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr><td><img=
 src=3D"http://www.carmamail.com/comhem/img2/bullet-blue-6x11.gif" alt=3D""=
 border=3D"0" width=3D"6" height=3D"11"></td><td><img src=3D"http://www.car=
mamail.com/img/pixel2.gif" width=3D"5" height=3D"1"></td><td align=3D"left"=
><font size=3D"2" style=3D"font-size: 11px;"><a target=3D"_blank" style=3D"=
text-decoration: none;" href=3D"http://www.carmamail.com/mail/RLS?mid=3D223=
993796&guid=3D13azAb&lid=3D695254" clinkID=3D"695254"><font face=3D"Arial, =
sans-serif" color=3D"#0068a2" style=3D"font-weight: bold;font-style: normal=
;text-decoration: none;">L&auml;s mer</font></a></font></td></tr></table></=
td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" wid=
th=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cellpadding=3D"0" =
cellspacing=3D"0" border=3D"0"><tr><td><img src=3D"http://www.carmamail.com=
/comhem/img2/bullet-purple-6x11.gif" alt=3D"" border=3D"0" width=3D"6" heig=
ht=3D"11"></td><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" wid=
th=3D"5" height=3D"1"></td><td align=3D"left"><font size=3D"2" style=3D"fon=
t-size: 11px;"><a target=3D"_blank" style=3D"text-decoration: none;" href=
=3D"http://www.carmamail.com/mail/RLS?mid=3D223993796&guid=3D13azAb&lid=3D6=
95255" clinkID=3D"695255"><font face=3D"Arial, sans-serif" color=3D"#d10080=
" style=3D"font-weight: bold;font-style: normal;text-decoration: none;">K&o=
uml;p</font></a></font></td></tr></table></td></tr></table></td></tr></tabl=
e></td></tr></table></td><td bgcolor=3D"#e5e5e5" width=3D"1"><img src=3D"ht=
tp://www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"1"></td><td va=
lign=3D"top"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=
=3D"100%"><tr><td width=3D"195"><table cellpadding=3D"0" cellspacing=3D"0" =
border=3D"0" width=3D"100%"><tr><td valign=3D"top"><table cellpadding=3D"0"=
 cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://w=
ww.carmamail.com/img/pixel2.gif" width=3D"10" height=3D"1" border=3D"0" alt=
=3D""></td><td width=3D"100%" align=3D"left"><table cellpadding=3D"0" cells=
pacing=3D"0" border=3D"0" width=3D"1"><tr><td><a><img src=3D"http://www.car=
mamail.com/comhem/img2/cover-80x110.gif" alt=3D"" border=3D"0" width=3D"80"=
 height=3D"110"></a></td></tr></table></td><td><img src=3D"http://www.carma=
mail.com/img/pixel2.gif" width=3D"10" height=3D"1" border=3D"0" alt=3D""></=
td></tr></table></td><td valign=3D"top" width=3D"100%"><table cellpadding=
=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%"=
 align=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr=
><td align=3D"left"><font face=3D"Arial, sans-serif" size=3D"2" color=3D"#3=
33333" style=3D"font-weight: bold;font-style: normal;text-decoration: none;=
font-size: 11px;">Title Row 1<br>=09=09=09=09=09=09=09=09=09=09Title Row 2<=
/font></td></tr></table></td></tr></table><table cellpadding=3D"0" cellspac=
ing=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://www.carmam=
ail.com/img/pixel2.gif" width=3D"1" height=3D"8" border=3D"0" alt=3D""></td=
></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=
=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cellpadding=3D"0" ce=
llspacing=3D"0" border=3D"0"><tr><td align=3D"left"><font face=3D"Arial, sa=
ns-serif" size=3D"2" color=3D"#666666" style=3D"font-weight: normal;font-st=
yle: normal;text-decoration: none;font-size: 11px;">Ljudbok / Genre</font><=
/td></tr></table></td></tr></table><table cellpadding=3D"0" cellspacing=3D"=
0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://www.carmamail.com=
/img/pixel2.gif" width=3D"1" height=3D"8" border=3D"0" alt=3D""></td></tr><=
/table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100=
%"><tr><td width=3D"100%" align=3D"left"><table cellpadding=3D"0" cellspaci=
ng=3D"0" border=3D"0"><tr><td align=3D"left"><font face=3D"Arial, sans-seri=
f" size=3D"3" color=3D"#0068a2" style=3D"font-weight: bold;font-style: norm=
al;text-decoration: none;font-size: 18px;">000:-</font></td></tr></table></=
td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" wid=
th=3D"100%"><tr><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" wi=
dth=3D"1" height=3D"4" border=3D"0" alt=3D""></td></tr></table><table cellp=
adding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D=
"100%" align=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"=
0"><tr><td><img src=3D"http://www.carmamail.com/comhem/img2/bullet-blue-6x1=
1.gif" alt=3D"" border=3D"0" width=3D"6" height=3D"11"></td><td><img src=3D=
"http://www.carmamail.com/img/pixel2.gif" width=3D"5" height=3D"1"></td><td=
 align=3D"left"><font size=3D"2" style=3D"font-size: 11px;"><a target=3D"_b=
lank" style=3D"text-decoration: none;" href=3D"http://www.carmamail.com/mai=
l/RLS?mid=3D223993796&guid=3D13azAb&lid=3D695256" clinkID=3D"695256"><font =
face=3D"Arial, sans-serif" color=3D"#0068a2" style=3D"font-weight: bold;fon=
t-style: normal;text-decoration: none;">L&auml;s mer</font></a></font></td>=
</tr></table></td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" b=
order=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cel=
lpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr><td><img src=3D"http://ww=
w.carmamail.com/comhem/img2/bullet-purple-6x11.gif" alt=3D"" border=3D"0" w=
idth=3D"6" height=3D"11"></td><td><img src=3D"http://www.carmamail.com/img/=
pixel2.gif" width=3D"5" height=3D"1"></td><td align=3D"left"><font size=3D"=
2" style=3D"font-size: 11px;"><a target=3D"_blank" style=3D"text-decoration=
: none;" href=3D"http://www.carmamail.com/mail/RLS?mid=3D223993796&guid=3D1=
3azAb&lid=3D695257" clinkID=3D"695257"><font face=3D"Arial, sans-serif" col=
or=3D"#d10080" style=3D"font-weight: bold;font-style: normal;text-decoratio=
n: none;">K&ouml;p</font></a></font></td></tr></table></td></tr></table></t=
d></tr></table></td></tr></table></td><td bgcolor=3D"#e5e5e5" width=3D"1"><=
img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"1=
"></td><td valign=3D"top"><table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0" width=3D"100%"><tr><td width=3D"195"><table cellpadding=3D"0" cellsp=
acing=3D"0" border=3D"0" width=3D"100%"><tr><td valign=3D"top"><table cellp=
adding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=
=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"10" height=3D"1" bord=
er=3D"0" alt=3D""></td><td width=3D"100%" align=3D"left"><table cellpadding=
=3D"0" cellspacing=3D"0" border=3D"0" width=3D"1"><tr><td><a><img src=3D"ht=
tp://www.carmamail.com/comhem/img2/cover-80x110.gif" alt=3D"" border=3D"0" =
width=3D"80" height=3D"110"></a></td></tr></table></td><td><img src=3D"http=
://www.carmamail.com/img/pixel2.gif" width=3D"10" height=3D"1" border=3D"0"=
 alt=3D""></td></tr></table></td><td valign=3D"top" width=3D"100%"><table c=
ellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td widt=
h=3D"100%" align=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0"><tr><td align=3D"left"><font face=3D"Arial, sans-serif" size=3D"2" c=
olor=3D"#333333" style=3D"font-weight: bold;font-style: normal;text-decorat=
ion: none;font-size: 11px;">Title Row 1<br>=09=09=09=09=09=09=09=09=09=09Ti=
tle Row 2</font></td></tr></table></td></tr></table><table cellpadding=3D"0=
" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://=
www.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"8" border=3D"0" alt=
=3D""></td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cellpadd=
ing=3D"0" cellspacing=3D"0" border=3D"0"><tr><td align=3D"left"><font face=
=3D"Arial, sans-serif" size=3D"2" color=3D"#666666" style=3D"font-weight: n=
ormal;font-style: normal;text-decoration: none;font-size: 11px;">Utbildning=
 / Genre</font></td></tr></table></td></tr></table><table cellpadding=3D"0"=
 cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://w=
ww.carmamail.com/img/pixel2.gif" width=3D"1" height=3D"8" border=3D"0" alt=
=3D""></td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cellpadd=
ing=3D"0" cellspacing=3D"0" border=3D"0"><tr><td align=3D"left"><font face=
=3D"Arial, sans-serif" size=3D"3" color=3D"#0068a2" style=3D"font-weight: b=
old;font-style: normal;text-decoration: none;font-size: 18px;">000:-</font>=
</td></tr></table></td></tr></table><table cellpadding=3D"0" cellspacing=3D=
"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://www.carmamail.co=
m/img/pixel2.gif" width=3D"1" height=3D"4" border=3D"0" alt=3D""></td></tr>=
</table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"10=
0%"><tr><td width=3D"100%" align=3D"left"><table cellpadding=3D"0" cellspac=
ing=3D"0" border=3D"0"><tr><td><img src=3D"http://www.carmamail.com/comhem/=
img2/bullet-blue-6x11.gif" alt=3D"" border=3D"0" width=3D"6" height=3D"11">=
</td><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"5" h=
eight=3D"1"></td><td align=3D"left"><font size=3D"2" style=3D"font-size: 11=
px;"><a target=3D"_blank" style=3D"text-decoration: none;" href=3D"http://w=
ww.carmamail.com/mail/RLS?mid=3D223993796&guid=3D13azAb&lid=3D695258" clink=
ID=3D"695258"><font face=3D"Arial, sans-serif" color=3D"#0068a2" style=3D"f=
ont-weight: bold;font-style: normal;text-decoration: none;">L&auml;s mer</f=
ont></a></font></td></tr></table></td></tr></table><table cellpadding=3D"0"=
 cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%" align=
=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr><td><=
img src=3D"http://www.carmamail.com/comhem/img2/bullet-purple-6x11.gif" alt=
=3D"" border=3D"0" width=3D"6" height=3D"11"></td><td><img src=3D"http://ww=
w.carmamail.com/img/pixel2.gif" width=3D"5" height=3D"1"></td><td align=3D"=
left"><font size=3D"2" style=3D"font-size: 11px;"><a target=3D"_blank" styl=
e=3D"text-decoration: none;" href=3D"http://www.carmamail.com/mail/RLS?mid=
=3D223993796&guid=3D13azAb&lid=3D695259" clinkID=3D"695259"><font face=3D"A=
rial, sans-serif" color=3D"#d10080" style=3D"font-weight: bold;font-style: =
normal;text-decoration: none;">K&ouml;p</font></a></font></td></tr></table>=
</td></tr></table></td></tr></table></td></tr></table></td></tr></table></t=
d></tr></table></td></tr><tr><td><img src=3D"http://www.carmamail.com/img/p=
ixel2.gif" width=3D"1" height=3D"15" border=3D"0" alt=3D""></td></tr></tabl=
e>

</td><td bgcolor=3D"#e5e5e5"><img src=3D"http://www.carmamail.com/img/pixel=
2.gif" width=3D"1" height=3D"1" border=3D"0" alt=3D""></td></tr></table></t=
d></tr><tr><td><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" widt=
h=3D"100%"><tr><td width=3D"100%" bgcolor=3D"#676767" background=3D"http://=
www.carmamail.com/comhem/img2/bottom-bg.gif" style=3D"background-image: url=
(http://www.carmamail.com/comhem/img2/bottom-bg.gif);background-repeat: rep=
eat-x;">

<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr>=
<td><img src=3D"http://www.carmamail.com/images/pixel.gif" width=3D"1" heig=
ht=3D"1" alt=3D"" border=3D"0"></td><td><img src=3D"http://www.carmamail.co=
m/img/pixel2.gif" width=3D"1" height=3D"20" border=3D"0" alt=3D""></td><td>=
<img src=3D"http://www.carmamail.com/images/pixel.gif" width=3D"1" height=
=3D"1" alt=3D"" border=3D"0"></td></tr><tr><td><img src=3D"http://www.carma=
mail.com/img/pixel2.gif" width=3D"10" height=3D"1" border=3D"0" alt=3D""></=
td><td width=3D"100%"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"=
0" width=3D"100%"><tr><td valign=3D"top" width=3D"100%"><table cellpadding=
=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td valign=3D"top"=
><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr=
><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"10" heig=
ht=3D"1" border=3D"0" alt=3D""></td><td width=3D"100%"><table cellpadding=
=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td valign=3D"top"=
 width=3D"100%"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" wid=
th=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cellpadding=3D"0" =
cellspacing=3D"0" border=3D"0"><tr><td align=3D"left"><font face=3D"Arial, =
sans-serif" size=3D"3" color=3D"#ffffff" style=3D"font-weight: bold;font-st=
yle: normal;text-decoration: none;font-size: 14px;">P&aring; tv i veckan</f=
ont></td></tr></table></td></tr></table><table cellpadding=3D"0" cellspacin=
g=3D"0" border=3D"0" width=3D"100%"><tr><td><img src=3D"http://www.carmamai=
l.com/img/pixel2.gif" width=3D"1" height=3D"10" border=3D"0" alt=3D""></td>=
</tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=
=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cellpadding=3D"0" ce=
llspacing=3D"0" border=3D"0" width=3D"1"><tr><td><a href=3D"http://www.carm=
amail.com/mail/RLS?mid=3D223993796&guid=3D13azAb&lid=3D695260" clinkID=3D"6=
95260"><img src=3D"http://www.carmamail.com/comhem/img2/tv-guiden-76x22.gif=
" alt=3D"" border=3D"0" width=3D"76" height=3D"22"></a></td></tr></table></=
td></tr></table></td></tr></table></td></tr></table></td><td valign=3D"top"=
><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr=
><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"10" heig=
ht=3D"1" border=3D"0" alt=3D""></td><td width=3D"100%"><table cellpadding=
=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td valign=3D"top"=
><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr=
><td width=3D"100%" align=3D"left"><table cellpadding=3D"0" cellspacing=3D"=
0" border=3D"0" width=3D"1"><tr><td><a><img src=3D"http://www.carmamail.com=
/comhem/img2/small-spot-60x67.gif" alt=3D"" border=3D"0" width=3D"60" heigh=
t=3D"67"></a></td></tr></table></td><td><img src=3D"http://www.carmamail.co=
m/img/pixel2.gif" width=3D"8" height=3D"1" border=3D"0" alt=3D""></td></tr>=
</table></td><td valign=3D"top" width=3D"100%"><table cellpadding=3D"0" cel=
lspacing=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"=
left"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr><td align=
=3D"left"><font face=3D"Arial, sans-serif" size=3D"2" color=3D"#ffffff" sty=
le=3D"font-weight: normal;font-style: normal;text-decoration: none;font-siz=
e: 11px;"><b>Title</b><br>=09=09=09=09=09=09=09=09=09=09<br>=09=09=09=09=09=
=09=09=09=09=09Day hh:mm<br>=09=09=09=09=09=09=09=09=09=09</font></td></tr>=
</table></td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cellpadd=
ing=3D"0" cellspacing=3D"0" border=3D"0"><tr><td><img src=3D"http://www.car=
mamail.com/SuperTemplate/bullet.gif" alt=3D"" border=3D"0" width=3D"3" heig=
ht=3D"5"></td><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" widt=
h=3D"2" height=3D"1"></td><td align=3D"left"><font face=3D"Arial, sans-seri=
f" size=3D"2" color=3D"#ffffff" style=3D"font-weight: normal;font-style: no=
rmal;text-decoration: none;font-size: 11px;">Channel</font></td></tr></tabl=
e></td></tr></table></td></tr></table></td></tr></table></td><td valign=3D"=
top"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"=
><tr><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"10" =
height=3D"1" border=3D"0" alt=3D""></td><td width=3D"100%"><table cellpaddi=
ng=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td valign=3D"to=
p"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><=
tr><td width=3D"100%" align=3D"left"><table cellpadding=3D"0" cellspacing=
=3D"0" border=3D"0" width=3D"1"><tr><td><a><img src=3D"http://www.carmamail=
.com/comhem/img2/small-spot-60x67.gif" alt=3D"" border=3D"0" width=3D"60" h=
eight=3D"67"></a></td></tr></table></td><td><img src=3D"http://www.carmamai=
l.com/img/pixel2.gif" width=3D"8" height=3D"1" border=3D"0" alt=3D""></td><=
/tr></table></td><td valign=3D"top" width=3D"100%"><table cellpadding=3D"0"=
 cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%" align=
=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr><td a=
lign=3D"left"><font face=3D"Arial, sans-serif" size=3D"2" color=3D"#ffffff"=
 style=3D"font-weight: normal;font-style: normal;text-decoration: none;font=
-size: 11px;"><b>Title</b><br>=09=09=09=09=09=09=09=09=09=09<br>=09=09=09=
=09=09=09=09=09=09=09Day hh:mm<br>=09=09=09=09=09=09=09=09=09=09</font></td=
></tr></table></td></tr></table><table cellpadding=3D"0" cellspacing=3D"0" =
border=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left"><table ce=
llpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr><td><img src=3D"http://w=
ww.carmamail.com/SuperTemplate/bullet.gif" alt=3D"" border=3D"0" width=3D"3=
" height=3D"5"></td><td><img src=3D"http://www.carmamail.com/img/pixel2.gif=
" width=3D"2" height=3D"1"></td><td align=3D"left"><font face=3D"Arial, san=
s-serif" size=3D"2" color=3D"#ffffff" style=3D"font-weight: normal;font-sty=
le: normal;text-decoration: none;font-size: 11px;">Channel</font></td></tr>=
</table></td></tr></table></td></tr></table></td></tr></table></td><td vali=
gn=3D"top"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D=
"100%"><tr><td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=
=3D"10" height=3D"1" border=3D"0" alt=3D""></td><td width=3D"100%"><table c=
ellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td vali=
gn=3D"top"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D=
"100%"><tr><td width=3D"100%" align=3D"left"><table cellpadding=3D"0" cells=
pacing=3D"0" border=3D"0" width=3D"1"><tr><td><a><img src=3D"http://www.car=
mamail.com/comhem/img2/small-spot-60x67.gif" alt=3D"" border=3D"0" width=3D=
"60" height=3D"67"></a></td></tr></table></td><td><img src=3D"http://www.ca=
rmamail.com/img/pixel2.gif" width=3D"8" height=3D"1" border=3D"0" alt=3D"">=
</td></tr></table></td><td valign=3D"top" width=3D"100%"><table cellpadding=
=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%"=
 align=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr=
><td align=3D"left"><font face=3D"Arial, sans-serif" size=3D"2" color=3D"#f=
fffff" style=3D"font-weight: normal;font-style: normal;text-decoration: non=
e;font-size: 11px;"><b>Title</b><br>=09=09=09=09=09=09=09=09=09=09<br>=09=
=09=09=09=09=09=09=09=09=09Day hh:mm<br>=09=09=09=09=09=09=09=09=09=09</fon=
t></td></tr></table></td></tr></table><table cellpadding=3D"0" cellspacing=
=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left"><t=
able cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr><td><img src=3D"h=
ttp://www.carmamail.com/SuperTemplate/bullet.gif" alt=3D"" border=3D"0" wid=
th=3D"3" height=3D"5"></td><td><img src=3D"http://www.carmamail.com/img/pix=
el2.gif" width=3D"2" height=3D"1"></td><td align=3D"left"><font face=3D"Ari=
al, sans-serif" size=3D"2" color=3D"#ffffff" style=3D"font-weight: normal;f=
ont-style: normal;text-decoration: none;font-size: 11px;">Channel</font></t=
d></tr></table></td></tr></table></td></tr></table></td></tr></table></td><=
/tr></table></td></tr></table></td><td><img src=3D"http://www.carmamail.com=
/img/pixel2.gif" width=3D"10" height=3D"1" border=3D"0" alt=3D""></td></tr>=
<tr><td><img src=3D"http://www.carmamail.com/images/pixel.gif" width=3D"1" =
height=3D"1" alt=3D"" border=3D"0"></td><td><img src=3D"http://www.carmamai=
l.com/img/pixel2.gif" width=3D"1" height=3D"20" border=3D"0" alt=3D""></td>=
<td><img src=3D"http://www.carmamail.com/images/pixel.gif" width=3D"1" heig=
ht=3D"1" alt=3D"" border=3D"0"></td></tr></table>

<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr>=
<td width=3D"100%"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" =
width=3D"100%"><tr><td valign=3D"top" width=3D"100%"><table cellpadding=3D"=
0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td width=3D"100%" ali=
gn=3D"left"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=
=3D"1"><tr><td><a><img src=3D"http://www.carmamail.com/comhem/img2/bottom-c=
orners-600x8.gif" alt=3D"" border=3D"0" width=3D"600" height=3D"8"></a></td=
></tr></table></td></tr></table></td></tr></table></td></tr></table>

</td></tr></table></td></tr></table></td></tr><tr><td>

<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr>=
<td><img src=3D"http://www.carmamail.com/img/pixel2.gif" width=3D"1" height=
=3D"10" border=3D"0" alt=3D""></td></tr><tr><td width=3D"100%"><table cellp=
adding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr><td valign=
=3D"top" width=3D"100%"><table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0" width=3D"100%"><tr><td width=3D"100%" align=3D"left"><table cellpadd=
ing=3D"0" cellspacing=3D"0" border=3D"0"><tr><td align=3D"left"><font size=
=3D"2" style=3D"font-size: 11px;"><a style=3D"text-decoration: underline;" =
href=3D"http://www.carmamail.com/mail/RLS?mid=3D223993796&guid=3D13azAb&lid=
=3D695261" clinkID=3D"695261"><font face=3D"Arial, sans-serif" color=3D"#99=
9999" style=3D"font-weight: normal;font-style: normal;text-decoration: unde=
rline;">Avsluta prenumeration</font></a></font></td></tr></table></td></tr>=
</table></td></tr></table></td></tr><tr><td><img src=3D"http://www.carmamai=
l.com/img/pixel2.gif" width=3D"1" height=3D"25" border=3D"0" alt=3D""></td>=
</tr></table>

</td></tr></table></td></tr></table></body></html>

------=_Part_329666_58751540.1301655732499--
