Return-Path: <bo-bx6rw3raupta74au6m0rxbysph09qe@b.avivaemail.co.uk>
X-Original-To: alchemyworx@cp.assurance.returnpath.net
Delivered-To: assurance@localhost.returnpath.net
Received: from mxa-d1.returnpath.net (unknown [10.8.2.117])
	by cpa-d1.returnpath.net (Postfix) with ESMTP id 84EBF198271
	for <alchemyworx@cp.assurance.returnpath.net>; Fri,  1 Apr 2011 08:14:28 -0600 (MDT)
Received: from mta141.norwichunionemail.com (mta141.norwichunionemail.com [64.37.95.217])
	by mxa-d1.returnpath.net (Postfix) with SMTP id 727BEBCC
	for <alchemyworx@cp.assurance.returnpath.net>; Fri,  1 Apr 2011 08:14:27 -0600 (MDT)
DomainKey-Signature: a=rsa-sha1; q=dns; c=nofws;
  s=200505; d=avivaemail.co.uk;
  b=E4WJDZHtNvKzks4LOkpPErtbJZwW7nlYg6X21Fu5H66AXXaHgKxs7bVXeE7GQ7Sx4jB4T7fv4CdYp/JW4mIrJpuubCCc8ZzzvPo6PEdJHNT856KIR1Dt/UR+Jx+fcbYQ/NO/jIilt4KQfeNzsm+FvP7QnV6jRXeOq1k+CTc1xHo=;
 h=Date:Message-ID:List-Unsubscribe:From:To:Subject:MIME-Version:Reply-To:Content-type;
Date: Fri, 1 Apr 2011 14:14:49 -0000
Message-ID: <bx6rw3raupta74au6m0rxbysph09qe.0.15@mta141.avivaemail.co.uk>
List-Unsubscribe: <mailto:rm-0bx6rw3raupta74au6m0rxbysph09qe@avivaemail.co.uk>
From: =?utf-8?q?Aviva?= <aviva@avivaemail.co.uk>
To: alchemyworx@cp.assurance.returnpath.net
Subject: (TEST-Multipart) =?utf-8?q?=5BRetention_In_Life_ezine=5Fhome=5F050411=5D_Introducing_Your_?=
 =?utf-8?q?Aviva_Essentials=3A_Win_4_tickets_to_the_Aviva_Premiership_Rugb?=
 =?utf-8?q?y_Final=2C_Keep_the_cost_of_driving_down_and_more?=
MIME-Version: 1.0
Reply-To: =?utf-8?q?Aviva?= <support-bx6rw3raupta74au6m0rxbysph09qe@avivaemail.co.uk>
Content-type: multipart/alternative; boundary="=bx6rw3raupta74au6m0rxbysph09qe"


--=bx6rw3raupta74au6m0rxbysph09qe
Content-Type: text/plain; charset="utf-8"
Content-transfer-encoding: 8bit


Aviva 

If this email doesn't display correctly, 
click here :
http://avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL/hosted?track=avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL&t_params=FNAME%3DReturn%26REMOVE%3Drm-0bx6rw3raupta74au6m0rxbysph09qe%2540avivaemail.co.uk

AVIVA - Your Aviva Essentials http://avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL/avivalp 

Motor : http://avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL/carlp 

Home : http://avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL/homelp 

Travel : http://avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL/travelp 

Breakdown : http://avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL/breakdlp 

Dear Return,

Welcome to Your Aviva Essentials, our customer newsletter jam-packed
with tips and advice. What are you planning for the Easter holidays? If
it's DIY or a family break we've got lots of great tips and inspiration.


In this issue of the Aviva eZine:

Keep the cost of driving down
Top 5 family days out
Top 5 DIY checks
The latest security guidelines for travellers
Street to school - Sarah's* story

PS Thanks for all your previous feedback, check out the cost savings tips
we have put together for you. 
Tell us more : http://avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL/complp?CLIENTID= about what you think of the
eZine.

http://avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL/complp?CLIENTID= 

Keep the cost of driving down: be green

Save money at the pumps and go further on one tank of petrol with our
green driving tips, brought to you in association with experts at the
RAC. You could see a 15% fuel efficiency improvement.

Read our money-saving tips : http://avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL/costfelp 

Keep the cost of driving down: be green http://avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL/costfelp 

Top 5 family days out 

The long bank holiday can only mean one thing – fun day trips! We've put
together our top 5 days out under £100 – and a couple of tips to survive
any long car journeys with the kids. 

Top 5 family days out : http://avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL/motorfelp 

Days out with kids http://avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL/motorfelp 

Top 5 DIY checks: get your house in order this Easter

Planning to decorate this Easter holiday? Make sure you've got the
groundwork right first with our 5 helpful DIY checks. Even better, make
the checks an annual habit and you'll sleep easier knowing there's less
chance any unwelcome surprises will surface.

Check out our 5 DIY checks : http://avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL/homefelp  

Up-to-date security travel advice

Going away? Saunter through the airports – and ensure you're able to
keep those luxury items in your handbag – by reading the latest security
guidelines. Plus, what to do if you're ill while you're away.

The latest security guidelines : http://avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL/travelfelp 

Up-to-date security travel advice http://avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL/travelfelp 

Street to school - Sarah's* story

We've partnered with Railway Children, a charity who dedicates its work
to helping vulnerable children like Sarah who are at risk on our
streets. Sarah was reunited with her family and is now at college,
thanks to support from Railway Children. 

Read about Street-to-school : http://avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL/sponsorlp 

Street-to-school - Sarah's* story http://avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL/sponsorlp 

Win 4 tickets to the Rubgy Premiership Final http://avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL/complp?CLIENTID= 

Win one of 3 sets of 4 tickets to the Aviva Premiership Rugby Final at
Twickenham Stadium on 28 May 2011 

Enter now http://avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL/complp?CLIENTID= 

Winner of the November competition : TBC 

Joan Beesley, Merseyside, won a Sony HD TV and Blu-Ray player.
"The prize was brilliant, we were amazed at winning such a fantastic
prize and would just like to say thank you to everyone at Aviva" : TBC 

Enter now : TBC 
Top tips for getting fit at home TBC 

My Policy

My Policy http://avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL/mypollp 

Register for My Policyto: 

Check your policy details

Make a claim

Change your cover

Renew your policy online

Benefit from an exclusive package of travel, leisure and high street
offers.

My Policy : http://avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL/mypollp 

Online tools

Update your policy : http://avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL/mypollp 

Home contents calculator : http://avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL/concalclp 

Route planner : http://avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL/routelp 

My claims app for iPhone : http://avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL/claimslp 

Facebook http://avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL/fbooklp 

Digg http://avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL/digglp 

Twitter http://avivaemail.co.uk/a/tBNld25AWKyy7B8Z$5RAAAAAAcL/twitterlp 

* Sarah is a fictious name, used to protect the individual's identity

If you would prefer not to receive any further marketing information
from Aviva by email, simply send a 
blank email to us : mailto:rm-0bx6rw3raupta74au6m0rxbysph09qe@avivaemail.co.uk . 
This email and any files sent with it are intended only for the named
recipient. If you are not the named recipient please telephone/email the
sender immediately. You should not disclose the content or
take/retain/distribute any copies. 

Aviva Insurance UK Limited, Registered Office: 8 Surrey Street, Norwich
NR1 3NG. Registered in England No. 99122. Authorised and regulated by
the Financial Services Authority. 

NFPZZA00011 Mar11

--=bx6rw3raupta74au6m0rxbysph09qe
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><head>=
<title>Aviva
</title><meta http-equiv=3D"Content-Type" content=3D"text/html;charset=3DUT=
F-8"></head><body onload=3D'' margintop=3D"0" marginleft=3D"0" marginright=
=3D"0" bgcolor=3D"#eef5f9">






<table width=3D"100%" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" bgco=
lor=3D"#eef5f9" align=3D"center">
<tr>
<td width=3D"100%">
<table width=3D"600" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" bgcol=
or=3D"#eef5f9" align=3D"center">
<tr>
<td width=3D"600">
<table width=3D"600" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"14"></td>
<td width=3D"586" height=3D"25" style=3D"font-family:arial,helvetica,freesa=
ns,sans-serif;font-size:11px;color:#0051b5">If this email doesn't display c=
orrectly,
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/hosted?tra=
ck=3Davivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL&t_params=3DFNAME%3DRetu=
rn%26REMOVE%3Drm-0bx6rw3raupta74au6m0rxbysph09qe%2540avivaemail.co.uk" styl=
e=3D"text-decoration:underline;color:#0051b5" target=3D"_blank">click here<=
/a>.</td>
</tr>
</table>
<table width=3D"600" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"9"></td>
<td width=3D"584">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/avivalp" t=
arget=3D"_blank">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_header.gif" style=3D"dis=
play:block" width=3D"584" height=3D"81" alt=3D"AVIVA - Your Aviva Essential=
s" title=3D"AVIVA - Your Aviva Essentials" border=3D"0"></a></td>
<td width=3D"7"></td>
</tr>
</table>
<table width=3D"600" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"9"></td>
<td width=3D"1" bgcolor=3D"#ebf2f6"></td>
<td width=3D"1" bgcolor=3D"#e5ebef"></td>
<td width=3D"1" bgcolor=3D"#dae1e4"></td>
<td width=3D"576" valign=3D"top" bgcolor=3D"#ffffff">
<table width=3D"576" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" bgcol=
or=3D"#fdd100">
<tr>
<td width=3D"16"></td>
<td width=3D"386">
<table width=3D"386" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"95" height=3D"29" bgcolor=3D"#faf5cf" background=3D"http://f.c=
htah.com/i/9/371928251/p2217_nav_bg.gif" style=3D"background-image:url('htt=
p://f.chtah.com/i/9/371928251/p2217_nav_bg.gif');">
<center>
<span style=3D"font-family:arial,helvetica,freesans,sans-serif;font-size:12=
px;color:#004fb6;">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/carlp" sty=
le=3D"text-decoration:none;color:#004fb6" target=3D"_blank"><strong>Motor</=
strong></a>
</span>
</center></td>
<td width=3D"1" bgcolor=3D"#bebba0"></td>
<td width=3D"1" bgcolor=3D"#fffffd"></td>
<td width=3D"95" height=3D"29" bgcolor=3D"#faf5cf" background=3D"http://f.c=
htah.com/i/9/371928251/p2217_nav_bg.gif" style=3D"background-image:url('htt=
p://f.chtah.com/i/9/371928251/p2217_nav_bg.gif');">
<center>
<span style=3D"font-family:arial,helvetica,freesans,sans-serif;font-size:12=
px;color:#004fb6;">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/homelp" st=
yle=3D"text-decoration:none;color:#004fb6" target=3D"_blank"><strong>Home</=
strong></a>
</span>
</center></td>
<td width=3D"1" bgcolor=3D"#bebba0"></td>
<td width=3D"1" bgcolor=3D"#fffffd"></td>
<td width=3D"95" height=3D"29" bgcolor=3D"#faf5cf" background=3D"http://f.c=
htah.com/i/9/371928251/p2217_nav_bg.gif" style=3D"background-image:url('htt=
p://f.chtah.com/i/9/371928251/p2217_nav_bg.gif');">
<center>
<span style=3D"font-family:arial,helvetica,freesans,sans-serif;font-size:12=
px;color:#004fb6;">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/travelp" s=
tyle=3D"text-decoration:none;color:#004fb6" target=3D"_blank"><strong>Trave=
l</strong></a>
</span>
</center></td>
<td width=3D"1" bgcolor=3D"#bebba0"></td>
<td width=3D"1" bgcolor=3D"#fffffd"></td>
<td width=3D"95" height=3D"29" bgcolor=3D"#faf5cf" background=3D"http://f.c=
htah.com/i/9/371928251/p2217_nav_bg.gif" style=3D"background-image:url('htt=
p://f.chtah.com/i/9/371928251/p2217_nav_bg.gif');">
<center>
<span style=3D"font-family:arial,helvetica,freesans,sans-serif;font-size:12=
px;color:#004fb6;">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/breakdlp" =
style=3D"text-decoration:none;color:#004fb6" target=3D"_blank"><strong>Brea=
kdown</strong></a>
</span>
</center></td>
</tr>
</table></td>
<td width=3D"174">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_header_br.gif" style=3D"=
display:block" width=3D"174" height=3D"29" border=3D"0"></td>
</tr>
</table>
<table width=3D"576" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"576" height=3D"13"></td>
</tr>
</table>
<table width=3D"576" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"26"></td>
<td width=3D"219" valign=3D"top">
<table width=3D"219" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"8"></td>
</tr>
</table>
<table width=3D"219" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td style=3D"font-family:arial,helvetica,freesans,sans-serif;font-size:12px=
;line-height:15px;color:#000000"><strong>Dear Return,</strong>
<br>
<br>Welcome to Your Aviva Essentials, our customer newsletter jam-packed wi=
th tips and advice. What are you planning for the Easter holidays? If it's =
DIY or a family break we've got lots of great tips and inspiration.

<br><br><strong>In this issue of the Aviva eZine:</strong></td>
</tr>
</table>
<table width=3D"219" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"15"></td>
</tr>
</table>
<table width=3D"230" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"8" valign=3D"top">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_intro_bullet.gif" style=
=3D"display:block" width=3D"8" height=3D"9" border=3D"0"></td>
<td width=3D"222" valign=3D"top" style=3D"font-family:arial,helvetica,frees=
ans,sans-serif;font-size:12px;line-height:15px;color:#004fb6">
<a href=3D"#anchor1" style=3D"text-decoration:underline;color:#004fb6"><str=
ong>Keep the cost of driving down</strong></a></td>
</tr>
<tr>
<td width=3D"8" valign=3D"top">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_intro_bullet.gif" style=
=3D"display:block" width=3D"8" height=3D"9" border=3D"0"></td>
<td width=3D"201" valign=3D"top" style=3D"font-family:arial,helvetica,frees=
ans,sans-serif;font-size:12px;line-height:15px;color:#004fb6">
<a href=3D"#anchor2" style=3D"text-decoration:underline;color:#004fb6"><str=
ong>Top 5 family days out</strong></a></td>
<td width=3D"10"></td>
</tr>
<tr>
<td width=3D"8" valign=3D"top">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_intro_bullet.gif" style=
=3D"display:block" width=3D"8" height=3D"9" border=3D"0"></td>
<td width=3D"201" valign=3D"top" style=3D"font-family:arial,helvetica,frees=
ans,sans-serif;font-size:12px;line-height:15px;color:#004fb6">
<a href=3D"#anchor3" style=3D"text-decoration:underline;color:#004fb6"><str=
ong>Top 5 DIY checks</strong></a></td>
<td width=3D"10"></td>
</tr>
<tr>
<td width=3D"8" valign=3D"top">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_intro_bullet.gif" style=
=3D"display:block" width=3D"8" height=3D"9" border=3D"0"></td>
<td width=3D"201" valign=3D"top" style=3D"font-family:arial,helvetica,frees=
ans,sans-serif;font-size:12px;line-height:15px;color:#004fb6">
<a href=3D"#anchor4" style=3D"text-decoration:underline;color:#004fb6"><str=
ong>The latest security guidelines for travellers</strong></a></td>
<td width=3D"10"></td>
</tr>
<tr>
<td width=3D"8" valign=3D"top">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_intro_bullet.gif" style=
=3D"display:block" width=3D"8" height=3D"9" border=3D"0"></td>
<td width=3D"201" valign=3D"top" style=3D"font-family:arial,helvetica,frees=
ans,sans-serif;font-size:12px;line-height:15px;color:#004fb6">
<a href=3D"#anchor5" style=3D"text-decoration:underline;color:#004fb6"><str=
ong>Street to school - Sarah's* story</strong></a></td>
<td width=3D"10"></td>
</tr>
</table>
</td>
<td width=3D"10"></td>
<td width=3D"306" valign=3D"top">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_intro_img_3.jpg" style=
=3D"display:block" width=3D"306" height=3D"204" border=3D"0"></td>
<td width=3D"15"></td>
</tr>
</table>
<table width=3D"576" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"576" height=3D"5"></td>
</tr>
</table>
<table width=3D"500" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"25"></td>
<td width=3D"455" style=3D"font-family:arial,helvetica,freesans,sans-serif;=
font-size:12px;line-height:15px;color:#000000">
<br><strong>PS</strong> Thanks for all your previous feedback, check out th=
e cost savings tips we have put together for you.
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/complp?CLI=
ENTID=3D" target=3D"_blank" style=3D"text-decoration:underlined; color:#000=
000">Tell us more</a> about what you think of the eZine.
</td>
<td width=3D"20"></td>
</tr>
</table>
<table width=3D"576" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"576" height=3D"15"></td>
</tr>
</table>
<table width=3D"576" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"14"></td>
<td width=3D"377" valign=3D"top">

<table width=3D"377" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"16"></td>
</tr>
</table>
<table width=3D"377" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"377">
<a name=3D"anchor1" id=3D"anchor1"></a>
<table width=3D"377" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"1" bgcolor=3D"#c8c8c8"></td>
</tr>
</table>
<table width=3D"377" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"1" bgcolor=3D"#c8c8c8"></td>
<td width=3D"375" valign=3D"top">
<table width=3D"375" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"15"></td>
<td width=3D"204" valign=3D"top">
<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"10"></td>
</tr>
</table>
<table width=3D"204" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td style=3D"font-family:arial,helvetica,freesans,sans-serif;font-size:16px=
;line-height:19px;color:#004fb6"><strong>Keep the cost of driving down: be =
green</strong></td>
</tr>
</table>
<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"10"></td>
</tr>
</table>
<table width=3D"204" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td style=3D"font-family:arial,helvetica,freesans,sans-serif;font-size:12px=
;line-height:15px;color:#000000">
Save money at the pumps and go further on one tank of petrol with our green=
 driving tips, brought to you in association with experts at the RAC. You c=
ould see a 15% fuel efficiency improvement.</td>
</tr>
</table>
<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"10"></td>
</tr>
</table>
<table width=3D"211" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"211" height=3D"26" bgcolor=3D"#FFD900" background=3D"http://f.=
chtah.com/i/9/371928251/p2217_pod2_btn_bg.gif" style=3D"background-image:ur=
l('http://f.chtah.com/i/9/371928251/p2217_pod2_btn_bg.gif');">
<table width=3D"211" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td style=3D"font-family:arial,helvetica,freesans,sans-serif;font-size:11px=
;line-height:14px;color:#004eb5;text-align:center;">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/costfelp" =
style=3D"text-decoration:none;color:#004eb5" target=3D"_blank"><strong>Read=
 our money-saving tips</strong></a>
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/costfelp" =
target=3D"_blank">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_btn_arrow.gif" width=3D"=
14" height=3D"9" border=3D"0"></a></td>
</tr>
</table></td>
</tr>
</table></td>
<td width=3D"20"></td>
<td width=3D"136" valign=3D"top">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/costfelp" =
target=3D"_blank">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_coins_car.jpg" style=3D"=
display:block" width=3D"136" height=3D"196" alt=3D"Keep the cost of driving=
 down: be green" title=3D"Keep the cost of driving down: be green" border=
=3D"0"></a></td>
</tr>
</table></td>
<td width=3D"1" bgcolor=3D"#c8c8c8"></td>
</tr>
</table>
<table width=3D"377" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"1" bgcolor=3D"#c8c8c8"></td>
</tr>
</table></td>
</tr>
</table>

<table width=3D"377" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"16"></td>
</tr>
</table>

<table width=3D"377" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"377">
<a name=3D"anchor2" id=3D"anchor2"></a>
<table width=3D"377" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"1" bgcolor=3D"#c8c8c8"></td>
</tr>
</table>
<table width=3D"377" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"1" bgcolor=3D"#c8c8c8"></td>
<td width=3D"375" valign=3D"top">
<table width=3D"375" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"15"></td>
<td width=3D"204" valign=3D"top">
<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"10"></td>
</tr>
</table>
<table width=3D"204" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td style=3D"font-family:arial,helvetica,freesans,sans-serif;font-size:16px=
;line-height:19px;color:#004fb6"><strong>Top 5 family days out
<br></strong></td>
</tr>
</table>
<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"10"></td>
</tr>
</table>
<table width=3D"204" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td style=3D"font-family:arial,helvetica,freesans,sans-serif;font-size:12px=
;line-height:15px;color:#000000">The long bank holiday can only mean one th=
ing =E2=80=93 fun day trips! We've put together our top 5 days out under &p=
ound;100 =E2=80=93 and a couple of tips to survive any long car journeys wi=
th the kids.
</tr>
</table>
<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"10"></td>
</tr>
</table>
<table width=3D"181" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"181" height=3D"26" bgcolor=3D"#FFD900" background=3D"http://f.=
chtah.com/i/9/371928251/p2217_pod1_btn_bg.gif" style=3D"background-image:ur=
l('http://f.chtah.com/i/9/371928251/p2217_pod1_btn_bg.gif');">
<table width=3D"181" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td style=3D"font-family:arial,helvetica,freesans,sans-serif;font-size:11px=
;line-height:14px;color:#004eb5;text-align:center;">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/motorfelp"=
 style=3D"text-decoration:none;color:#004eb5" target=3D"_blank"><strong>Top=
 5 family days out</strong></a>
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/motorfelp"=
 target=3D"_blank">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_btn_arrow.gif" width=3D"=
14" height=3D"9" border=3D"0" title=3D"Top 5 family days out" alt=3D"Top 5 =
family days out"></a></td>
</tr>
</table></td>
</tr>
</table></td>
<td width=3D"20"></td>
<td width=3D"136" valign=3D"top">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/motorfelp"=
 target=3D"_blank">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_pod1_img_2a.jpg" style=
=3D"display:block" width=3D"136" height=3D"184" alt=3D"Days out with kids" =
title=3D"Days out with kids" border=3D"0"></a></td>
</tr>
</table></td>
<td width=3D"1" bgcolor=3D"#c8c8c8"></td>
</tr>
</table>
<table width=3D"377" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"1" bgcolor=3D"#c8c8c8"></td>
</tr>
</table></td>
</tr>
</table>

<table width=3D"377" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"16"></td>
</tr>
</table>

<table width=3D"377" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"377">
<a name=3D"anchor3" id=3D"anchor3"></a>
<table width=3D"377" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"1" bgcolor=3D"#c8c8c8"></td>
</tr>
</table>
<table width=3D"377" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"1" bgcolor=3D"#c8c8c8"></td>
<td width=3D"375" valign=3D"top">
<table width=3D"375" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"15"></td>
<td width=3D"204" valign=3D"top">
<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"10"></td>
</tr>
</table>
<table width=3D"204" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td style=3D"font-family:arial,helvetica,freesans,sans-serif;font-size:16px=
;line-height:19px;color:#004fb6"><strong>Top 5 DIY checks: get your house i=
n order this Easter</strong></td>
</tr>
</table>
<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"10"></td>
</tr>
</table>
<table width=3D"204" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td style=3D"font-family:arial,helvetica,freesans,sans-serif;font-size:12px=
;line-height:15px;color:#000000">Planning to decorate this Easter holiday? =
Make sure you've got the groundwork right first with our 5 helpful DIY chec=
ks. Even better, make the checks an annual habit and you'll sleep easier kn=
owing there's less chance any unwelcome surprises will surface.</td>
</tr>
</table>
<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"10"></td>
</tr>
</table>
<table width=3D"211" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"211" height=3D"26" bgcolor=3D"#FFD900" background=3D"http://f.=
chtah.com/i/9/371928251/p2217_pod2_btn_bg.gif" style=3D"background-image:ur=
l('http://f.chtah.com/i/9/371928251/p2217_pod2_btn_bg.gif');">
<table width=3D"211" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td style=3D"font-family:arial,helvetica,freesans,sans-serif;font-size:11px=
;line-height:14px;color:#004eb5;text-align:center;">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/homefelp" =
style=3D"text-decoration:none;color:#004eb5" target=3D"_blank"><strong>Chec=
k out our 5 DIY checks</strong></a>
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/homefelp" =
target=3D"_blank">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_btn_arrow.gif" width=3D"=
14" height=3D"9" border=3D"0" title=3D"Check out our 5 DIY checks" alt=3D"C=
heck out our 5 DIY checks"></a></td>
</tr>
</table>
</td>
</tr>
</table>
<table width=3D"211" cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr><=
td height=3D"15" bgcolor=3D"#FFFFFF"></td></tr></table>
</td>
<td width=3D"20"></td>
<td width=3D"136" valign=3D"top">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/homefelp" =
target=3D"_blank">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_pod2_img_d_2.jpg" style=
=3D"display:block" width=3D"136" height=3D"210" alt=3D"Check out our 5 DIY =
checks" title=3D"Check out our 5 DIY checks" border=3D"0"></a></td>
</tr>
</table></td>
<td width=3D"1" bgcolor=3D"#c8c8c8"></td>
</tr>
</table>
<table width=3D"377" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"1" bgcolor=3D"#c8c8c8"></td>
</tr>
</table></td>
</tr>
</table>

<table width=3D"377" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"16"></td>
</tr>
</table>
<table width=3D"377" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"377">
<a name=3D"anchor4" id=3D"anchor4"></a>
<table width=3D"377" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"1" bgcolor=3D"#c8c8c8"></td>
</tr>
</table>
<table width=3D"377" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"1" bgcolor=3D"#c8c8c8"></td>
<td width=3D"375" valign=3D"top">
<table width=3D"375" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"15"></td>
<td width=3D"204" valign=3D"top">
<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"10"></td>
</tr>
</table>
<table width=3D"204" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td style=3D"font-family:arial,helvetica,freesans,sans-serif;font-size:16px=
;line-height:19px;color:#004fb6">
<strong>Up-to-date security travel advice</strong></td>
</tr>
</table>
<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"10"></td>
</tr>
</table>
<table width=3D"204" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td style=3D"font-family:arial,helvetica,freesans,sans-serif;font-size:12px=
;line-height:15px;color:#000000">Going away? Saunter through the airports =
=E2=80=93 and ensure you're able to keep those luxury items in your handbag=
 =E2=80=93 by reading the latest security guidelines. Plus, what to do if y=
ou're ill while you're away.</td>
</tr>
</table>
<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"10"></td>
</tr>
</table>
<table width=3D"211" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"211" height=3D"26" bgcolor=3D"#FFD900" background=3D"http://f.=
chtah.com/i/9/371928251/p2217_pod2_btn_bg.gif" style=3D"background-image:ur=
l('http://f.chtah.com/i/9/371928251/p2217_pod2_btn_bg.gif');">
<table width=3D"211" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td style=3D"font-family:arial,helvetica,freesans,sans-serif;font-size:11px=
;line-height:14px;color:#004eb5;text-align:center;">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/travelfelp=
" style=3D"text-decoration:none;color:#004eb5" target=3D"_blank"><strong>Th=
e latest security guidelines</strong></a>
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/travelfelp=
" target=3D"_blank">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_btn_arrow.gif" width=3D"=
14" height=3D"9" border=3D"0" title=3D"The latest security guidelines" alt=
=3D"The latest security guidelines"></a></td>
</tr>
</table></td>
</tr>
</table></td>
<td width=3D"20"></td>
<td width=3D"136" valign=3D"top">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/travelfelp=
" target=3D"_blank">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_pod2_imga.jpg" style=3D"=
display:block" width=3D"136" height=3D"196" alt=3D"Up-to-date security trav=
el advice" title=3D"Up-to-date security travel advice" border=3D"0"></a></t=
d>
</tr>
</table></td>
<td width=3D"1" bgcolor=3D"#c8c8c8"></td>
</tr>
</table>
<table width=3D"377" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"1" bgcolor=3D"#c8c8c8"></td>
</tr>
</table></td>
</tr>
</table>
<table width=3D"377" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"16"></td>
</tr>
</table>
<table width=3D"377" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"377">
<a name=3D"anchor5" id=3D"anchor5"></a>
<table width=3D"377" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"1" bgcolor=3D"#c8c8c8"></td>
</tr>
</table>
<table width=3D"377" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"1" bgcolor=3D"#c8c8c8"></td>
<td width=3D"375" valign=3D"top">
<table width=3D"375" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"15"></td>
<td width=3D"204" valign=3D"top">
<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"10"></td>
</tr>
</table>
<table width=3D"204" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td style=3D"font-family:arial,helvetica,freesans,sans-serif;font-size:16px=
;line-height:19px;color:#004fb6"><strong>Street to school - Sarah's* story<=
/strong></td>
</tr>
</table>
<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"10"></td>
</tr>
</table>
<table width=3D"204" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td style=3D"font-family:arial,helvetica,freesans,sans-serif;font-size:12px=
;line-height:15px;color:#000000">
We've partnered with Railway Children, a charity who dedicates its work to =
helping vulnerable children like Sarah who are at risk on our streets. Sara=
h was reunited with her family and is now at college, thanks to support fro=
m Railway Children.
</td>
</tr>
</table>
<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"10"></td>
</tr>
</table>
<table width=3D"211" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"211" height=3D"26" bgcolor=3D"#FFD900" background=3D"http://f.=
chtah.com/i/9/371928251/p2217_pod2_btn_bg.gif" style=3D"background-image:ur=
l('http://f.chtah.com/i/9/371928251/p2217_pod2_btn_bg.gif');">
<table width=3D"211" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td style=3D"font-family:arial,helvetica,freesans,sans-serif;font-size:11px=
;line-height:8px;color:#004eb5;text-align:center;">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/sponsorlp"=
 style=3D"text-decoration:none;color:#004eb5" target=3D"_blank"><strong>Rea=
d about Street-to-school</strong></a>
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/sponsorlp"=
 target=3D"_blank">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_btn_arrow.gif" width=3D"=
14" height=3D"9" border=3D"0"></a></td>
</tr>
</table></td>
</tr>
</table>
<table width=3D"211" cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr><=
td height=3D"10" bgcolor=3D"#ffffff"></td></tr></table>
</td>
<td width=3D"20"></td>
<td width=3D"136" valign=3D"top">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/sponsorlp"=
 target=3D"_blank">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_pod2_imgb.jpg" style=3D"=
display:block" width=3D"136" height=3D"196" alt=3D"Street-to-school - Sarah=
's* story" title=3D"Street-to-school - Sarah's* story" border=3D"0"></a></t=
d>
</tr>
</table></td>
<td width=3D"1" bgcolor=3D"#c8c8c8"></td>
</tr>
</table>
<table width=3D"377" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"1" bgcolor=3D"#c8c8c8"></td>
</tr>
</table></td>
</tr>
</table>

<table width=3D"377" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"16"></td>
</tr>
</table> </td>
<td width=3D"18"></td>
<td width=3D"152" valign=3D"top">
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" bgcol=
or=3D"#d3ebf5">
<tr>
<td width=3D"152">
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"10"></td>
</tr>
</table>
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"8"></td>
<td width=3D"136" height=3D"25" valign=3D"top" style=3D"font-family:arial,h=
elvetica,freesans,sans-serif;font-size:14px;line-height:17px;color:#004fb6"=
><strong>Win 4 tickets to the Aviva Premiership Rubgy Final</strong></td>
<td width=3D"8"></td>
</tr>
</table>
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"10"></td>
</tr>
</table>
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"152">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/complp?CLI=
ENTID=3D" target=3D"_blank">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_winticks2.jpg" style=3D"=
display:block" width=3D"152" height=3D"115" alt=3D"Win 4 tickets to the Rub=
gy Premiership Final" title=3D"Win 4 tickets to the Rubgy Premiership Final=
" border=3D"0"></a></td>
</tr>
</table>
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"8"></td>
<td width=3D"136" valign=3D"top" style=3D"font-family:arial,helvetica,frees=
ans,sans-serif;font-size:11px;line-height:14px;color:#000000">
<br>
Win one of 3 sets of 4 tickets to the Aviva Premiership Rugby Final at Twic=
kenham Stadium on 28 May 2011
<br></td>
<td width=3D"8"></td>
</tr>
</table>
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"10"></td>
</tr>
</table>
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"6"></td>
<td width=3D"146">
<table width=3D"89" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"89" height=3D"25" bgcolor=3D"#FFD900" background=3D"http://f.c=
htah.com/i/9/371928251/p2217_wintv_btn_bg.gif" style=3D"background-image:ur=
l('http://f.chtah.com/i/9/371928251/p2217_wintv_btn_bg.gif');">
<table width=3D"89" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td style=3D"font-family:arial,helvetica,freesans,sans-serif;font-size:11px=
;line-height:14px;color:#004eb5;text-align:center;">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/complp?CLI=
ENTID=3D" style=3D"text-decoration:none;color:#004eb5" target=3D"_blank"><s=
trong>Enter now</strong></a>
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/complp?CLI=
ENTID=3D" target=3D"_blank">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_btn_arrow.gif" width=3D"=
14" height=3D"9" border=3D"0" title=3D"Enter now" alt=3D"Enter now"></a></t=
d>
</tr>
</table></td>
</tr>
</table></td>
</tr>
</table>
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"18"></td>
</tr>
</table></td>
</tr>
</table>
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"13"></td>
</tr>
</table>
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" bgcol=
or=3D"#ffffff">
<tr>
<td width=3D"152">
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" bgcol=
or=3D"#ffffff">
<tr>
<td width=3D"152" style=3D"font-family:arial,helvetica,verdana,freesans-san=
s-serif; font-size:14px; line-height:17px; color:#004fb6; text-align:left">=
<a href=3D"TBC" target=3D"_blank" style=3D"text-decoration:none; color:#004=
fb6"><strong>Winner of the November competition</strong></a></td>
</tr>
</table>
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" bgcol=
or=3D"#ffffff">
<tr>
<td width=3D"152" height=3D"10"></td>
</tr>
</table>
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" bgcol=
or=3D"#ffffff">
<tr>
<td width=3D"152" style=3D"font-family:arial,helvetica,verdana,freesans-san=
s-serif; font-size:12px; line-height:15px; color:#000000; text-align:left">=
<a href=3D"TBC" target=3D"_blank" style=3D"text-decoration:none; color:#000=
000">Joan Beesley, Merseyside, won a Sony HD TV and Blu-Ray player.<br>
<br>
&quot;The prize was brilliant, we were amazed at winning such a fantastic p=
rize and would just like to say thank you to everyone at Aviva&quot;</a></t=
d>
</tr>
</table>
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" bgcol=
or=3D"#ffffff">
<tr>
<td width=3D"152" height=3D"10"></td>
</tr>
</table>
<table width=3D"121" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"121" height=3D"26" bgcolor=3D"#FFD900" background=3D"http://f.=
chtah.com/i/9/371928251/p2217_pod2_btn_bg_new.gif" style=3D"background-imag=
e:url('http://f.chtah.com/i/9/371928251/p2217_pod2_btn_bg_new.gif');">
<table width=3D"121" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td style=3D"font-family:arial,helvetica,freesans,sans-serif;font-size:11px=
;line-height:14px;color:#004eb5;text-align:center;">
<a href=3D"TBC" style=3D"text-decoration:none;color:#004eb5" target=3D"_bla=
nk"><strong>Enter now</strong></a>
<a href=3D"TBC" target=3D"_blank">
<img src=3D"http://f.avivaemail.co.uk/i/9/371928251/p1920_btn_arrow.gif" wi=
dth=3D"14" height=3D"9" border=3D"0" title=3D"Top tips for getting fit at h=
ome" alt=3D"Top tips for getting fit at home"></a></td>
</tr>
</table>
</td>
</tr>
</table>
</td>
</tr>
</table>
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"20"></td>
</tr>
</table>

<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" bgcol=
or=3D"#d3ebf5">
<tr>
<td width=3D"152">
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"10"></td>
</tr>
</table>
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"8"></td>
<td width=3D"136" height=3D"25" valign=3D"top" style=3D"font-family:arial,h=
elvetica,freesans,sans-serif;font-size:14px;line-height:17px;color:#004fb6"=
><strong>My Policy</strong></td>
<td width=3D"8"></td>
</tr>
</table>
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"10"></td>
</tr>
</table>
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"152">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/mypollp" t=
arget=3D"_blank">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_mypolicy.jpg" style=3D"d=
isplay:block" width=3D"152" height=3D"115" alt=3D"My Policy" title=3D"My Po=
licy" border=3D"0"></a></td>
</tr>
</table>
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr><=
td height=3D"10" bgcolor=3D"#d3ebf5"></td></tr></table>
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"8"></td>
<td width=3D"136" valign=3D"top" style=3D"font-family:arial,helvetica,frees=
ans,sans-serif;font-size:11px;line-height:14px;color:#000000">
<table width=3D"136" cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr><=
td height=3D"5" bgcolor=3D"#d3ebf5"></td></tr></table>
Register for <strong>My Policy</strong> to:
<table width=3D"136" cellpadding=3D"0" cellspacing=3D"0" border=3D"0"><tr><=
td height=3D"10" bgcolor=3D"#d3ebf5"></td></tr></table>
<table width=3D"136" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" bgcol=
or=3D"#d3ebf5">
<tr>
<td width=3D"7" valign=3D"top">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_btn_arrow.gif" style=3D"=
display:block" width=3D"14" height=3D"9" border=3D"0"></td>
<td width=3D"5"></td>
<td style=3D"font-family:arial,helvetica,freesans,sans-serif;font-size:11px=
;line-height:14px;color:#000000">
Check your policy details
</td>
</tr>
</table>
<table width=3D"136" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" bgcol=
or=3D"#d3ebf5">
<tr>
<td width=3D"7">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_btn_arrow.gif" style=3D"=
display:block" width=3D"14" height=3D"9" border=3D"0"></td>
<td width=3D"5"></td>
<td style=3D"font-family:arial,helvetica,freesans,sans-serif;font-size:11px=
;line-height:14px;color:#000000">
Make a claim
</td>
</tr>
</table>
<table width=3D"136" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" bgcol=
or=3D"#d3ebf5">
<tr>
<td width=3D"7" valign=3D"top">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_btn_arrow.gif" style=3D"=
display:block" width=3D"14" height=3D"9" border=3D"0"></td>
<td width=3D"5"></td>
<td style=3D"font-family:arial,helvetica,freesans,sans-serif;font-size:11px=
;line-height:14px;color:#000000">
Change your cover
</td>
</tr>
</table>
<table width=3D"136" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" bgcol=
or=3D"#d3ebf5">
<tr>
<td width=3D"7" valign=3D"top">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_btn_arrow.gif" style=3D"=
display:block" width=3D"14" height=3D"9" border=3D"0"></td>
<td width=3D"5"></td>
<td style=3D"font-family:arial,helvetica,freesans,sans-serif;font-size:11px=
;line-height:14px;color:#000000">
Renew your policy online
</td>
</tr>
</table>
<table width=3D"136" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" bgcol=
or=3D"#d3ebf5">
<tr>
<td width=3D"7" valign=3D"top">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_btn_arrow.gif" style=3D"=
display:block" width=3D"14" height=3D"9" border=3D"0"></td>
<td width=3D"5"></td>
<td style=3D"font-family:arial,helvetica,freesans,sans-serif;font-size:11px=
;line-height:14px;color:#000000">
Benefit from an exclusive package of travel, leisure and high street offers.
</td>
</tr>
</table>
</td>
<td width=3D"8"></td>
</tr>
</table>
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"10"></td>
</tr>
</table>
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"6"></td>
<td width=3D"146">
<table width=3D"89" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"89" height=3D"25" bgcolor=3D"#FFD900" background=3D"http://f.c=
htah.com/i/9/371928251/p2217_wintv_btn_bg.gif" style=3D"background-image:ur=
l('http://f.chtah.com/i/9/371928251/p2217_wintv_btn_bg.gif');">
<table width=3D"89" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td style=3D"font-family:arial,helvetica,freesans,sans-serif;font-size:11px=
;line-height:14px;color:#004eb5;text-align:center;">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/mypollp" s=
tyle=3D"text-decoration:none;color:#004eb5" target=3D"_blank"><strong>My Po=
licy</strong></a>
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/mypollp" t=
arget=3D"_blank">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_btn_arrow.gif" width=3D"=
14" height=3D"9" border=3D"0" title=3D"My Policy" alt=3D"My Policy"></a></t=
d>
</tr>
</table></td>
</tr>
</table></td>
</tr>
</table>
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"18"></td>
</tr>
</table></td>
</tr>
</table>




<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"12"></td>
</tr>
</table>
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" bgcol=
or=3D"#ffd900">
<tr>
<td width=3D"14" height=3D"29"></td>
<td width=3D"138" style=3D"font-family:arial,helvetica,freesans,sans-serif;=
font-size:12px;line-height:15px;color:#004fb6;"><strong>Online tools</stron=
g></td>
</tr>
</table>
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"9"></td>
</tr>
</table>
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"24" valign=3D"top">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_ot_bullet.gif" style=3D"=
display:block" width=3D"24" height=3D"13" border=3D"0"></td>
<td width=3D"128" valign=3D"top" style=3D"font-family:arial,helvetica,frees=
ans,sans-serif;font-size:11px;line-height:14px;color:#003399;">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/mypollp" s=
tyle=3D"text-decoration:underline;color:#003399" target=3D"_blank">Update y=
our policy</a></td>
</tr>
<tr>
<td colspan=3D"2" height=3D"5"></td>
</tr>
<tr>
<td width=3D"24" valign=3D"top">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_ot_bullet.gif" style=3D"=
display:block" width=3D"24" height=3D"13" border=3D"0"></td>
<td width=3D"128" valign=3D"top" style=3D"font-family:arial,helvetica,frees=
ans,sans-serif;font-size:11px;line-height:14px;color:#003399;">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/concalclp"=
 style=3D"text-decoration:underline;color:#003399" target=3D"_blank">Home c=
ontents calculator</a></td>
</tr>
<tr>
<td colspan=3D"2" height=3D"5"></td>
</tr>
<tr>
<td width=3D"24" valign=3D"top">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_ot_bullet.gif" style=3D"=
display:block" width=3D"24" height=3D"13" border=3D"0"></td>
<td width=3D"128" valign=3D"top" style=3D"font-family:arial,helvetica,frees=
ans,sans-serif;font-size:11px;line-height:14px;color:#003399;">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/routelp" s=
tyle=3D"text-decoration:underline;color:#003399" target=3D"_blank">Route pl=
anner</a></td>
</tr>
<tr>
<td colspan=3D"2" height=3D"5"></td>
</tr>
<tr>
<td width=3D"24" valign=3D"top">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_ot_bullet.gif" style=3D"=
display:block" width=3D"24" height=3D"13" border=3D"0"></td>
<td width=3D"128" valign=3D"top" style=3D"font-family:arial,helvetica,frees=
ans,sans-serif;font-size:11px;line-height:14px;color:#003399;">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/claimslp" =
style=3D"text-decoration:underline;color:#003399" target=3D"_blank">My clai=
ms app for iPhone</a></td>
</tr>
</table>
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td height=3D"15"></td>
</tr>
</table>
<table width=3D"152" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"28">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/fbooklp" t=
arget=3D"_blank">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_icon_facebook.gif" style=
=3D"display:block" width=3D"28" height=3D"22" alt=3D"Facebook" title=3D"Fac=
ebook" border=3D"0"></a></td>
<td width=3D"66" style=3D"font-family:arial,helvetica,freesans,sans-serif;f=
ont-size:11px;line-height:14px;color:#666666;">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/fbooklp" s=
tyle=3D"text-decoration:none;color:#666666" target=3D"_blank"><strong>Faceb=
ook</strong></a></td>
<td width=3D"28">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/digglp" ta=
rget=3D"_blank">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_icon_digg.gif" style=3D"=
display:block" width=3D"28" height=3D"22" alt=3D"Digg" title=3D"Digg" borde=
r=3D"0"></a></td>
<td width=3D"30" style=3D"font-family:arial,helvetica,freesans,sans-serif;f=
ont-size:11px;line-height:14px;color:#666666;">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/digglp" st=
yle=3D"text-decoration:none;color:#666666" target=3D"_blank"><strong>Digg</=
strong></a></td>
</tr>
<tr>
<td colspan=3D"4" height=3D"5"></td>
</tr>
<tr>
<td width=3D"28">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/twitterlp"=
 target=3D"_blank">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_icon_twitter.gif" style=
=3D"display:block" width=3D"28" height=3D"22" alt=3D"Twitter" title=3D"Twit=
ter" border=3D"0"></a></td>
<td width=3D"66" style=3D"font-family:arial,helvetica,freesans,sans-serif;f=
ont-size:11px;line-height:14px;color:#666666;">
<a href=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/twitterlp"=
 style=3D"text-decoration:none;color:#666666" target=3D"_blank"><strong>Twi=
tter</strong></a></td>
<td width=3D"28"></td>
<td width=3D"30"></td>
</tr>
</table></td>
<td width=3D"15"></td>
</tr>
</table></td>
<td width=3D"1" bgcolor=3D"#b0b5b9"></td>
<td width=3D"1" bgcolor=3D"#c1c7cc"></td>
<td width=3D"1" bgcolor=3D"#d2dadd"></td>
<td width=3D"1" bgcolor=3D"#dee5ea"></td>
<td width=3D"1" bgcolor=3D"#e7eff4"></td>
<td width=3D"7"></td>
</tr>
</table>
<table width=3D"600" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"9"></td>
<td width=3D"584">
<img src=3D"http://f.chtah.com/i/9/371928251/p2217_main_footer.gif" style=
=3D"display:block" width=3D"584" height=3D"42" border=3D"0"></td>
<td width=3D"7"></td>
</tr>
</table>
<table width=3D"600" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
<tr>
<td width=3D"40"></td>
<td width=3D"540" style=3D"font-family:arial,helvetica,freesans,sans-serif;=
font-size:10px;line-height:13px;color:#0051b5;">
<br>
* Sarah is a fictious name, used to protect the individual's identity<br>
<br>
If you would prefer not to receive any further marketing information from A=
viva by email, simply send a
<a href=3D"mailto:rm-0bx6rw3raupta74au6m0rxbysph09qe@avivaemail.co.uk" styl=
e=3D"text-decoration:underline;color:#0051b5" target=3D"_blank">blank email=
 to us</a>.
This email and any files sent with it are intended only for the named recip=
ient. If you are not the named recipient please telephone/email the sender =
immediately. You should not disclose the content or take/retain/distribute =
any copies.

<br>
<br>Aviva Insurance UK Limited, Registered Office: 8 Surrey Street, Norwich=
 NR1 3NG. Registered in England No. 99122. Authorised and regulated by the =
Financial Services Authority.
<br>

<br>NFPZZA00011 Mar11</td>
<td width=3D"20"></td>
</tr>
</table></td>
</tr>
</table></td>
</tr>
</table>

<img src=3D"http://avivaemail.co.uk/a/hBNld25AWKyy7B8Z$5RAAAAAAcL/spacer.gi=
f">
</body></html>

--=bx6rw3raupta74au6m0rxbysph09qe--

