apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    technical-exercise: "Raw Message text parser to extract fields"
  labels:
    run: msgparser
  name: msgparser
  namespace: braintree
spec:
  replicas: 2
  selector:
    matchLabels:
      run: msgparser
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: msgparser
    spec:
      containers:
      - image: hemantrumde/msgparser:v2.0
        imagePullPolicy: Always
        name: msgparser
        ports:
        - containerPort: 4000
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
