apiVersion: v1
kind: Service
metadata:
  name: svc-msgparser-loadbalancer
  namespace: braintree
  annotations:
    title: "load balancer service for pods"
spec:
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
  type: LoadBalancer
  selector:
    run: msgparser
